<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Populates the actors table with countries, groups, organizations, and militias
     * involved in current active conflicts (2024-2025).
     */
    public function run(): void
    {
        $actors = [
            // ========================================
            // RUSSIA-UKRAINE WAR
            // ========================================
            [
                'name' => 'Russian Federation',
                'short_name' => 'Russia',
                'alias_names' => json_encode(['Russia', 'Russian Federation', 'RF']),
                'actor_type' => 'STATE',
                'country_id' => null, // Set after countries are seeded
                'primary_region' => 'Eastern Europe',
                'operational_areas' => json_encode(['Ukraine', 'Syria', 'Africa', 'Georgia']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 100,
                'flag_emoji' => '🇷🇺',
                'color_hex' => '#0039A6',
                'icon' => 'flag',
            ],
            [
                'name' => 'Ukraine',
                'short_name' => 'Ukraine',
                'alias_names' => json_encode(['Ukraine', 'UA']),
                'actor_type' => 'STATE',
                'primary_region' => 'Eastern Europe',
                'operational_areas' => json_encode(['Ukraine']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 100,
                'flag_emoji' => '🇺🇦',
                'color_hex' => '#0057B7',
                'icon' => 'flag',
            ],
            [
                'name' => 'Wagner Group',
                'short_name' => 'Wagner',
                'alias_names' => json_encode(['Wagner PMC', 'PMC Wagner', 'Wagner Mercenaries']),
                'actor_type' => 'PMC',
                'primary_region' => 'Global',
                'operational_areas' => json_encode(['Ukraine', 'Syria', 'Mali', 'CAR', 'Libya']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode(['us' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 85,
                'flag_emoji' => '🏴',
                'color_hex' => '#8B4513',
                'icon' => 'shield-alt',
                'founded_date' => '2014-01-01',
            ],
            [
                'name' => 'Donetsk People\'s Republic',
                'short_name' => 'DPR',
                'alias_names' => json_encode(['DNR', 'Donetsk PR']),
                'actor_type' => 'SEPARATIST',
                'primary_region' => 'Eastern Europe',
                'operational_areas' => json_encode(['Ukraine - Donetsk Oblast']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 75,
                'flag_emoji' => '🏳️',
                'color_hex' => '#000000',
                'icon' => 'users',
                'founded_date' => '2014-04-07',
            ],
            [
                'name' => 'Luhansk People\'s Republic',
                'short_name' => 'LPR',
                'alias_names' => json_encode(['LNR', 'Luhansk PR']),
                'actor_type' => 'SEPARATIST',
                'primary_region' => 'Eastern Europe',
                'operational_areas' => json_encode(['Ukraine - Luhansk Oblast']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 75,
                'flag_emoji' => '🏳️',
                'color_hex' => '#0056A7',
                'icon' => 'users',
                'founded_date' => '2014-04-27',
            ],

            // ========================================
            // ISRAEL-GAZA CONFLICT
            // ========================================
            [
                'name' => 'Israel',
                'short_name' => 'Israel',
                'alias_names' => json_encode(['State of Israel', 'Israel']),
                'actor_type' => 'STATE',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Israel', 'Gaza', 'West Bank', 'Lebanon', 'Syria']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 100,
                'flag_emoji' => '🇮🇱',
                'color_hex' => '#0038B8',
                'icon' => 'flag',
            ],
            [
                'name' => 'Hamas',
                'short_name' => 'Hamas',
                'alias_names' => json_encode(['Harakat al-Muqawama al-Islamiya', 'Islamic Resistance Movement', 'Izz ad-Din al-Qassam Brigades']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Gaza Strip', 'West Bank']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 95,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#00AA00',
                'icon' => 'users-cog',
                'founded_date' => '1987-12-14',
            ],
            [
                'name' => 'Palestinian Islamic Jihad',
                'short_name' => 'PIJ',
                'alias_names' => json_encode(['Islamic Jihad Movement in Palestine', 'Al-Quds Brigades']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Gaza Strip', 'West Bank']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDay(),
                'autocomplete_priority' => 85,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#009900',
                'icon' => 'users-cog',
            ],
            [
                'name' => 'Hezbollah',
                'short_name' => 'Hezbollah',
                'alias_names' => json_encode(['Party of God', 'Hizbullah', 'Hizballah']),
                'actor_type' => 'MILITIA',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Lebanon', 'Syria', 'Yemen']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 90,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#FFCC00',
                'icon' => 'fist-raised',
                'founded_date' => '1985-01-01',
            ],
            [
                'name' => 'Houthis',
                'short_name' => 'Houthis',
                'alias_names' => json_encode(['Ansar Allah', 'Ansarullah', 'Houthi Movement']),
                'actor_type' => 'INSURGENT',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Yemen', 'Red Sea', 'Saudi Arabia']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 88,
                'flag_emoji' => '🏴',
                'color_hex' => '#007A3D',
                'icon' => 'users',
                'founded_date' => '1992-01-01',
            ],

            // ========================================
            // SUDAN CIVIL WAR
            // ========================================
            [
                'name' => 'Sudanese Armed Forces',
                'short_name' => 'SAF',
                'alias_names' => json_encode(['Sudan Armed Forces', 'Sudanese Army']),
                'actor_type' => 'GOVERNMENT_FORCES',
                'primary_region' => 'Northeast Africa',
                'operational_areas' => json_encode(['Sudan']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 85,
                'flag_emoji' => '🇸🇩',
                'color_hex' => '#007229',
                'icon' => 'fighter-jet',
            ],
            [
                'name' => 'Rapid Support Forces',
                'short_name' => 'RSF',
                'alias_names' => json_encode(['Janjaweed', 'Rapid Support']),
                'actor_type' => 'MILITIA',
                'primary_region' => 'Northeast Africa',
                'operational_areas' => json_encode(['Sudan', 'Darfur']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 85,
                'flag_emoji' => '🏴',
                'color_hex' => '#D21034',
                'icon' => 'users',
                'founded_date' => '2013-08-01',
            ],

            // ========================================
            // MYANMAR CIVIL WAR
            // ========================================
            [
                'name' => 'Tatmadaw',
                'short_name' => 'Tatmadaw',
                'alias_names' => json_encode(['Myanmar Armed Forces', 'Burma Army']),
                'actor_type' => 'GOVERNMENT_FORCES',
                'primary_region' => 'Southeast Asia',
                'operational_areas' => json_encode(['Myanmar']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 80,
                'flag_emoji' => '🇲🇲',
                'color_hex' => '#FECB00',
                'icon' => 'fighter-jet',
            ],
            [
                'name' => 'People\'s Defense Force',
                'short_name' => 'PDF',
                'alias_names' => json_encode(['PDF Myanmar', 'People\'s Defense Forces']),
                'actor_type' => 'REBEL',
                'primary_region' => 'Southeast Asia',
                'operational_areas' => json_encode(['Myanmar']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 75,
                'flag_emoji' => '🚩',
                'color_hex' => '#EA2839',
                'icon' => 'users',
                'founded_date' => '2021-05-05',
            ],
            [
                'name' => 'Arakan Army',
                'short_name' => 'AA',
                'alias_names' => json_encode(['Arakan Army Myanmar']),
                'actor_type' => 'INSURGENT',
                'primary_region' => 'Southeast Asia',
                'operational_areas' => json_encode(['Myanmar - Rakhine State']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(1),
                'autocomplete_priority' => 70,
                'flag_emoji' => '🛡️',
                'color_hex' => '#034694',
                'icon' => 'users',
                'founded_date' => '2009-04-10',
            ],
            [
                'name' => 'Kachin Independence Army',
                'short_name' => 'KIA',
                'alias_names' => json_encode(['Kachin Independence Organisation']),
                'actor_type' => 'INSURGENT',
                'primary_region' => 'Southeast Asia',
                'operational_areas' => json_encode(['Myanmar - Kachin State']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 70,
                'flag_emoji' => '🛡️',
                'color_hex' => '#FF0000',
                'icon' => 'users',
            ],

            // ========================================
            // SYRIA
            // ========================================
            [
                'name' => 'Syrian Arab Army',
                'short_name' => 'SAA',
                'alias_names' => json_encode(['Syrian Army', 'Syrian Government Forces']),
                'actor_type' => 'GOVERNMENT_FORCES',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Syria']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(5),
                'autocomplete_priority' => 70,
                'flag_emoji' => '🇸🇾',
                'color_hex' => '#CE1126',
                'icon' => 'fighter-jet',
            ],
            [
                'name' => 'Syrian Democratic Forces',
                'short_name' => 'SDF',
                'alias_names' => json_encode(['YPG', 'Kurdish Forces', 'SDF-YPG']),
                'actor_type' => 'MILITIA',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Syria - Northeast']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(3),
                'autocomplete_priority' => 70,
                'flag_emoji' => '🛡️',
                'color_hex' => '#FFD700',
                'icon' => 'users',
                'founded_date' => '2015-10-10',
            ],
            [
                'name' => 'Hayat Tahrir al-Sham',
                'short_name' => 'HTS',
                'alias_names' => json_encode(['Al-Nusra Front', 'Jabhat al-Nusra', 'Tahrir al-Sham']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Syria - Idlib']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(4),
                'autocomplete_priority' => 75,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2017-01-28',
            ],

            // ========================================
            // SAHEL TERRORISM
            // ========================================
            [
                'name' => 'Jama\'at Nasr al-Islam wal Muslimin',
                'short_name' => 'JNIM',
                'alias_names' => json_encode(['GSIM', 'Al-Qaeda in the Sahel', 'Group for Support of Islam and Muslims']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Sahel',
                'operational_areas' => json_encode(['Mali', 'Burkina Faso', 'Niger']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(1),
                'autocomplete_priority' => 80,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2017-03-02',
            ],
            [
                'name' => 'Islamic State in the Greater Sahara',
                'short_name' => 'ISGS',
                'alias_names' => json_encode(['ISIS Sahara', 'Islamic State Sahel']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Sahel',
                'operational_areas' => json_encode(['Mali', 'Burkina Faso', 'Niger']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 80,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2015-05-01',
            ],
            [
                'name' => 'Boko Haram',
                'short_name' => 'Boko Haram',
                'alias_names' => json_encode(['Jama\'atu Ahlis Sunna Lidda\'awati wal-Jihad']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'West Africa',
                'operational_areas' => json_encode(['Nigeria', 'Chad', 'Cameroon', 'Niger']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(3),
                'autocomplete_priority' => 82,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2002-01-01',
            ],
            [
                'name' => 'Islamic State West Africa Province',
                'short_name' => 'ISWAP',
                'alias_names' => json_encode(['ISIS West Africa', 'Wilayat Gharb Ifriqiyyah']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'West Africa',
                'operational_areas' => json_encode(['Nigeria', 'Chad', 'Niger']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(1),
                'autocomplete_priority' => 82,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2016-03-12',
            ],
            [
                'name' => 'Al-Shabaab',
                'short_name' => 'Al-Shabaab',
                'alias_names' => json_encode(['Harakat al-Shabaab al-Mujahideen', 'Al-Shabab']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'East Africa',
                'operational_areas' => json_encode(['Somalia', 'Kenya']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 85,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2006-01-01',
            ],

            // ========================================
            // GLOBAL TERRORISM
            // ========================================
            [
                'name' => 'Islamic State',
                'short_name' => 'ISIS',
                'alias_names' => json_encode(['ISIL', 'Daesh', 'Islamic State of Iraq and Syria', 'IS']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Global',
                'operational_areas' => json_encode(['Iraq', 'Syria', 'Afghanistan', 'Africa', 'Southeast Asia']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 90,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2013-04-09',
            ],
            [
                'name' => 'Islamic State - Khorasan Province',
                'short_name' => 'ISIS-K',
                'alias_names' => json_encode(['IS-KP', 'ISKP', 'Islamic State Khorasan']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'South Asia',
                'operational_areas' => json_encode(['Afghanistan', 'Pakistan']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(1),
                'autocomplete_priority' => 85,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2015-01-10',
            ],
            [
                'name' => 'Al-Qaeda',
                'short_name' => 'AQ',
                'alias_names' => json_encode(['Al-Qaida', 'The Base', 'Qaeda']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Global',
                'operational_areas' => json_encode(['Afghanistan', 'Yemen', 'Syria', 'Sahel']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'low',
                'last_activity_date' => now()->subDays(15),
                'autocomplete_priority' => 75,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '1988-08-11',
            ],
            [
                'name' => 'Al-Qaeda in the Arabian Peninsula',
                'short_name' => 'AQAP',
                'alias_names' => json_encode(['Al-Qaeda Yemen', 'AQAP Yemen']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Yemen', 'Saudi Arabia']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(7),
                'autocomplete_priority' => 78,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2009-01-22',
            ],
            [
                'name' => 'Taliban',
                'short_name' => 'Taliban',
                'alias_names' => json_encode(['Islamic Emirate of Afghanistan', 'Afghan Taliban']),
                'actor_type' => 'INSURGENT',
                'primary_region' => 'South Asia',
                'operational_areas' => json_encode(['Afghanistan', 'Pakistan']),
                'is_state_actor' => true,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(3),
                'autocomplete_priority' => 85,
                'flag_emoji' => '🇦🇫',
                'color_hex' => '#000000',
                'icon' => 'users',
                'founded_date' => '1994-09-01',
            ],
            [
                'name' => 'Tehrik-i-Taliban Pakistan',
                'short_name' => 'TTP',
                'alias_names' => json_encode(['Pakistani Taliban', 'TTP Pakistan']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'South Asia',
                'operational_areas' => json_encode(['Pakistan', 'Afghanistan']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 80,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2007-12-14',
            ],

            // ========================================
            // MEXICAN CARTELS
            // ========================================
            [
                'name' => 'Sinaloa Cartel',
                'short_name' => 'Sinaloa',
                'alias_names' => json_encode(['Sinaloa Drug Cartel', 'Pacific Cartel']),
                'actor_type' => 'CARTEL',
                'primary_region' => 'North America',
                'operational_areas' => json_encode(['Mexico', 'United States']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 85,
                'flag_emoji' => '💊',
                'color_hex' => '#8B0000',
                'icon' => 'skull-crossbones',
            ],
            [
                'name' => 'Jalisco New Generation Cartel',
                'short_name' => 'CJNG',
                'alias_names' => json_encode(['Cartel Jalisco Nueva Generacion', 'CJNG Cartel']),
                'actor_type' => 'CARTEL',
                'primary_region' => 'North America',
                'operational_areas' => json_encode(['Mexico', 'United States']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 88,
                'flag_emoji' => '💊',
                'color_hex' => '#DC143C',
                'icon' => 'skull-crossbones',
                'founded_date' => '2010-01-01',
            ],
            [
                'name' => 'Los Zetas',
                'short_name' => 'Zetas',
                'alias_names' => json_encode(['Zetas Cartel', 'Los Zetas Cartel']),
                'actor_type' => 'CARTEL',
                'primary_region' => 'North America',
                'operational_areas' => json_encode(['Mexico', 'Guatemala']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(5),
                'autocomplete_priority' => 75,
                'flag_emoji' => '💊',
                'color_hex' => '#800000',
                'icon' => 'skull-crossbones',
                'founded_date' => '1999-01-01',
            ],
            [
                'name' => 'Gulf Cartel',
                'short_name' => 'CDG',
                'alias_names' => json_encode(['Cartel del Golfo', 'Gulf Cartel Mexico']),
                'actor_type' => 'CARTEL',
                'primary_region' => 'North America',
                'operational_areas' => json_encode(['Mexico']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(4),
                'autocomplete_priority' => 75,
                'flag_emoji' => '💊',
                'color_hex' => '#B22222',
                'icon' => 'skull-crossbones',
            ],

            // ========================================
            // COLOMBIA & LATIN AMERICA
            // ========================================
            [
                'name' => 'National Liberation Army',
                'short_name' => 'ELN',
                'alias_names' => json_encode(['Ejercito de Liberacion Nacional', 'ELN Colombia']),
                'actor_type' => 'INSURGENT',
                'primary_region' => 'South America',
                'operational_areas' => json_encode(['Colombia', 'Venezuela']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(6),
                'autocomplete_priority' => 70,
                'flag_emoji' => '🚩',
                'color_hex' => '#FF0000',
                'icon' => 'users',
                'founded_date' => '1964-07-04',
            ],

            // ========================================
            // DEMOCRATIC REPUBLIC OF CONGO
            // ========================================
            [
                'name' => 'M23',
                'short_name' => 'M23',
                'alias_names' => json_encode(['March 23 Movement', 'Mouvement du 23-Mars']),
                'actor_type' => 'REBEL',
                'primary_region' => 'Central Africa',
                'operational_areas' => json_encode(['Democratic Republic of Congo']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDay(),
                'autocomplete_priority' => 78,
                'flag_emoji' => '🚩',
                'color_hex' => '#007FFF',
                'icon' => 'users',
                'founded_date' => '2012-04-04',
            ],
            [
                'name' => 'Allied Democratic Forces',
                'short_name' => 'ADF',
                'alias_names' => json_encode(['ADF-NALU', 'Allied Democratic Forces Uganda']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Central Africa',
                'operational_areas' => json_encode(['Democratic Republic of Congo', 'Uganda']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 75,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '1995-01-01',
            ],

            // ========================================
            // KASHMIR
            // ========================================
            [
                'name' => 'Lashkar-e-Taiba',
                'short_name' => 'LeT',
                'alias_names' => json_encode(['Army of the Good', 'Lashkar-e-Tayyiba']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'South Asia',
                'operational_areas' => json_encode(['Pakistan', 'India - Kashmir']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'low',
                'last_activity_date' => now()->subDays(45),
                'autocomplete_priority' => 65,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '1990-01-01',
            ],
            [
                'name' => 'Jaish-e-Mohammed',
                'short_name' => 'JeM',
                'alias_names' => json_encode(['Army of Mohammed', 'Jaish-e-Mohammad']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'South Asia',
                'operational_areas' => json_encode(['Pakistan', 'India - Kashmir']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'low',
                'last_activity_date' => now()->subDays(50),
                'autocomplete_priority' => 65,
                'flag_emoji' => '🏴‍☠️',
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2000-01-31',
            ],

            // ========================================
            // ALL COUNTRIES (with flag emojis)
            // ========================================
            ['name' => 'United States of America', 'short_name' => 'USA', 'alias_names' => json_encode(['United States', 'US', 'America']), 'actor_type' => 'STATE', 'primary_region' => 'North America', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 50, 'flag_emoji' => '🇺🇸', 'color_hex' => '#3C3B6E', 'icon' => 'flag'],
            ['name' => 'China', 'short_name' => 'China', 'alias_names' => json_encode(['People\'s Republic of China', 'PRC']), 'actor_type' => 'STATE', 'primary_region' => 'East Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 50, 'flag_emoji' => '🇨🇳', 'color_hex' => '#DE2910', 'icon' => 'flag'],
            ['name' => 'United Kingdom', 'short_name' => 'UK', 'alias_names' => json_encode(['Britain', 'Great Britain', 'England']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇬🇧', 'color_hex' => '#012169', 'icon' => 'flag'],
            ['name' => 'France', 'short_name' => 'France', 'alias_names' => json_encode(['French Republic']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇫🇷', 'color_hex' => '#0055A4', 'icon' => 'flag'],
            ['name' => 'Germany', 'short_name' => 'Germany', 'alias_names' => json_encode(['Federal Republic of Germany', 'Deutschland']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇩🇪', 'color_hex' => '#000000', 'icon' => 'flag'],
            ['name' => 'Japan', 'short_name' => 'Japan', 'alias_names' => json_encode(['Nippon', 'Japan']), 'actor_type' => 'STATE', 'primary_region' => 'East Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 40, 'flag_emoji' => '🇯🇵', 'color_hex' => '#BC002D', 'icon' => 'flag'],
            ['name' => 'South Korea', 'short_name' => 'South Korea', 'alias_names' => json_encode(['Republic of Korea', 'ROK', 'Korea']), 'actor_type' => 'STATE', 'primary_region' => 'East Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 40, 'flag_emoji' => '🇰🇷', 'color_hex' => '#003478', 'icon' => 'flag'],
            ['name' => 'North Korea', 'short_name' => 'North Korea', 'alias_names' => json_encode(['DPRK', 'Democratic People\'s Republic of Korea']), 'actor_type' => 'STATE', 'primary_region' => 'East Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 55, 'flag_emoji' => '🇰🇵', 'color_hex' => '#024FA2', 'icon' => 'flag'],
            ['name' => 'India', 'short_name' => 'India', 'alias_names' => json_encode(['Republic of India', 'Bharat']), 'actor_type' => 'STATE', 'primary_region' => 'South Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 50, 'flag_emoji' => '🇮🇳', 'color_hex' => '#FF9933', 'icon' => 'flag'],
            ['name' => 'Pakistan', 'short_name' => 'Pakistan', 'alias_names' => json_encode(['Islamic Republic of Pakistan']), 'actor_type' => 'STATE', 'primary_region' => 'South Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'medium', 'autocomplete_priority' => 55, 'flag_emoji' => '🇵🇰', 'color_hex' => '#01411C', 'icon' => 'flag'],
            ['name' => 'Iran', 'short_name' => 'Iran', 'alias_names' => json_encode(['Islamic Republic of Iran', 'Persia']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'medium', 'autocomplete_priority' => 75, 'flag_emoji' => '🇮🇷', 'color_hex' => '#239F40', 'icon' => 'flag'],
            ['name' => 'Iraq', 'short_name' => 'Iraq', 'alias_names' => json_encode(['Republic of Iraq']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 50, 'flag_emoji' => '🇮🇶', 'color_hex' => '#007A3D', 'icon' => 'flag'],
            ['name' => 'Saudi Arabia', 'short_name' => 'Saudi Arabia', 'alias_names' => json_encode(['Kingdom of Saudi Arabia', 'KSA']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'medium', 'autocomplete_priority' => 65, 'flag_emoji' => '🇸🇦', 'color_hex' => '#006C35', 'icon' => 'flag'],
            ['name' => 'Turkey', 'short_name' => 'Turkey', 'alias_names' => json_encode(['Republic of Türkiye', 'Türkiye']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'medium', 'autocomplete_priority' => 65, 'flag_emoji' => '🇹🇷', 'color_hex' => '#E30A17', 'icon' => 'flag'],
            ['name' => 'Egypt', 'short_name' => 'Egypt', 'alias_names' => json_encode(['Arab Republic of Egypt']), 'actor_type' => 'STATE', 'primary_region' => 'North Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇪🇬', 'color_hex' => '#CE1126', 'icon' => 'flag'],
            ['name' => 'South Africa', 'short_name' => 'South Africa', 'alias_names' => json_encode(['RSA', 'Republic of South Africa']), 'actor_type' => 'STATE', 'primary_region' => 'Southern Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇿🇦', 'color_hex' => '#007A4D', 'icon' => 'flag'],
            ['name' => 'Nigeria', 'short_name' => 'Nigeria', 'alias_names' => json_encode(['Federal Republic of Nigeria']), 'actor_type' => 'STATE', 'primary_region' => 'West Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'medium', 'autocomplete_priority' => 55, 'flag_emoji' => '🇳🇬', 'color_hex' => '#008751', 'icon' => 'flag'],
            ['name' => 'Ethiopia', 'short_name' => 'Ethiopia', 'alias_names' => json_encode(['Federal Democratic Republic of Ethiopia']), 'actor_type' => 'STATE', 'primary_region' => 'East Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'medium', 'autocomplete_priority' => 55, 'flag_emoji' => '🇪🇹', 'color_hex' => '#009A44', 'icon' => 'flag'],
            ['name' => 'Kenya', 'short_name' => 'Kenya', 'alias_names' => json_encode(['Republic of Kenya']), 'actor_type' => 'STATE', 'primary_region' => 'East Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 40, 'flag_emoji' => '🇰🇪', 'color_hex' => '#006600', 'icon' => 'flag'],
            ['name' => 'Somalia', 'short_name' => 'Somalia', 'alias_names' => json_encode(['Federal Republic of Somalia']), 'actor_type' => 'STATE', 'primary_region' => 'East Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'high', 'autocomplete_priority' => 70, 'flag_emoji' => '🇸🇴', 'color_hex' => '#4189DD', 'icon' => 'flag'],
            ['name' => 'Democratic Republic of the Congo', 'short_name' => 'DRC', 'alias_names' => json_encode(['DR Congo', 'Congo-Kinshasa', 'DRC']), 'actor_type' => 'STATE', 'primary_region' => 'Central Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'high', 'autocomplete_priority' => 70, 'flag_emoji' => '🇨🇩', 'color_hex' => '#007FFF', 'icon' => 'flag'],
            ['name' => 'Mali', 'short_name' => 'Mali', 'alias_names' => json_encode(['Republic of Mali']), 'actor_type' => 'STATE', 'primary_region' => 'West Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'high', 'autocomplete_priority' => 65, 'flag_emoji' => '🇲🇱', 'color_hex' => '#14B53A', 'icon' => 'flag'],
            ['name' => 'Burkina Faso', 'short_name' => 'Burkina Faso', 'alias_names' => json_encode(['Burkina']), 'actor_type' => 'STATE', 'primary_region' => 'West Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'high', 'autocomplete_priority' => 65, 'flag_emoji' => '🇧🇫', 'color_hex' => '#EF2B2D', 'icon' => 'flag'],
            ['name' => 'Niger', 'short_name' => 'Niger', 'alias_names' => json_encode(['Republic of Niger']), 'actor_type' => 'STATE', 'primary_region' => 'West Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'medium', 'autocomplete_priority' => 60, 'flag_emoji' => '🇳🇪', 'color_hex' => '#E05206', 'icon' => 'flag'],
            ['name' => 'Chad', 'short_name' => 'Chad', 'alias_names' => json_encode(['Republic of Chad']), 'actor_type' => 'STATE', 'primary_region' => 'Central Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇹🇩', 'color_hex' => '#002664', 'icon' => 'flag'],
            ['name' => 'Cameroon', 'short_name' => 'Cameroon', 'alias_names' => json_encode(['Republic of Cameroon']), 'actor_type' => 'STATE', 'primary_region' => 'Central Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇨🇲', 'color_hex' => '#007A5E', 'icon' => 'flag'],
            ['name' => 'Central African Republic', 'short_name' => 'CAR', 'alias_names' => json_encode(['CAR', 'Central Africa']), 'actor_type' => 'STATE', 'primary_region' => 'Central Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'medium', 'autocomplete_priority' => 55, 'flag_emoji' => '🇨🇫', 'color_hex' => '#003082', 'icon' => 'flag'],
            ['name' => 'Uganda', 'short_name' => 'Uganda', 'alias_names' => json_encode(['Republic of Uganda']), 'actor_type' => 'STATE', 'primary_region' => 'East Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 40, 'flag_emoji' => '🇺🇬', 'color_hex' => '#000000', 'icon' => 'flag'],
            ['name' => 'Rwanda', 'short_name' => 'Rwanda', 'alias_names' => json_encode(['Republic of Rwanda']), 'actor_type' => 'STATE', 'primary_region' => 'East Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'medium', 'autocomplete_priority' => 50, 'flag_emoji' => '🇷🇼', 'color_hex' => '#00A1DE', 'icon' => 'flag'],
            ['name' => 'Brazil', 'short_name' => 'Brazil', 'alias_names' => json_encode(['Federative Republic of Brazil', 'Brasil']), 'actor_type' => 'STATE', 'primary_region' => 'South America', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇧🇷', 'color_hex' => '#009C3B', 'icon' => 'flag'],
            ['name' => 'Argentina', 'short_name' => 'Argentina', 'alias_names' => json_encode(['Argentine Republic']), 'actor_type' => 'STATE', 'primary_region' => 'South America', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇦🇷', 'color_hex' => '#75AADB', 'icon' => 'flag'],
            ['name' => 'Colombia', 'short_name' => 'Colombia', 'alias_names' => json_encode(['Republic of Colombia']), 'actor_type' => 'STATE', 'primary_region' => 'South America', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'medium', 'autocomplete_priority' => 55, 'flag_emoji' => '🇨🇴', 'color_hex' => '#FCD116', 'icon' => 'flag'],
            ['name' => 'Venezuela', 'short_name' => 'Venezuela', 'alias_names' => json_encode(['Bolivarian Republic of Venezuela']), 'actor_type' => 'STATE', 'primary_region' => 'South America', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇻🇪', 'color_hex' => '#FFCC00', 'icon' => 'flag'],
            ['name' => 'Mexico', 'short_name' => 'Mexico', 'alias_names' => json_encode(['United Mexican States']), 'actor_type' => 'STATE', 'primary_region' => 'North America', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'high', 'autocomplete_priority' => 70, 'flag_emoji' => '🇲🇽', 'color_hex' => '#006847', 'icon' => 'flag'],
            ['name' => 'Canada', 'short_name' => 'Canada', 'alias_names' => json_encode(['Canada']), 'actor_type' => 'STATE', 'primary_region' => 'North America', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇨🇦', 'color_hex' => '#FF0000', 'icon' => 'flag'],
            ['name' => 'Australia', 'short_name' => 'Australia', 'alias_names' => json_encode(['Commonwealth of Australia']), 'actor_type' => 'STATE', 'primary_region' => 'Oceania', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇦🇺', 'color_hex' => '#00008B', 'icon' => 'flag'],
            ['name' => 'New Zealand', 'short_name' => 'New Zealand', 'alias_names' => json_encode(['Aotearoa']), 'actor_type' => 'STATE', 'primary_region' => 'Oceania', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇳🇿', 'color_hex' => '#00247D', 'icon' => 'flag'],
            ['name' => 'Poland', 'short_name' => 'Poland', 'alias_names' => json_encode(['Republic of Poland', 'Polska']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇵🇱', 'color_hex' => '#DC143C', 'icon' => 'flag'],
            ['name' => 'Romania', 'short_name' => 'Romania', 'alias_names' => json_encode(['Romania']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇷🇴', 'color_hex' => '#002B7F', 'icon' => 'flag'],
            ['name' => 'Hungary', 'short_name' => 'Hungary', 'alias_names' => json_encode(['Hungary', 'Magyarország']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇭🇺', 'color_hex' => '#436F4D', 'icon' => 'flag'],
            ['name' => 'Czech Republic', 'short_name' => 'Czechia', 'alias_names' => json_encode(['Czechia', 'Czech Republic']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇨🇿', 'color_hex' => '#11457E', 'icon' => 'flag'],
            ['name' => 'Slovakia', 'short_name' => 'Slovakia', 'alias_names' => json_encode(['Slovak Republic']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇸🇰', 'color_hex' => '#0B4EA2', 'icon' => 'flag'],
            ['name' => 'Austria', 'short_name' => 'Austria', 'alias_names' => json_encode(['Republic of Austria', 'Österreich']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇦🇹', 'color_hex' => '#ED2939', 'icon' => 'flag'],
            ['name' => 'Switzerland', 'short_name' => 'Switzerland', 'alias_names' => json_encode(['Swiss Confederation', 'Schweiz']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇨🇭', 'color_hex' => '#FF0000', 'icon' => 'flag'],
            ['name' => 'Netherlands', 'short_name' => 'Netherlands', 'alias_names' => json_encode(['Holland', 'Kingdom of the Netherlands']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇳🇱', 'color_hex' => '#21468B', 'icon' => 'flag'],
            ['name' => 'Belgium', 'short_name' => 'Belgium', 'alias_names' => json_encode(['Kingdom of Belgium']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇧🇪', 'color_hex' => '#000000', 'icon' => 'flag'],
            ['name' => 'Spain', 'short_name' => 'Spain', 'alias_names' => json_encode(['Kingdom of Spain', 'España']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇪🇸', 'color_hex' => '#AA151B', 'icon' => 'flag'],
            ['name' => 'Portugal', 'short_name' => 'Portugal', 'alias_names' => json_encode(['Portuguese Republic']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇵🇹', 'color_hex' => '#006600', 'icon' => 'flag'],
            ['name' => 'Italy', 'short_name' => 'Italy', 'alias_names' => json_encode(['Italian Republic', 'Italia']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇮🇹', 'color_hex' => '#009246', 'icon' => 'flag'],
            ['name' => 'Greece', 'short_name' => 'Greece', 'alias_names' => json_encode(['Hellenic Republic', 'Hellas']), 'actor_type' => 'STATE', 'primary_region' => 'Southern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇬🇷', 'color_hex' => '#0D5EAF', 'icon' => 'flag'],
            ['name' => 'Bulgaria', 'short_name' => 'Bulgaria', 'alias_names' => json_encode(['Republic of Bulgaria']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇧🇬', 'color_hex' => '#00966E', 'icon' => 'flag'],
            ['name' => 'Serbia', 'short_name' => 'Serbia', 'alias_names' => json_encode(['Republic of Serbia']), 'actor_type' => 'STATE', 'primary_region' => 'Southern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 40, 'flag_emoji' => '🇷🇸', 'color_hex' => '#C6363C', 'icon' => 'flag'],
            ['name' => 'Croatia', 'short_name' => 'Croatia', 'alias_names' => json_encode(['Republic of Croatia', 'Hrvatska']), 'actor_type' => 'STATE', 'primary_region' => 'Southern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇭🇷', 'color_hex' => '#FF0000', 'icon' => 'flag'],
            ['name' => 'Slovenia', 'short_name' => 'Slovenia', 'alias_names' => json_encode(['Republic of Slovenia']), 'actor_type' => 'STATE', 'primary_region' => 'Southern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇸🇮', 'color_hex' => '#005DA4', 'icon' => 'flag'],
            ['name' => 'Bosnia and Herzegovina', 'short_name' => 'Bosnia', 'alias_names' => json_encode(['BiH', 'Bosnia-Herzegovina']), 'actor_type' => 'STATE', 'primary_region' => 'Southern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇧🇦', 'color_hex' => '#002395', 'icon' => 'flag'],
            ['name' => 'North Macedonia', 'short_name' => 'N. Macedonia', 'alias_names' => json_encode(['Republic of North Macedonia', 'Macedonia']), 'actor_type' => 'STATE', 'primary_region' => 'Southern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇲🇰', 'color_hex' => '#D20000', 'icon' => 'flag'],
            ['name' => 'Albania', 'short_name' => 'Albania', 'alias_names' => json_encode(['Republic of Albania']), 'actor_type' => 'STATE', 'primary_region' => 'Southern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇦🇱', 'color_hex' => '#E41E20', 'icon' => 'flag'],
            ['name' => 'Kosovo', 'short_name' => 'Kosovo', 'alias_names' => json_encode(['Republic of Kosovo']), 'actor_type' => 'STATE', 'primary_region' => 'Southern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 40, 'flag_emoji' => '🇽🇰', 'color_hex' => '#244AA5', 'icon' => 'flag'],
            ['name' => 'Montenegro', 'short_name' => 'Montenegro', 'alias_names' => json_encode(['Montenegro']), 'actor_type' => 'STATE', 'primary_region' => 'Southern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇲🇪', 'color_hex' => '#C40308', 'icon' => 'flag'],
            ['name' => 'Moldova', 'short_name' => 'Moldova', 'alias_names' => json_encode(['Republic of Moldova']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇲🇩', 'color_hex' => '#003DA5', 'icon' => 'flag'],
            ['name' => 'Belarus', 'short_name' => 'Belarus', 'alias_names' => json_encode(['Republic of Belarus']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'medium', 'autocomplete_priority' => 60, 'flag_emoji' => '🇧🇾', 'color_hex' => '#C8313E', 'icon' => 'flag'],
            ['name' => 'Lithuania', 'short_name' => 'Lithuania', 'alias_names' => json_encode(['Republic of Lithuania']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇱🇹', 'color_hex' => '#006A44', 'icon' => 'flag'],
            ['name' => 'Latvia', 'short_name' => 'Latvia', 'alias_names' => json_encode(['Republic of Latvia']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇱🇻', 'color_hex' => '#9E3039', 'icon' => 'flag'],
            ['name' => 'Estonia', 'short_name' => 'Estonia', 'alias_names' => json_encode(['Republic of Estonia']), 'actor_type' => 'STATE', 'primary_region' => 'Eastern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇪🇪', 'color_hex' => '#0072CE', 'icon' => 'flag'],
            ['name' => 'Finland', 'short_name' => 'Finland', 'alias_names' => json_encode(['Republic of Finland', 'Suomi']), 'actor_type' => 'STATE', 'primary_region' => 'Northern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇫🇮', 'color_hex' => '#003580', 'icon' => 'flag'],
            ['name' => 'Sweden', 'short_name' => 'Sweden', 'alias_names' => json_encode(['Kingdom of Sweden', 'Sverige']), 'actor_type' => 'STATE', 'primary_region' => 'Northern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇸🇪', 'color_hex' => '#006AA7', 'icon' => 'flag'],
            ['name' => 'Norway', 'short_name' => 'Norway', 'alias_names' => json_encode(['Kingdom of Norway', 'Norge']), 'actor_type' => 'STATE', 'primary_region' => 'Northern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇳🇴', 'color_hex' => '#BA0C2F', 'icon' => 'flag'],
            ['name' => 'Denmark', 'short_name' => 'Denmark', 'alias_names' => json_encode(['Kingdom of Denmark', 'Danmark']), 'actor_type' => 'STATE', 'primary_region' => 'Northern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇩🇰', 'color_hex' => '#C60C30', 'icon' => 'flag'],
            ['name' => 'Iceland', 'short_name' => 'Iceland', 'alias_names' => json_encode(['Republic of Iceland', 'Ísland']), 'actor_type' => 'STATE', 'primary_region' => 'Northern Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇮🇸', 'color_hex' => '#02529C', 'icon' => 'flag'],
            ['name' => 'Ireland', 'short_name' => 'Ireland', 'alias_names' => json_encode(['Republic of Ireland', 'Éire']), 'actor_type' => 'STATE', 'primary_region' => 'Western Europe', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇮🇪', 'color_hex' => '#169B62', 'icon' => 'flag'],
            ['name' => 'Yemen', 'short_name' => 'Yemen', 'alias_names' => json_encode(['Republic of Yemen']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'high', 'autocomplete_priority' => 75, 'flag_emoji' => '🇾🇪', 'color_hex' => '#CE1126', 'icon' => 'flag'],
            ['name' => 'Lebanon', 'short_name' => 'Lebanon', 'alias_names' => json_encode(['Lebanese Republic']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'high', 'autocomplete_priority' => 70, 'flag_emoji' => '🇱🇧', 'color_hex' => '#ED1C24', 'icon' => 'flag'],
            ['name' => 'Jordan', 'short_name' => 'Jordan', 'alias_names' => json_encode(['Hashemite Kingdom of Jordan']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇯🇴', 'color_hex' => '#007A3D', 'icon' => 'flag'],
            ['name' => 'United Arab Emirates', 'short_name' => 'UAE', 'alias_names' => json_encode(['UAE', 'Emirates']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'medium', 'autocomplete_priority' => 50, 'flag_emoji' => '🇦🇪', 'color_hex' => '#FF0000', 'icon' => 'flag'],
            ['name' => 'Qatar', 'short_name' => 'Qatar', 'alias_names' => json_encode(['State of Qatar']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇶🇦', 'color_hex' => '#8D1B3D', 'icon' => 'flag'],
            ['name' => 'Kuwait', 'short_name' => 'Kuwait', 'alias_names' => json_encode(['State of Kuwait']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇰🇼', 'color_hex' => '#007A3D', 'icon' => 'flag'],
            ['name' => 'Bahrain', 'short_name' => 'Bahrain', 'alias_names' => json_encode(['Kingdom of Bahrain']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇧🇭', 'color_hex' => '#CE1126', 'icon' => 'flag'],
            ['name' => 'Oman', 'short_name' => 'Oman', 'alias_names' => json_encode(['Sultanate of Oman']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇴🇲', 'color_hex' => '#EF2B2D', 'icon' => 'flag'],
            ['name' => 'Palestine', 'short_name' => 'Palestine', 'alias_names' => json_encode(['State of Palestine', 'Palestinian Territories']), 'actor_type' => 'STATE', 'primary_region' => 'Middle East', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'high', 'autocomplete_priority' => 80, 'flag_emoji' => '🇵🇸', 'color_hex' => '#007A3D', 'icon' => 'flag'],
            ['name' => 'Azerbaijan', 'short_name' => 'Azerbaijan', 'alias_names' => json_encode(['Republic of Azerbaijan']), 'actor_type' => 'STATE', 'primary_region' => 'Caucasus', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇦🇿', 'color_hex' => '#00B9E4', 'icon' => 'flag'],
            ['name' => 'Armenia', 'short_name' => 'Armenia', 'alias_names' => json_encode(['Republic of Armenia']), 'actor_type' => 'STATE', 'primary_region' => 'Caucasus', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇦🇲', 'color_hex' => '#D90012', 'icon' => 'flag'],
            ['name' => 'Georgia', 'short_name' => 'Georgia', 'alias_names' => json_encode(['Sakartvelo']), 'actor_type' => 'STATE', 'primary_region' => 'Caucasus', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 45, 'flag_emoji' => '🇬🇪', 'color_hex' => '#FF0000', 'icon' => 'flag'],
            ['name' => 'Kazakhstan', 'short_name' => 'Kazakhstan', 'alias_names' => json_encode(['Republic of Kazakhstan']), 'actor_type' => 'STATE', 'primary_region' => 'Central Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇰🇿', 'color_hex' => '#00AFCA', 'icon' => 'flag'],
            ['name' => 'Uzbekistan', 'short_name' => 'Uzbekistan', 'alias_names' => json_encode(['Republic of Uzbekistan']), 'actor_type' => 'STATE', 'primary_region' => 'Central Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇺🇿', 'color_hex' => '#1EB53A', 'icon' => 'flag'],
            ['name' => 'Turkmenistan', 'short_name' => 'Turkmenistan', 'alias_names' => json_encode(['Turkmenistan']), 'actor_type' => 'STATE', 'primary_region' => 'Central Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇹🇲', 'color_hex' => '#00843D', 'icon' => 'flag'],
            ['name' => 'Tajikistan', 'short_name' => 'Tajikistan', 'alias_names' => json_encode(['Republic of Tajikistan']), 'actor_type' => 'STATE', 'primary_region' => 'Central Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇹🇯', 'color_hex' => '#006600', 'icon' => 'flag'],
            ['name' => 'Kyrgyzstan', 'short_name' => 'Kyrgyzstan', 'alias_names' => json_encode(['Kyrgyz Republic']), 'actor_type' => 'STATE', 'primary_region' => 'Central Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇰🇬', 'color_hex' => '#E8112D', 'icon' => 'flag'],
            ['name' => 'Afghanistan', 'short_name' => 'Afghanistan', 'alias_names' => json_encode(['Islamic Emirate of Afghanistan']), 'actor_type' => 'STATE', 'primary_region' => 'South Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'high', 'autocomplete_priority' => 70, 'flag_emoji' => '🇦🇫', 'color_hex' => '#000000', 'icon' => 'flag'],
            ['name' => 'Bangladesh', 'short_name' => 'Bangladesh', 'alias_names' => json_encode(['People\'s Republic of Bangladesh']), 'actor_type' => 'STATE', 'primary_region' => 'South Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇧🇩', 'color_hex' => '#006A4E', 'icon' => 'flag'],
            ['name' => 'Sri Lanka', 'short_name' => 'Sri Lanka', 'alias_names' => json_encode(['Ceylon']), 'actor_type' => 'STATE', 'primary_region' => 'South Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇱🇰', 'color_hex' => '#8D153A', 'icon' => 'flag'],
            ['name' => 'Nepal', 'short_name' => 'Nepal', 'alias_names' => json_encode(['Federal Democratic Republic of Nepal']), 'actor_type' => 'STATE', 'primary_region' => 'South Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇳🇵', 'color_hex' => '#DC143C', 'icon' => 'flag'],
            ['name' => 'Indonesia', 'short_name' => 'Indonesia', 'alias_names' => json_encode(['Republic of Indonesia']), 'actor_type' => 'STATE', 'primary_region' => 'Southeast Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 40, 'flag_emoji' => '🇮🇩', 'color_hex' => '#FF0000', 'icon' => 'flag'],
            ['name' => 'Malaysia', 'short_name' => 'Malaysia', 'alias_names' => json_encode(['Malaysia']), 'actor_type' => 'STATE', 'primary_region' => 'Southeast Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇲🇾', 'color_hex' => '#010066', 'icon' => 'flag'],
            ['name' => 'Singapore', 'short_name' => 'Singapore', 'alias_names' => json_encode(['Republic of Singapore']), 'actor_type' => 'STATE', 'primary_region' => 'Southeast Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇸🇬', 'color_hex' => '#ED2939', 'icon' => 'flag'],
            ['name' => 'Thailand', 'short_name' => 'Thailand', 'alias_names' => json_encode(['Kingdom of Thailand']), 'actor_type' => 'STATE', 'primary_region' => 'Southeast Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'low', 'autocomplete_priority' => 40, 'flag_emoji' => '🇹🇭', 'color_hex' => '#A51931', 'icon' => 'flag'],
            ['name' => 'Vietnam', 'short_name' => 'Vietnam', 'alias_names' => json_encode(['Socialist Republic of Vietnam']), 'actor_type' => 'STATE', 'primary_region' => 'Southeast Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 35, 'flag_emoji' => '🇻🇳', 'color_hex' => '#DA251D', 'icon' => 'flag'],
            ['name' => 'Philippines', 'short_name' => 'Philippines', 'alias_names' => json_encode(['Republic of the Philippines']), 'actor_type' => 'STATE', 'primary_region' => 'Southeast Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'medium', 'autocomplete_priority' => 55, 'flag_emoji' => '🇵🇭', 'color_hex' => '#0038A8', 'icon' => 'flag'],
            ['name' => 'Cambodia', 'short_name' => 'Cambodia', 'alias_names' => json_encode(['Kingdom of Cambodia']), 'actor_type' => 'STATE', 'primary_region' => 'Southeast Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇰🇭', 'color_hex' => '#032EA1', 'icon' => 'flag'],
            ['name' => 'Laos', 'short_name' => 'Laos', 'alias_names' => json_encode(['Lao People\'s Democratic Republic']), 'actor_type' => 'STATE', 'primary_region' => 'Southeast Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇱🇦', 'color_hex' => '#CE1126', 'icon' => 'flag'],
            ['name' => 'Taiwan', 'short_name' => 'Taiwan', 'alias_names' => json_encode(['Republic of China', 'ROC']), 'actor_type' => 'STATE', 'primary_region' => 'East Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'medium', 'autocomplete_priority' => 55, 'flag_emoji' => '🇹🇼', 'color_hex' => '#FE0000', 'icon' => 'flag'],
            ['name' => 'Mongolia', 'short_name' => 'Mongolia', 'alias_names' => json_encode(['Mongolia']), 'actor_type' => 'STATE', 'primary_region' => 'East Asia', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 25, 'flag_emoji' => '🇲🇳', 'color_hex' => '#C4272F', 'icon' => 'flag'],
            ['name' => 'Morocco', 'short_name' => 'Morocco', 'alias_names' => json_encode(['Kingdom of Morocco']), 'actor_type' => 'STATE', 'primary_region' => 'North Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇲🇦', 'color_hex' => '#C1272D', 'icon' => 'flag'],
            ['name' => 'Algeria', 'short_name' => 'Algeria', 'alias_names' => json_encode(['People\'s Democratic Republic of Algeria']), 'actor_type' => 'STATE', 'primary_region' => 'North Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇩🇿', 'color_hex' => '#006633', 'icon' => 'flag'],
            ['name' => 'Tunisia', 'short_name' => 'Tunisia', 'alias_names' => json_encode(['Republic of Tunisia']), 'actor_type' => 'STATE', 'primary_region' => 'North Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'inactive', 'autocomplete_priority' => 30, 'flag_emoji' => '🇹🇳', 'color_hex' => '#E70013', 'icon' => 'flag'],
            ['name' => 'Libya', 'short_name' => 'Libya', 'alias_names' => json_encode(['State of Libya']), 'actor_type' => 'STATE', 'primary_region' => 'North Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => true, 'activity_level' => 'medium', 'autocomplete_priority' => 60, 'flag_emoji' => '🇱🇾', 'color_hex' => '#E70013', 'icon' => 'flag'],
            ['name' => 'Eritrea', 'short_name' => 'Eritrea', 'alias_names' => json_encode(['State of Eritrea']), 'actor_type' => 'STATE', 'primary_region' => 'East Africa', 'is_state_actor' => true, 'is_designated_terrorist' => false, 'designations' => json_encode([]), 'is_active_in_conflict' => false, 'activity_level' => 'medium', 'autocomplete_priority' => 50, 'flag_emoji' => '🇪🇷', 'color_hex' => '#4189DD', 'icon' => 'flag'],
        ];

        foreach ($actors as $actor) {
            DB::table('actors')->insert(array_merge($actor, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('Actors seeded successfully.');
    }
}
