<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Populates the actors table with countries, groups, organizations, and militias
     * involved in current active conflicts (2024-2025).
     */
    public function run(): void
    {
        $actors = [
            // ========================================
            // RUSSIA-UKRAINE WAR
            // ========================================
            [
                'name' => 'Russian Federation',
                'short_name' => 'Russia',
                'alias_names' => json_encode(['Russia', 'Russian Federation', 'RF']),
                'actor_type' => 'STATE',
                'country_id' => null, // Set after countries are seeded
                'primary_region' => 'Eastern Europe',
                'operational_areas' => json_encode(['Ukraine', 'Syria', 'Africa', 'Georgia']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 100,
                'color_hex' => '#0039A6',
                'icon' => 'flag',
            ],
            [
                'name' => 'Ukraine',
                'short_name' => 'Ukraine',
                'alias_names' => json_encode(['Ukraine', 'UA']),
                'actor_type' => 'STATE',
                'primary_region' => 'Eastern Europe',
                'operational_areas' => json_encode(['Ukraine']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 100,
                'color_hex' => '#0057B7',
                'icon' => 'flag',
            ],
            [
                'name' => 'Wagner Group',
                'short_name' => 'Wagner',
                'alias_names' => json_encode(['Wagner PMC', 'PMC Wagner', 'Wagner Mercenaries']),
                'actor_type' => 'PMC',
                'primary_region' => 'Global',
                'operational_areas' => json_encode(['Ukraine', 'Syria', 'Mali', 'CAR', 'Libya']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode(['us' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 85,
                'color_hex' => '#8B4513',
                'icon' => 'shield-alt',
                'founded_date' => '2014-01-01',
            ],
            [
                'name' => 'Donetsk People\'s Republic',
                'short_name' => 'DPR',
                'alias_names' => json_encode(['DNR', 'Donetsk PR']),
                'actor_type' => 'SEPARATIST',
                'primary_region' => 'Eastern Europe',
                'operational_areas' => json_encode(['Ukraine - Donetsk Oblast']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 75,
                'color_hex' => '#000000',
                'icon' => 'users',
                'founded_date' => '2014-04-07',
            ],
            [
                'name' => 'Luhansk People\'s Republic',
                'short_name' => 'LPR',
                'alias_names' => json_encode(['LNR', 'Luhansk PR']),
                'actor_type' => 'SEPARATIST',
                'primary_region' => 'Eastern Europe',
                'operational_areas' => json_encode(['Ukraine - Luhansk Oblast']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 75,
                'color_hex' => '#0056A7',
                'icon' => 'users',
                'founded_date' => '2014-04-27',
            ],

            // ========================================
            // ISRAEL-GAZA CONFLICT
            // ========================================
            [
                'name' => 'Israel',
                'short_name' => 'Israel',
                'alias_names' => json_encode(['State of Israel', 'Israel']),
                'actor_type' => 'STATE',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Israel', 'Gaza', 'West Bank', 'Lebanon', 'Syria']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 100,
                'color_hex' => '#0038B8',
                'icon' => 'flag',
            ],
            [
                'name' => 'Hamas',
                'short_name' => 'Hamas',
                'alias_names' => json_encode(['Harakat al-Muqawama al-Islamiya', 'Islamic Resistance Movement', 'Izz ad-Din al-Qassam Brigades']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Gaza Strip', 'West Bank']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 95,
                'color_hex' => '#00AA00',
                'icon' => 'users-cog',
                'founded_date' => '1987-12-14',
            ],
            [
                'name' => 'Palestinian Islamic Jihad',
                'short_name' => 'PIJ',
                'alias_names' => json_encode(['Islamic Jihad Movement in Palestine', 'Al-Quds Brigades']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Gaza Strip', 'West Bank']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDay(),
                'autocomplete_priority' => 85,
                'color_hex' => '#009900',
                'icon' => 'users-cog',
            ],
            [
                'name' => 'Hezbollah',
                'short_name' => 'Hezbollah',
                'alias_names' => json_encode(['Party of God', 'Hizbullah', 'Hizballah']),
                'actor_type' => 'MILITIA',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Lebanon', 'Syria', 'Yemen']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 90,
                'color_hex' => '#FFCC00',
                'icon' => 'fist-raised',
                'founded_date' => '1985-01-01',
            ],
            [
                'name' => 'Houthis',
                'short_name' => 'Houthis',
                'alias_names' => json_encode(['Ansar Allah', 'Ansarullah', 'Houthi Movement']),
                'actor_type' => 'INSURGENT',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Yemen', 'Red Sea', 'Saudi Arabia']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 88,
                'color_hex' => '#007A3D',
                'icon' => 'users',
                'founded_date' => '1992-01-01',
            ],

            // ========================================
            // SUDAN CIVIL WAR
            // ========================================
            [
                'name' => 'Sudanese Armed Forces',
                'short_name' => 'SAF',
                'alias_names' => json_encode(['Sudan Armed Forces', 'Sudanese Army']),
                'actor_type' => 'GOVERNMENT_FORCES',
                'primary_region' => 'Northeast Africa',
                'operational_areas' => json_encode(['Sudan']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 85,
                'color_hex' => '#007229',
                'icon' => 'fighter-jet',
            ],
            [
                'name' => 'Rapid Support Forces',
                'short_name' => 'RSF',
                'alias_names' => json_encode(['Janjaweed', 'Rapid Support']),
                'actor_type' => 'MILITIA',
                'primary_region' => 'Northeast Africa',
                'operational_areas' => json_encode(['Sudan', 'Darfur']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 85,
                'color_hex' => '#D21034',
                'icon' => 'users',
                'founded_date' => '2013-08-01',
            ],

            // ========================================
            // MYANMAR CIVIL WAR
            // ========================================
            [
                'name' => 'Tatmadaw',
                'short_name' => 'Tatmadaw',
                'alias_names' => json_encode(['Myanmar Armed Forces', 'Burma Army']),
                'actor_type' => 'GOVERNMENT_FORCES',
                'primary_region' => 'Southeast Asia',
                'operational_areas' => json_encode(['Myanmar']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 80,
                'color_hex' => '#FECB00',
                'icon' => 'fighter-jet',
            ],
            [
                'name' => 'People\'s Defense Force',
                'short_name' => 'PDF',
                'alias_names' => json_encode(['PDF Myanmar', 'People\'s Defense Forces']),
                'actor_type' => 'REBEL',
                'primary_region' => 'Southeast Asia',
                'operational_areas' => json_encode(['Myanmar']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 75,
                'color_hex' => '#EA2839',
                'icon' => 'users',
                'founded_date' => '2021-05-05',
            ],
            [
                'name' => 'Arakan Army',
                'short_name' => 'AA',
                'alias_names' => json_encode(['Arakan Army Myanmar']),
                'actor_type' => 'INSURGENT',
                'primary_region' => 'Southeast Asia',
                'operational_areas' => json_encode(['Myanmar - Rakhine State']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(1),
                'autocomplete_priority' => 70,
                'color_hex' => '#034694',
                'icon' => 'users',
                'founded_date' => '2009-04-10',
            ],
            [
                'name' => 'Kachin Independence Army',
                'short_name' => 'KIA',
                'alias_names' => json_encode(['Kachin Independence Organisation']),
                'actor_type' => 'INSURGENT',
                'primary_region' => 'Southeast Asia',
                'operational_areas' => json_encode(['Myanmar - Kachin State']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 70,
                'color_hex' => '#FF0000',
                'icon' => 'users',
            ],

            // ========================================
            // SYRIA
            // ========================================
            [
                'name' => 'Syrian Arab Army',
                'short_name' => 'SAA',
                'alias_names' => json_encode(['Syrian Army', 'Syrian Government Forces']),
                'actor_type' => 'GOVERNMENT_FORCES',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Syria']),
                'is_state_actor' => true,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(5),
                'autocomplete_priority' => 70,
                'color_hex' => '#CE1126',
                'icon' => 'fighter-jet',
            ],
            [
                'name' => 'Syrian Democratic Forces',
                'short_name' => 'SDF',
                'alias_names' => json_encode(['YPG', 'Kurdish Forces', 'SDF-YPG']),
                'actor_type' => 'MILITIA',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Syria - Northeast']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(3),
                'autocomplete_priority' => 70,
                'color_hex' => '#FFD700',
                'icon' => 'users',
                'founded_date' => '2015-10-10',
            ],
            [
                'name' => 'Hayat Tahrir al-Sham',
                'short_name' => 'HTS',
                'alias_names' => json_encode(['Al-Nusra Front', 'Jabhat al-Nusra', 'Tahrir al-Sham']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Syria - Idlib']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(4),
                'autocomplete_priority' => 75,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2017-01-28',
            ],

            // ========================================
            // SAHEL TERRORISM
            // ========================================
            [
                'name' => 'Jama\'at Nasr al-Islam wal Muslimin',
                'short_name' => 'JNIM',
                'alias_names' => json_encode(['GSIM', 'Al-Qaeda in the Sahel', 'Group for Support of Islam and Muslims']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Sahel',
                'operational_areas' => json_encode(['Mali', 'Burkina Faso', 'Niger']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(1),
                'autocomplete_priority' => 80,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2017-03-02',
            ],
            [
                'name' => 'Islamic State in the Greater Sahara',
                'short_name' => 'ISGS',
                'alias_names' => json_encode(['ISIS Sahara', 'Islamic State Sahel']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Sahel',
                'operational_areas' => json_encode(['Mali', 'Burkina Faso', 'Niger']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 80,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2015-05-01',
            ],
            [
                'name' => 'Boko Haram',
                'short_name' => 'Boko Haram',
                'alias_names' => json_encode(['Jama\'atu Ahlis Sunna Lidda\'awati wal-Jihad']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'West Africa',
                'operational_areas' => json_encode(['Nigeria', 'Chad', 'Cameroon', 'Niger']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(3),
                'autocomplete_priority' => 82,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2002-01-01',
            ],
            [
                'name' => 'Islamic State West Africa Province',
                'short_name' => 'ISWAP',
                'alias_names' => json_encode(['ISIS West Africa', 'Wilayat Gharb Ifriqiyyah']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'West Africa',
                'operational_areas' => json_encode(['Nigeria', 'Chad', 'Niger']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(1),
                'autocomplete_priority' => 82,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2016-03-12',
            ],
            [
                'name' => 'Al-Shabaab',
                'short_name' => 'Al-Shabaab',
                'alias_names' => json_encode(['Harakat al-Shabaab al-Mujahideen', 'Al-Shabab']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'East Africa',
                'operational_areas' => json_encode(['Somalia', 'Kenya']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 85,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2006-01-01',
            ],

            // ========================================
            // GLOBAL TERRORISM
            // ========================================
            [
                'name' => 'Islamic State',
                'short_name' => 'ISIS',
                'alias_names' => json_encode(['ISIL', 'Daesh', 'Islamic State of Iraq and Syria', 'IS']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Global',
                'operational_areas' => json_encode(['Iraq', 'Syria', 'Afghanistan', 'Africa', 'Southeast Asia']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 90,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2013-04-09',
            ],
            [
                'name' => 'Islamic State - Khorasan Province',
                'short_name' => 'ISIS-K',
                'alias_names' => json_encode(['IS-KP', 'ISKP', 'Islamic State Khorasan']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'South Asia',
                'operational_areas' => json_encode(['Afghanistan', 'Pakistan']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(1),
                'autocomplete_priority' => 85,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2015-01-10',
            ],
            [
                'name' => 'Al-Qaeda',
                'short_name' => 'AQ',
                'alias_names' => json_encode(['Al-Qaida', 'The Base', 'Qaeda']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Global',
                'operational_areas' => json_encode(['Afghanistan', 'Yemen', 'Syria', 'Sahel']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'low',
                'last_activity_date' => now()->subDays(15),
                'autocomplete_priority' => 75,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '1988-08-11',
            ],
            [
                'name' => 'Al-Qaeda in the Arabian Peninsula',
                'short_name' => 'AQAP',
                'alias_names' => json_encode(['Al-Qaeda Yemen', 'AQAP Yemen']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Middle East',
                'operational_areas' => json_encode(['Yemen', 'Saudi Arabia']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(7),
                'autocomplete_priority' => 78,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2009-01-22',
            ],
            [
                'name' => 'Taliban',
                'short_name' => 'Taliban',
                'alias_names' => json_encode(['Islamic Emirate of Afghanistan', 'Afghan Taliban']),
                'actor_type' => 'INSURGENT',
                'primary_region' => 'South Asia',
                'operational_areas' => json_encode(['Afghanistan', 'Pakistan']),
                'is_state_actor' => true,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(3),
                'autocomplete_priority' => 85,
                'color_hex' => '#000000',
                'icon' => 'users',
                'founded_date' => '1994-09-01',
            ],
            [
                'name' => 'Tehrik-i-Taliban Pakistan',
                'short_name' => 'TTP',
                'alias_names' => json_encode(['Pakistani Taliban', 'TTP Pakistan']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'South Asia',
                'operational_areas' => json_encode(['Pakistan', 'Afghanistan']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 80,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2007-12-14',
            ],

            // ========================================
            // MEXICAN CARTELS
            // ========================================
            [
                'name' => 'Sinaloa Cartel',
                'short_name' => 'Sinaloa',
                'alias_names' => json_encode(['Sinaloa Drug Cartel', 'Pacific Cartel']),
                'actor_type' => 'CARTEL',
                'primary_region' => 'North America',
                'operational_areas' => json_encode(['Mexico', 'United States']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 85,
                'color_hex' => '#8B0000',
                'icon' => 'skull-crossbones',
            ],
            [
                'name' => 'Jalisco New Generation Cartel',
                'short_name' => 'CJNG',
                'alias_names' => json_encode(['Cartel Jalisco Nueva Generacion', 'CJNG Cartel']),
                'actor_type' => 'CARTEL',
                'primary_region' => 'North America',
                'operational_areas' => json_encode(['Mexico', 'United States']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now(),
                'autocomplete_priority' => 88,
                'color_hex' => '#DC143C',
                'icon' => 'skull-crossbones',
                'founded_date' => '2010-01-01',
            ],
            [
                'name' => 'Los Zetas',
                'short_name' => 'Zetas',
                'alias_names' => json_encode(['Zetas Cartel', 'Los Zetas Cartel']),
                'actor_type' => 'CARTEL',
                'primary_region' => 'North America',
                'operational_areas' => json_encode(['Mexico', 'Guatemala']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(5),
                'autocomplete_priority' => 75,
                'color_hex' => '#800000',
                'icon' => 'skull-crossbones',
                'founded_date' => '1999-01-01',
            ],
            [
                'name' => 'Gulf Cartel',
                'short_name' => 'CDG',
                'alias_names' => json_encode(['Cartel del Golfo', 'Gulf Cartel Mexico']),
                'actor_type' => 'CARTEL',
                'primary_region' => 'North America',
                'operational_areas' => json_encode(['Mexico']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(4),
                'autocomplete_priority' => 75,
                'color_hex' => '#B22222',
                'icon' => 'skull-crossbones',
            ],

            // ========================================
            // COLOMBIA & LATIN AMERICA
            // ========================================
            [
                'name' => 'National Liberation Army',
                'short_name' => 'ELN',
                'alias_names' => json_encode(['Ejercito de Liberacion Nacional', 'ELN Colombia']),
                'actor_type' => 'INSURGENT',
                'primary_region' => 'South America',
                'operational_areas' => json_encode(['Colombia', 'Venezuela']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'eu' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'medium',
                'last_activity_date' => now()->subDays(6),
                'autocomplete_priority' => 70,
                'color_hex' => '#FF0000',
                'icon' => 'users',
                'founded_date' => '1964-07-04',
            ],

            // ========================================
            // DEMOCRATIC REPUBLIC OF CONGO
            // ========================================
            [
                'name' => 'M23',
                'short_name' => 'M23',
                'alias_names' => json_encode(['March 23 Movement', 'Mouvement du 23-Mars']),
                'actor_type' => 'REBEL',
                'primary_region' => 'Central Africa',
                'operational_areas' => json_encode(['Democratic Republic of Congo']),
                'is_state_actor' => false,
                'is_designated_terrorist' => false,
                'designations' => json_encode([]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDay(),
                'autocomplete_priority' => 78,
                'color_hex' => '#007FFF',
                'icon' => 'users',
                'founded_date' => '2012-04-04',
            ],
            [
                'name' => 'Allied Democratic Forces',
                'short_name' => 'ADF',
                'alias_names' => json_encode(['ADF-NALU', 'Allied Democratic Forces Uganda']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'Central Africa',
                'operational_areas' => json_encode(['Democratic Republic of Congo', 'Uganda']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'high',
                'last_activity_date' => now()->subDays(2),
                'autocomplete_priority' => 75,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '1995-01-01',
            ],

            // ========================================
            // KASHMIR
            // ========================================
            [
                'name' => 'Lashkar-e-Taiba',
                'short_name' => 'LeT',
                'alias_names' => json_encode(['Army of the Good', 'Lashkar-e-Tayyiba']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'South Asia',
                'operational_areas' => json_encode(['Pakistan', 'India - Kashmir']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'low',
                'last_activity_date' => now()->subDays(45),
                'autocomplete_priority' => 65,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '1990-01-01',
            ],
            [
                'name' => 'Jaish-e-Mohammed',
                'short_name' => 'JeM',
                'alias_names' => json_encode(['Army of Mohammed', 'Jaish-e-Mohammad']),
                'actor_type' => 'TERRORIST',
                'primary_region' => 'South Asia',
                'operational_areas' => json_encode(['Pakistan', 'India - Kashmir']),
                'is_state_actor' => false,
                'is_designated_terrorist' => true,
                'designations' => json_encode(['us' => true, 'un' => true, 'eu' => true, 'uk' => true]),
                'is_active_in_conflict' => true,
                'activity_level' => 'low',
                'last_activity_date' => now()->subDays(50),
                'autocomplete_priority' => 65,
                'color_hex' => '#000000',
                'icon' => 'users-cog',
                'founded_date' => '2000-01-31',
            ],

            // Add more actors as needed...
        ];

        foreach ($actors as $actor) {
            DB::table('actors')->insert(array_merge($actor, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('Actors seeded successfully.');
    }
}
