<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ActorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Seeds non-state actors (militias, terrorist groups, PMCs, etc.)
     */
    public function run(): void
    {
        $this->seedNonStateActors();
        $this->command->info('Non-state actors seeded successfully.');
    }

    private function seedNonStateActors(): void
    {
        $actors = [
            // Russia-aligned groups
            [
                'name' => 'Wagner Group',
                'slug' => 'wagner-group',
                'type' => 'pmc',
                'description' => 'Russian private military company founded by Dmitry Utkin and funded by Yevgeny Prigozhin. Operated in Syria, Libya, Mali, CAR, and Ukraine. Known for brutal tactics. Prigozhin killed August 2023 after failed mutiny. Assets largely absorbed by Russian MoD.',
                'aliases' => json_encode(['PMC Wagner', 'Vagner', 'Africa Corps']),
                'parent_country' => 'RU',
                'ideology' => 'Pro-Russian',
                'active' => true,
                'founded_year' => 2014,
                'strength_estimate' => '25000',
                'areas_of_operation' => json_encode(['Ukraine', 'Syria', 'Libya', 'Mali', 'CAR', 'Sudan']),
                'equipment' => json_encode(['T-72', 'BMP', 'Artillery', 'Air defense']),
            ],
            [
                'name' => 'Donetsk People\'s Republic Forces',
                'slug' => 'dpr-forces',
                'type' => 'militia',
                'description' => 'Armed forces of the self-proclaimed DPR in eastern Ukraine. Integrated into Russian military structure after 2022 invasion. Originally formed 2014 during Donbas war.',
                'aliases' => json_encode(['DPR Army', 'DNR Forces', '1st Army Corps']),
                'parent_country' => 'RU',
                'ideology' => 'Pro-Russian separatist',
                'active' => true,
                'founded_year' => 2014,
                'strength_estimate' => '20000',
                'areas_of_operation' => json_encode(['Donetsk Oblast']),
                'equipment' => json_encode(['T-72', 'BMP-2', 'BTR-80', '2S1 Gvozdika']),
            ],
            [
                'name' => 'Luhansk People\'s Republic Forces',
                'slug' => 'lpr-forces',
                'type' => 'militia',
                'description' => 'Armed forces of the self-proclaimed LPR in eastern Ukraine. Integrated into Russian military structure. Part of 2nd Army Corps under Russian Southern Military District.',
                'aliases' => json_encode(['LPR Army', 'LNR Forces', '2nd Army Corps']),
                'parent_country' => 'RU',
                'ideology' => 'Pro-Russian separatist',
                'active' => true,
                'founded_year' => 2014,
                'strength_estimate' => '15000',
                'areas_of_operation' => json_encode(['Luhansk Oblast']),
                'equipment' => json_encode(['T-64', 'BMP-1', 'MT-LB']),
            ],

            // Palestinian groups
            [
                'name' => 'Hamas',
                'slug' => 'hamas',
                'type' => 'militant',
                'description' => 'Palestinian Sunni Islamist organization governing Gaza Strip since 2007. Military wing Al-Qassam Brigades. Responsible for October 7, 2023 attack on Israel. Designated terrorist organization by US, EU, and others.',
                'aliases' => json_encode(['Islamic Resistance Movement', 'Al-Qassam Brigades', 'Izz ad-Din al-Qassam Brigades']),
                'parent_country' => null,
                'ideology' => 'Sunni Islamist',
                'active' => true,
                'founded_year' => 1987,
                'strength_estimate' => '40000',
                'areas_of_operation' => json_encode(['Gaza Strip', 'West Bank']),
                'equipment' => json_encode(['Rockets', 'ATGMs', 'Drones', 'Small arms', 'Tunnels']),
            ],
            [
                'name' => 'Palestinian Islamic Jihad',
                'slug' => 'pij',
                'type' => 'militant',
                'description' => 'Palestinian Islamist militant organization. Second largest armed group in Gaza after Hamas. Iranian-backed. Al-Quds Brigades is military wing.',
                'aliases' => json_encode(['PIJ', 'Islamic Jihad', 'Al-Quds Brigades']),
                'parent_country' => null,
                'ideology' => 'Sunni Islamist',
                'active' => true,
                'founded_year' => 1981,
                'strength_estimate' => '12000',
                'areas_of_operation' => json_encode(['Gaza Strip', 'West Bank']),
                'equipment' => json_encode(['Rockets', 'ATGMs', 'Small arms']),
            ],

            // Lebanese/Iranian-backed groups
            [
                'name' => 'Hezbollah',
                'slug' => 'hezbollah',
                'type' => 'militant',
                'description' => 'Lebanese Shia Islamist political party and militant group. Iranian-backed with significant military capability. Fought 2006 war with Israel. Currently engaged in cross-border attacks supporting Hamas.',
                'aliases' => json_encode(['Party of God', 'Islamic Resistance in Lebanon']),
                'parent_country' => null,
                'ideology' => 'Shia Islamist',
                'active' => true,
                'founded_year' => 1982,
                'strength_estimate' => '100000',
                'areas_of_operation' => json_encode(['Lebanon', 'Syria']),
                'equipment' => json_encode(['Rockets', 'ATGMs', 'Drones', 'SAMs', 'Cruise missiles']),
            ],
            [
                'name' => 'Houthis',
                'slug' => 'houthis',
                'type' => 'militant',
                'description' => 'Yemeni Shia Islamist movement officially known as Ansar Allah. Controls northern Yemen including Sanaa. Iranian-backed. Attacking Red Sea shipping in support of Gaza.',
                'aliases' => json_encode(['Ansar Allah', 'Ansarullah']),
                'parent_country' => null,
                'ideology' => 'Zaydi Shia',
                'active' => true,
                'founded_year' => 1992,
                'strength_estimate' => '200000',
                'areas_of_operation' => json_encode(['Yemen', 'Red Sea', 'Saudi Arabia']),
                'equipment' => json_encode(['Ballistic missiles', 'Cruise missiles', 'Drones', 'Anti-ship missiles']),
            ],
            [
                'name' => 'Iraqi Popular Mobilization Forces',
                'slug' => 'pmf-iraq',
                'type' => 'militia',
                'description' => 'Iraqi state-sponsored umbrella organization of predominantly Shia militias. Formed 2014 to fight ISIS. Many components are Iranian-backed. Significant political influence in Iraq.',
                'aliases' => json_encode(['PMF', 'PMU', 'Hashd al-Shaabi', 'Popular Mobilization Units']),
                'parent_country' => 'IQ',
                'ideology' => 'Shia',
                'active' => true,
                'founded_year' => 2014,
                'strength_estimate' => '150000',
                'areas_of_operation' => json_encode(['Iraq', 'Syria']),
                'equipment' => json_encode(['T-72', 'M1 Abrams', 'Humvees', 'Artillery', 'Drones']),
            ],

            // Syrian groups
            [
                'name' => 'Syrian Democratic Forces',
                'slug' => 'sdf',
                'type' => 'militia',
                'description' => 'Multi-ethnic alliance in northern Syria dominated by Kurdish YPG. US-backed force that defeated ISIS territorial caliphate. Controls northeast Syria including oil fields.',
                'aliases' => json_encode(['SDF', 'QSD', "People's Defense Units", 'YPG']),
                'parent_country' => null,
                'ideology' => 'Democratic confederalism',
                'active' => true,
                'founded_year' => 2015,
                'strength_estimate' => '100000',
                'areas_of_operation' => json_encode(['Northeast Syria', 'Rojava']),
                'equipment' => json_encode(['Technicals', 'MRAPs', 'ATGMs', 'Small arms']),
            ],
            [
                'name' => 'Hayat Tahrir al-Sham',
                'slug' => 'hts',
                'type' => 'militant',
                'description' => 'Syrian Sunni Islamist militant group controlling Idlib province. Formerly Jabhat al-Nusra (Al-Qaeda affiliate). Led by Abu Mohammad al-Julani. Designated terrorist organization.',
                'aliases' => json_encode(['HTS', 'Jabhat al-Nusra', 'Al-Nusra Front', 'Jabhat Fateh al-Sham']),
                'parent_country' => null,
                'ideology' => 'Salafi-jihadist',
                'active' => true,
                'founded_year' => 2017,
                'strength_estimate' => '30000',
                'areas_of_operation' => json_encode(['Idlib', 'Northwest Syria']),
                'equipment' => json_encode(['Tanks', 'Artillery', 'ATGMs', 'Drones']),
            ],
            [
                'name' => 'Syrian National Army',
                'slug' => 'sna',
                'type' => 'militia',
                'description' => 'Turkish-backed Syrian opposition coalition operating in northern Syria. Formed from various FSA factions. Participates in Turkish military operations against SDF.',
                'aliases' => json_encode(['TFSA', 'Turkish-backed FSA', 'National Army']),
                'parent_country' => null,
                'ideology' => 'Syrian opposition',
                'active' => true,
                'founded_year' => 2017,
                'strength_estimate' => '80000',
                'areas_of_operation' => json_encode(['Northern Syria', 'Turkish border zone']),
                'equipment' => json_encode(['Technicals', 'APCs', 'Tanks', 'Artillery']),
            ],

            // African groups
            [
                'name' => 'JNIM',
                'slug' => 'jnim',
                'type' => 'terrorist',
                'description' => 'Jamaat Nusrat al-Islam wal-Muslimin - Al-Qaeda affiliate in the Sahel. Merger of multiple jihadist groups. Primary insurgent threat in Mali, Burkina Faso, and Niger.',
                'aliases' => json_encode(['Group for Support of Islam and Muslims', 'GSIM']),
                'parent_country' => null,
                'ideology' => 'Salafi-jihadist',
                'active' => true,
                'founded_year' => 2017,
                'strength_estimate' => '5000',
                'areas_of_operation' => json_encode(['Mali', 'Burkina Faso', 'Niger']),
                'equipment' => json_encode(['Technicals', 'Motorcycles', 'IEDs', 'Small arms']),
            ],
            [
                'name' => 'Islamic State Greater Sahara',
                'slug' => 'isgs',
                'type' => 'terrorist',
                'description' => 'ISIS affiliate in the Sahel region. Operates in Mali-Niger-Burkina Faso border area. Rival to JNIM with periodic clashes between the groups.',
                'aliases' => json_encode(['ISGS', 'ISIS Sahel', 'Islamic State in the Greater Sahara']),
                'parent_country' => null,
                'ideology' => 'Salafi-jihadist',
                'active' => true,
                'founded_year' => 2015,
                'strength_estimate' => '2000',
                'areas_of_operation' => json_encode(['Mali', 'Niger', 'Burkina Faso']),
                'equipment' => json_encode(['Motorcycles', 'IEDs', 'Small arms']),
            ],
            [
                'name' => 'Al-Shabaab',
                'slug' => 'al-shabaab',
                'type' => 'terrorist',
                'description' => 'Somali Al-Qaeda affiliate controlling parts of southern Somalia. Carries out attacks in Somalia and Kenya. One of Al-Qaeda\'s most effective affiliates.',
                'aliases' => json_encode(['Harakat al-Shabaab al-Mujahideen', 'HSM', 'The Youth']),
                'parent_country' => null,
                'ideology' => 'Salafi-jihadist',
                'active' => true,
                'founded_year' => 2006,
                'strength_estimate' => '10000',
                'areas_of_operation' => json_encode(['Somalia', 'Kenya']),
                'equipment' => json_encode(['Technicals', 'IEDs', 'Mortars', 'Small arms']),
            ],
            [
                'name' => 'Rapid Support Forces',
                'slug' => 'rsf-sudan',
                'type' => 'militia',
                'description' => 'Sudanese paramilitary force led by Mohamed Hamdan Dagalo (Hemedti). Evolved from Janjaweed militia. Currently fighting SAF for control of Sudan.',
                'aliases' => json_encode(['RSF', 'Janjaweed']),
                'parent_country' => 'SD',
                'ideology' => 'Paramilitary',
                'active' => true,
                'founded_year' => 2013,
                'strength_estimate' => '100000',
                'areas_of_operation' => json_encode(['Sudan', 'Darfur', 'Khartoum']),
                'equipment' => json_encode(['Technicals', 'APCs', 'Artillery', 'Drones']),
            ],

            // Myanmar groups
            [
                'name' => 'People\'s Defence Force',
                'slug' => 'pdf-myanmar',
                'type' => 'militia',
                'description' => 'Armed wing of Myanmar\'s National Unity Government opposing military junta. Formed after 2021 coup. Operating nationwide with varying capabilities.',
                'aliases' => json_encode(['PDF', 'NUG Armed Forces']),
                'parent_country' => null,
                'ideology' => 'Pro-democracy',
                'active' => true,
                'founded_year' => 2021,
                'strength_estimate' => '65000',
                'areas_of_operation' => json_encode(['Myanmar']),
                'equipment' => json_encode(['Small arms', 'IEDs', '3D printed weapons']),
            ],
            [
                'name' => 'Arakan Army',
                'slug' => 'arakan-army',
                'type' => 'militia',
                'description' => 'Ethnic Rakhine armed group seeking autonomy in Rakhine State. Part of Three Brotherhood Alliance. Major territorial gains against Myanmar military in 2023-2024.',
                'aliases' => json_encode(['AA', 'ULA/AA']),
                'parent_country' => null,
                'ideology' => 'Rakhine nationalism',
                'active' => true,
                'founded_year' => 2009,
                'strength_estimate' => '30000',
                'areas_of_operation' => json_encode(['Rakhine State', 'Myanmar']),
                'equipment' => json_encode(['Captured military equipment', 'Artillery', 'Drones']),
            ],
            [
                'name' => 'Kachin Independence Army',
                'slug' => 'kia',
                'type' => 'militia',
                'description' => 'Ethnic Kachin armed organization in northern Myanmar. One of largest and best-equipped ethnic armed groups. Long history of conflict with Myanmar military.',
                'aliases' => json_encode(['KIA', 'KIO']),
                'parent_country' => null,
                'ideology' => 'Kachin nationalism',
                'active' => true,
                'founded_year' => 1961,
                'strength_estimate' => '15000',
                'areas_of_operation' => json_encode(['Kachin State', 'Northern Shan State']),
                'equipment' => json_encode(['Artillery', 'Mortars', 'Anti-aircraft guns', 'Small arms']),
            ],

            // Ethiopian groups
            [
                'name' => 'Tigray Defense Forces',
                'slug' => 'tdf',
                'type' => 'militia',
                'description' => 'Armed forces of the Tigray regional government. Fought 2020-2022 Tigray War against Ethiopian federal forces and Eritrea. Ceased hostilities under November 2022 agreement.',
                'aliases' => json_encode(['TDF', 'TPLF Forces']),
                'parent_country' => null,
                'ideology' => 'Tigray nationalism',
                'active' => true,
                'founded_year' => 2020,
                'strength_estimate' => '250000',
                'areas_of_operation' => json_encode(['Tigray', 'Ethiopia']),
                'equipment' => json_encode(['Captured Ethiopian equipment', 'Artillery', 'Tanks']),
            ],
            [
                'name' => 'Fano Militia',
                'slug' => 'fano',
                'type' => 'militia',
                'description' => 'Amhara irregular militia forces. Originally allied with Ethiopian government against Tigray but now in conflict with federal government over regional militias.',
                'aliases' => json_encode(['Amhara Fano', 'Fano']),
                'parent_country' => null,
                'ideology' => 'Amhara nationalism',
                'active' => true,
                'founded_year' => 2018,
                'strength_estimate' => '100000',
                'areas_of_operation' => json_encode(['Amhara Region', 'Ethiopia']),
                'equipment' => json_encode(['Small arms', 'Technicals']),
            ],

            // Ukrainian volunteer units
            [
                'name' => 'Azov Brigade',
                'slug' => 'azov-brigade',
                'type' => 'militia',
                'description' => 'Ukrainian National Guard unit originally formed as volunteer battalion in 2014. Defended Mariupol in 2022. Controversial far-right origins but reformed as professional military unit.',
                'aliases' => json_encode(['Azov Regiment', 'Azov Battalion', '3rd Assault Brigade']),
                'parent_country' => 'UA',
                'ideology' => 'Ukrainian nationalist',
                'active' => true,
                'founded_year' => 2014,
                'strength_estimate' => '2500',
                'areas_of_operation' => json_encode(['Ukraine']),
                'equipment' => json_encode(['Standard Ukrainian military equipment']),
            ],
            [
                'name' => 'International Legion of Ukraine',
                'slug' => 'international-legion',
                'type' => 'militia',
                'description' => 'Foreign volunteer military unit fighting for Ukraine. Composed of volunteers from 50+ countries. Formally part of Ukrainian Armed Forces.',
                'aliases' => json_encode(['Foreign Legion of Ukraine']),
                'parent_country' => 'UA',
                'ideology' => 'Pro-Ukrainian',
                'active' => true,
                'founded_year' => 2022,
                'strength_estimate' => '3000',
                'areas_of_operation' => json_encode(['Ukraine']),
                'equipment' => json_encode(['Standard Ukrainian military equipment']),
            ],

            // Other significant groups
            [
                'name' => 'ISIS Remnants',
                'slug' => 'isis-remnants',
                'type' => 'terrorist',
                'description' => 'Remaining Islamic State fighters in Iraq and Syria conducting insurgent operations. Lost territorial caliphate in 2019 but maintains clandestine presence.',
                'aliases' => json_encode(['Islamic State', 'ISIL', 'Daesh', 'ISIS']),
                'parent_country' => null,
                'ideology' => 'Salafi-jihadist',
                'active' => true,
                'founded_year' => 2006,
                'strength_estimate' => '10000',
                'areas_of_operation' => json_encode(['Iraq', 'Syria']),
                'equipment' => json_encode(['IEDs', 'Small arms', 'SVBIEDs']),
            ],
            [
                'name' => 'ISIS-Khorasan',
                'slug' => 'isis-k',
                'type' => 'terrorist',
                'description' => 'ISIS affiliate in Afghanistan and Pakistan. Opposes both Taliban and Western targets. Responsible for Kabul airport bombing and Moscow concert hall attack.',
                'aliases' => json_encode(['ISIS-K', 'ISKP', 'Islamic State Khorasan Province']),
                'parent_country' => null,
                'ideology' => 'Salafi-jihadist',
                'active' => true,
                'founded_year' => 2015,
                'strength_estimate' => '4000',
                'areas_of_operation' => json_encode(['Afghanistan', 'Pakistan', 'Central Asia']),
                'equipment' => json_encode(['IEDs', 'Small arms', 'Suicide bombers']),
            ],
            [
                'name' => 'Al-Qaeda',
                'slug' => 'al-qaeda',
                'type' => 'terrorist',
                'description' => 'Global Salafi-jihadist organization founded by Osama bin Laden. Weakened leadership but maintains affiliates worldwide. Currently led by unknown successor after Zawahiri death.',
                'aliases' => json_encode(['AQ', 'The Base', 'Al-Qaida']),
                'parent_country' => null,
                'ideology' => 'Salafi-jihadist',
                'active' => true,
                'founded_year' => 1988,
                'strength_estimate' => '500',
                'areas_of_operation' => json_encode(['Global', 'Afghanistan', 'Yemen', 'Sahel']),
                'equipment' => json_encode(['Varies by affiliate']),
            ],
            [
                'name' => 'Taliban',
                'slug' => 'taliban',
                'type' => 'militant',
                'description' => 'Islamic fundamentalist movement now governing Afghanistan. Seized power August 2021 after US withdrawal. Imposes strict Islamic law and restrictions on women.',
                'aliases' => json_encode(['Islamic Emirate of Afghanistan', 'IEA']),
                'parent_country' => 'AF',
                'ideology' => 'Deobandi Islamist',
                'active' => true,
                'founded_year' => 1994,
                'strength_estimate' => '100000',
                'areas_of_operation' => json_encode(['Afghanistan']),
                'equipment' => json_encode(['Captured US/NATO equipment', 'Soviet-era equipment']),
            ],
        ];

        foreach ($actors as $actor) {
            DB::table('actors')->updateOrInsert(
                ['slug' => $actor['slug']],
                array_merge($actor, [
                    'uuid' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }

        $this->command->info('Non-state actors seeded: ' . count($actors) . ' actors');
    }
}
