<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AdditionalEquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Adds more ships, drones, artillery, and specialized equipment.
     */
    public function run(): void
    {
        $this->seedNavalVessels();
        $this->seedDrones();
        $this->seedArtillery();
        $this->seedAirDefense();
        $this->seedSupportVehicles();
        $this->command->info('Additional equipment seeded successfully (50+ items).');
    }

    private function seedNavalVessels(): void
    {
        $categories = DB::table('equipment_categories')->pluck('id', 'slug');
        $countries = DB::table('countries')->pluck('id', 'iso_code');

        $vessels = [
            // Corvettes
            [
                'designation' => 'Karakurt-class',
                'nato_designation' => 'Karakurt',
                'common_name' => 'Project 22800',
                'country_code' => 'RU',
                'category_slug' => 'patrol-boats',
                'introduced_year' => 2018,
                'estimated_produced' => 18,
                'description' => 'Russian guided-missile corvette by Pella Shipyard. Small but heavily armed with 8 Kalibr cruise missiles. Displacement of 800 tonnes. Designed for littoral operations in Black and Baltic Seas. First use of Pantsir-M naval air defense. Multiple units used for Kalibr strikes on Ukraine.',
                'specifications' => json_encode([
                    'manufacturer' => 'Pella Shipyard',
                    'origin_country' => 'Russia',
                    'displacement_tonnes' => 800,
                    'length_m' => 67,
                    'speed_knots' => 30,
                    'missiles' => '8x Kalibr',
                    'air_defense' => 'Pantsir-M',
                    'crew' => 39,
                ]),
            ],
            [
                'designation' => 'Buyan-M class',
                'nato_designation' => 'Buyan-M',
                'common_name' => 'Project 21631',
                'country_code' => 'RU',
                'category_slug' => 'patrol-boats',
                'introduced_year' => 2014,
                'estimated_produced' => 12,
                'description' => 'Russian river-sea corvette by Zelenodolsk Shipyard. Shallow draft allows Caspian Sea to Black Sea transit via inland waterways. Armed with 8 Kalibr missiles. First combat use from Caspian Sea hitting Syria targets 1500km away in 2015. Distinctive box launcher on stern.',
                'specifications' => json_encode([
                    'manufacturer' => 'Zelenodolsk Shipyard',
                    'origin_country' => 'Russia',
                    'displacement_tonnes' => 950,
                    'length_m' => 75,
                    'draft_m' => 2.6,
                    'speed_knots' => 25,
                    'missiles' => '8x Kalibr',
                    'range_nm' => 2500,
                ]),
            ],
            [
                'designation' => 'Visby-class',
                'nato_designation' => null,
                'common_name' => 'Visby',
                'country_code' => 'SE',
                'category_slug' => 'patrol-boats',
                'introduced_year' => 2009,
                'estimated_produced' => 5,
                'description' => 'Swedish stealth corvette by Kockums. Revolutionary carbon fiber composite hull with extreme low radar signature. Anti-submarine warfare focus with hull-mounted and towed sonar. 57mm Bofors gun, RBS-15 missiles, torpedoes. Among most advanced corvettes globally. Basis for Polish and UAE designs.',
                'specifications' => json_encode([
                    'manufacturer' => 'Kockums (Saab)',
                    'origin_country' => 'Sweden',
                    'displacement_tonnes' => 650,
                    'length_m' => 73,
                    'speed_knots' => 35,
                    'stealth' => true,
                    'hull_material' => 'Carbon fiber composite',
                    'crew' => 43,
                ]),
            ],
            [
                'designation' => 'Braunschweig-class',
                'nato_designation' => 'K130',
                'common_name' => 'Braunschweig',
                'country_code' => 'DE',
                'category_slug' => 'patrol-boats',
                'introduced_year' => 2008,
                'estimated_produced' => 5,
                'description' => 'German guided-missile corvette by ARGE K130 consortium. Optimized for littoral warfare with low radar signature. RBS-15 Mk3 anti-ship missiles, RAM air defense, 76mm gun. Integrated sensor mast. 5 more planned to bring fleet to 10 units.',
                'specifications' => json_encode([
                    'manufacturer' => 'ThyssenKrupp/Lürssen',
                    'origin_country' => 'Germany',
                    'displacement_tonnes' => 1840,
                    'length_m' => 89,
                    'speed_knots' => 26,
                    'missiles' => '4x RBS-15',
                    'air_defense' => '2x RAM',
                    'crew' => 65,
                ]),
            ],
            [
                'designation' => 'Sa\'ar 6-class',
                'nato_designation' => null,
                'common_name' => 'Magen',
                'country_code' => 'IL',
                'category_slug' => 'patrol-boats',
                'introduced_year' => 2020,
                'estimated_produced' => 4,
                'description' => 'Israeli corvette by ThyssenKrupp Marine Systems. Based on German MEKO design. Naval Iron Dome (C-Dome) for missile defense. Gabriel V and Harpoon anti-ship missiles. EL/M-2248 MF-STAR AESA radar. Most advanced Israeli surface combatant. Protecting gas platforms.',
                'specifications' => json_encode([
                    'manufacturer' => 'ThyssenKrupp Marine Systems',
                    'origin_country' => 'Israel/Germany',
                    'displacement_tonnes' => 1900,
                    'length_m' => 90,
                    'speed_knots' => 26,
                    'air_defense' => 'C-Dome (Naval Iron Dome)',
                    'radar' => 'EL/M-2248 MF-STAR',
                    'vls_cells' => 32,
                ]),
            ],

            // Landing Ships
            [
                'designation' => 'Ropucha-class',
                'nato_designation' => 'Alligator',
                'common_name' => 'Ropucha',
                'country_code' => 'RU',
                'category_slug' => 'patrol-boats',
                'introduced_year' => 1975,
                'estimated_produced' => 28,
                'description' => 'Soviet/Russian landing ship tank (LST) by Yantar Shipyard in Poland. Can carry 10 tanks or 24 APCs plus 340 troops. Bow and stern doors for roll-on/roll-off. Multiple units lost or damaged in Ukraine war including Moskva escort ships. Workhorse of Russian amphibious fleet.',
                'specifications' => json_encode([
                    'manufacturer' => 'Yantar Shipyard (Poland)',
                    'origin_country' => 'Russia/Poland',
                    'displacement_tonnes' => 4080,
                    'length_m' => 113,
                    'cargo' => '10 tanks or 24 APCs',
                    'troops' => 340,
                    'speed_knots' => 18,
                    'roro' => true,
                ]),
            ],
            [
                'designation' => 'San Antonio-class',
                'nato_designation' => null,
                'common_name' => 'San Antonio',
                'country_code' => 'US',
                'category_slug' => 'patrol-boats',
                'introduced_year' => 2006,
                'estimated_produced' => 13,
                'description' => 'American amphibious transport dock (LPD) by Huntington Ingalls Industries. Carries 800 Marines with vehicles and landing craft. Well deck for 2 LCAC hovercraft or 1 LCU. Flight deck for MV-22 Osprey and helicopters. 15 planned. Primary means of projecting Marine Corps power.',
                'specifications' => json_encode([
                    'manufacturer' => 'Huntington Ingalls Industries',
                    'origin_country' => 'United States',
                    'displacement_tonnes' => 25000,
                    'length_m' => 208,
                    'troops' => 800,
                    'well_deck' => '2 LCAC or 1 LCU',
                    'flight_deck' => 'MV-22 and helicopters',
                    'crew' => 360,
                ]),
            ],
            [
                'designation' => 'Type 075',
                'nato_designation' => 'Yushen-class',
                'common_name' => 'Type 075 LHD',
                'country_code' => 'CN',
                'category_slug' => 'carriers',
                'introduced_year' => 2021,
                'estimated_produced' => 3,
                'description' => 'Chinese amphibious assault ship (LHD) by Hudong-Zhonghua Shipyard. Largest Chinese amphibious vessel at 40,000 tonnes. Full-length flight deck for Z-8, Z-20 helicopters. Well deck for hovercraft and landing craft. 3 commissioned with more building. Intended for Taiwan contingency.',
                'specifications' => json_encode([
                    'manufacturer' => 'Hudong-Zhonghua Shipyard',
                    'origin_country' => 'China',
                    'displacement_tonnes' => 40000,
                    'length_m' => 237,
                    'aircraft' => 30,
                    'troops' => 1200,
                    'well_deck' => true,
                    'speed_knots' => 25,
                ]),
            ],

            // Submarines
            [
                'designation' => 'Kilo-class',
                'nato_designation' => 'Improved Kilo',
                'common_name' => 'Project 636.3',
                'country_code' => 'RU',
                'category_slug' => 'submarines',
                'introduced_year' => 1997,
                'estimated_produced' => 40,
                'description' => 'Russian diesel-electric attack submarine by Admiralty Shipyards. "Black Hole" nickname for extremely quiet operation. Carries Kalibr cruise missiles for land attack. 6 torpedo tubes. Exported to China, India, Vietnam, Algeria. Used extensively for Ukraine strikes from Black Sea.',
                'specifications' => json_encode([
                    'manufacturer' => 'Admiralty Shipyards',
                    'origin_country' => 'Russia',
                    'displacement_tonnes' => 3950,
                    'length_m' => 74,
                    'torpedoes' => 6,
                    'missiles' => '4x Kalibr',
                    'crew' => 52,
                    'diving_depth_m' => 300,
                    'endurance_days' => 45,
                ]),
            ],
            [
                'designation' => 'Type 212A',
                'nato_designation' => null,
                'common_name' => 'Type 212',
                'country_code' => 'DE',
                'category_slug' => 'submarines',
                'introduced_year' => 2005,
                'estimated_produced' => 10,
                'description' => 'German air-independent propulsion submarine by ThyssenKrupp Marine Systems. Fuel cell AIP allows 2+ weeks submerged without surfacing. Extremely quiet non-nuclear sub. Basis for Italian Todaro-class. 6 in German Navy, 4 in Italian Navy. Type 212CD being developed with Norway.',
                'specifications' => json_encode([
                    'manufacturer' => 'ThyssenKrupp Marine Systems',
                    'origin_country' => 'Germany',
                    'displacement_tonnes' => 1830,
                    'length_m' => 56,
                    'torpedoes' => 6,
                    'crew' => 27,
                    'aip' => 'Fuel cell',
                    'submerged_endurance_days' => 14,
                ]),
            ],
            [
                'designation' => 'Soryu-class',
                'nato_designation' => null,
                'common_name' => 'Soryu',
                'country_code' => 'JP',
                'category_slug' => 'submarines',
                'introduced_year' => 2009,
                'estimated_produced' => 12,
                'description' => 'Japanese diesel-electric submarine by Mitsubishi Heavy Industries and Kawasaki Heavy Industries. Stirling AIP engine for extended submerged operations. X-form rudder for maneuverability. 12 built. Succeeded by lithium-ion battery Taigei-class. Nearly exported to Australia before French deal.',
                'specifications' => json_encode([
                    'manufacturer' => 'Mitsubishi/Kawasaki',
                    'origin_country' => 'Japan',
                    'displacement_tonnes' => 4200,
                    'length_m' => 84,
                    'torpedoes' => 6,
                    'missiles' => 'Harpoon capable',
                    'crew' => 65,
                    'aip' => 'Stirling',
                    'diving_depth_m' => 275,
                ]),
            ],
        ];

        $this->insertEquipment($vessels, $categories, $countries);
        $this->command->info('Naval vessels seeded (12 items)');
    }

    private function seedDrones(): void
    {
        $categories = DB::table('equipment_categories')->pluck('id', 'slug');
        $countries = DB::table('countries')->pluck('id', 'iso_code');

        $drones = [
            [
                'designation' => 'RQ-4 Global Hawk',
                'nato_designation' => null,
                'common_name' => 'Global Hawk',
                'country_code' => 'US',
                'category_slug' => 'uav',
                'introduced_year' => 2001,
                'estimated_produced' => 70,
                'description' => 'American high-altitude long-endurance surveillance UAV by Northrop Grumman. Can survey 40,000 square miles daily at 60,000 feet. 32+ hour endurance. Integrated sensor suite includes SAR, EO/IR, SIGINT. Used for ISR over Ukraine conflict from Polish airspace. EQ-4B variant for communications relay.',
                'specifications' => json_encode([
                    'manufacturer' => 'Northrop Grumman',
                    'origin_country' => 'United States',
                    'wingspan_m' => 39.9,
                    'length_m' => 14.5,
                    'ceiling_m' => 18000,
                    'endurance_hours' => 32,
                    'range_km' => 22000,
                    'unit_cost_million' => 130,
                ]),
            ],
            [
                'designation' => 'MQ-1C Gray Eagle',
                'nato_designation' => null,
                'common_name' => 'Gray Eagle',
                'country_code' => 'US',
                'category_slug' => 'uav',
                'introduced_year' => 2009,
                'estimated_produced' => 200,
                'description' => 'American medium-altitude long-endurance UCAV by General Atomics. Army version of Predator series. 25-hour endurance, heavy fuel engine. Carries Hellfire missiles and GBU-44 Viper Strike. Extensive combat record. Being upgraded to Extended Range variant with satellite communications.',
                'specifications' => json_encode([
                    'manufacturer' => 'General Atomics',
                    'origin_country' => 'United States',
                    'wingspan_m' => 17,
                    'endurance_hours' => 25,
                    'ceiling_m' => 8800,
                    'payload_kg' => 488,
                    'hardpoints' => 4,
                    'weapons' => 'AGM-114 Hellfire, GBU-44',
                ]),
            ],
            [
                'designation' => 'Wing Loong II',
                'nato_designation' => null,
                'common_name' => 'Wing Loong II',
                'country_code' => 'CN',
                'category_slug' => 'uav',
                'introduced_year' => 2017,
                'estimated_produced' => 100,
                'description' => 'Chinese medium-altitude long-endurance UCAV by Chengdu Aircraft Corporation. Competitor to MQ-9 Reaper. Export success to Egypt, UAE, Saudi Arabia, Pakistan, Serbia. 480kg weapon payload on 6 hardpoints. Satellite datalink for beyond-line-of-sight operations.',
                'specifications' => json_encode([
                    'manufacturer' => 'Chengdu Aircraft Corporation',
                    'origin_country' => 'China',
                    'wingspan_m' => 20.5,
                    'endurance_hours' => 20,
                    'ceiling_m' => 9000,
                    'payload_kg' => 480,
                    'hardpoints' => 6,
                    'operators' => ['Egypt', 'UAE', 'Saudi Arabia', 'Pakistan', 'Serbia'],
                ]),
            ],
            [
                'designation' => 'Shahed-136',
                'nato_designation' => 'Geran-2',
                'common_name' => 'Shahed-136',
                'country_code' => 'IR',
                'category_slug' => 'uav',
                'introduced_year' => 2021,
                'estimated_produced' => 3000,
                'description' => 'Iranian loitering munition (kamikaze drone) by Iran Aircraft Manufacturing Industries. Delta wing design with pusher propeller. GPS/INS guidance with 40kg warhead. Mass produced cheaply. Extensively used by Russia against Ukrainian infrastructure. Designated Geran-2 in Russian service.',
                'specifications' => json_encode([
                    'manufacturer' => 'Iran Aircraft Manufacturing Industries',
                    'origin_country' => 'Iran',
                    'wingspan_m' => 2.5,
                    'length_m' => 3.5,
                    'range_km' => 2500,
                    'warhead_kg' => 40,
                    'guidance' => 'GPS/INS',
                    'unit_cost_usd' => 20000,
                    'one_way' => true,
                ]),
            ],
            [
                'designation' => 'Mohajer-6',
                'nato_designation' => null,
                'common_name' => 'Mohajer-6',
                'country_code' => 'IR',
                'category_slug' => 'uav',
                'introduced_year' => 2017,
                'estimated_produced' => 200,
                'description' => 'Iranian reconnaissance and strike UAV by Qods Aviation Industries. Carries Ghaem smart bombs and missiles. Used by IRGC and transferred to Russia for Ukraine war. 24-hour endurance claimed. Represents significant Iranian drone capability advancement.',
                'specifications' => json_encode([
                    'manufacturer' => 'Qods Aviation Industries',
                    'origin_country' => 'Iran',
                    'wingspan_m' => 10,
                    'endurance_hours' => 24,
                    'ceiling_m' => 5500,
                    'payload_kg' => 40,
                    'weapons' => 'Ghaem smart bombs, Almas missiles',
                ]),
            ],
            [
                'designation' => 'Heron TP',
                'nato_designation' => 'Eitan',
                'common_name' => 'Eitan',
                'country_code' => 'IL',
                'category_slug' => 'uav',
                'introduced_year' => 2010,
                'estimated_produced' => 50,
                'description' => 'Israeli MALE UAV by Israel Aerospace Industries. Largest Israeli UAV at wingspan of 26m. 36-hour endurance, satellite communications. Can carry weapons including Spike missiles. Operated by Israeli Air Force for ISR and strike missions. Export variant sold to India.',
                'specifications' => json_encode([
                    'manufacturer' => 'Israel Aerospace Industries',
                    'origin_country' => 'Israel',
                    'wingspan_m' => 26,
                    'length_m' => 14,
                    'ceiling_m' => 13700,
                    'endurance_hours' => 36,
                    'payload_kg' => 1000,
                    'weapons' => 'Spike missiles',
                ]),
            ],
            [
                'designation' => 'Switchblade 600',
                'nato_designation' => null,
                'common_name' => 'Switchblade 600',
                'country_code' => 'US',
                'category_slug' => 'uav',
                'introduced_year' => 2022,
                'estimated_produced' => 1000,
                'description' => 'American loitering munition by AeroVironment. Larger than Switchblade 300, designed for armored vehicles. Javelin anti-tank warhead with top-attack capability. Backpack portable. 40-minute loiter time. Supplied to Ukraine. Fire-and-forget with abort capability.',
                'specifications' => json_encode([
                    'manufacturer' => 'AeroVironment',
                    'origin_country' => 'United States',
                    'weight_kg' => 23,
                    'range_km' => 40,
                    'loiter_time_min' => 40,
                    'warhead' => 'Anti-armor (Javelin type)',
                    'guidance' => 'GPS + EO/IR',
                    'man_portable' => true,
                ]),
            ],
            [
                'designation' => 'Hero-120',
                'nato_designation' => null,
                'common_name' => 'Hero-120',
                'country_code' => 'IL',
                'category_slug' => 'uav',
                'introduced_year' => 2019,
                'estimated_produced' => 500,
                'description' => 'Israeli loitering munition by UVision. Electric propulsion for silent approach. 60-minute loiter, 40km range. 4.5kg shaped charge warhead for light armor. Recoverable if target not engaged. Part of Hero family ranging from 30 to 1250 variants.',
                'specifications' => json_encode([
                    'manufacturer' => 'UVision',
                    'origin_country' => 'Israel',
                    'weight_kg' => 12.5,
                    'range_km' => 40,
                    'loiter_time_min' => 60,
                    'warhead_kg' => 4.5,
                    'guidance' => 'EO/IR',
                    'electric' => true,
                ]),
            ],
            [
                'designation' => 'MALE RPAS',
                'nato_designation' => 'Eurodrone',
                'common_name' => 'Eurodrone',
                'country_code' => 'DE',
                'category_slug' => 'uav',
                'introduced_year' => 2028,
                'estimated_produced' => 0,
                'description' => 'European medium-altitude long-endurance UAV under development by Airbus Defence. Joint program with Germany, France, Italy, Spain. Twin turboprop engines for redundancy. Intended to replace Heron TP and reduce dependence on US/Israeli systems. First flight expected 2027.',
                'specifications' => json_encode([
                    'manufacturer' => 'Airbus Defence',
                    'origin_country' => 'Germany/France/Italy/Spain',
                    'wingspan_m' => 26,
                    'endurance_hours' => 24,
                    'payload_kg' => 2300,
                    'ceiling_m' => 13000,
                    'status' => 'In development',
                ]),
            ],
        ];

        $this->insertEquipment($drones, $categories, $countries);
        $this->command->info('Drones seeded (9 items)');
    }

    private function seedArtillery(): void
    {
        $categories = DB::table('equipment_categories')->pluck('id', 'slug');
        $countries = DB::table('countries')->pluck('id', 'iso_code');

        $artillery = [
            [
                'designation' => 'M777A2',
                'nato_designation' => null,
                'common_name' => 'M777',
                'country_code' => 'US',
                'category_slug' => 'spa',
                'introduced_year' => 2005,
                'estimated_produced' => 1000,
                'description' => 'American/British towed 155mm howitzer by BAE Systems. Lightest 155mm howitzer at 4.2 tonnes using titanium and aluminum alloys. CH-47 helicopter transportable. Digital fire control with Excalibur precision rounds (40km). 150+ supplied to Ukraine. Combat proven in Afghanistan.',
                'specifications' => json_encode([
                    'manufacturer' => 'BAE Systems',
                    'origin_country' => 'United States/UK',
                    'caliber_mm' => 155,
                    'weight_kg' => 4200,
                    'range_km' => 24.7,
                    'range_excalibur_km' => 40,
                    'rate_of_fire' => '5 rounds/min',
                    'crew' => 8,
                    'helicopter_portable' => true,
                ]),
            ],
            [
                'designation' => 'M109A7 Paladin',
                'nato_designation' => null,
                'common_name' => 'Paladin',
                'country_code' => 'US',
                'category_slug' => 'spa',
                'introduced_year' => 2015,
                'estimated_produced' => 580,
                'description' => 'American 155mm self-propelled howitzer by BAE Systems. Latest M109 variant with new chassis, engine, and digital fire control. Bradley-derived components for commonality. Automated ammunition handling. M109A6 being upgraded to A7 standard.',
                'specifications' => json_encode([
                    'manufacturer' => 'BAE Systems',
                    'origin_country' => 'United States',
                    'caliber_mm' => 155,
                    'weight_tonnes' => 35,
                    'range_km' => 30,
                    'rate_of_fire' => '4 rounds/min',
                    'crew' => 4,
                    'ammunition' => 39,
                ]),
            ],
            [
                'designation' => '2A36 Giatsint-B',
                'nato_designation' => null,
                'common_name' => 'Giatsint',
                'country_code' => 'RU',
                'category_slug' => 'spa',
                'introduced_year' => 1975,
                'estimated_produced' => 2500,
                'description' => 'Soviet/Russian 152mm towed gun-howitzer by Uraltransmash. Exceptional 28km range with conventional shells. Used for counter-battery fire. Both towed (2A36) and self-propelled (2S5) variants. Still heavily used in Ukraine conflict by both sides.',
                'specifications' => json_encode([
                    'manufacturer' => 'Uraltransmash',
                    'origin_country' => 'Russia',
                    'caliber_mm' => 152,
                    'weight_kg' => 9800,
                    'range_km' => 28,
                    'rate_of_fire' => '6 rounds/min',
                    'crew' => 8,
                    'towed' => true,
                ]),
            ],
            [
                'designation' => 'D-30',
                'nato_designation' => null,
                'common_name' => 'D-30',
                'country_code' => 'RU',
                'category_slug' => 'spa',
                'introduced_year' => 1963,
                'estimated_produced' => 10000,
                'description' => 'Soviet towed 122mm howitzer by No. 9 Plant. Unique three-trail design allows 360° traverse. Simple, reliable, produced in vast numbers. Used by 60+ countries. Still standard light artillery in many armies. Extensively used in Ukraine by both sides.',
                'specifications' => json_encode([
                    'manufacturer' => 'No. 9 Plant Yekaterinburg',
                    'origin_country' => 'Russia',
                    'caliber_mm' => 122,
                    'weight_kg' => 3200,
                    'range_km' => 15.3,
                    'rate_of_fire' => '8 rounds/min',
                    'crew' => 7,
                    'traverse' => '360°',
                ]),
            ],
            [
                'designation' => 'FH-70',
                'nato_designation' => null,
                'common_name' => 'FH-70',
                'country_code' => 'DE',
                'category_slug' => 'spa',
                'introduced_year' => 1978,
                'estimated_produced' => 1100,
                'description' => 'NATO standard 155mm towed howitzer by Rheinmetall, OTO Melara, and Royal Ordnance. Auxiliary power unit for self-propulsion. Used by Italy, Germany (phased out), Japan, Estonia. Some transferred to Ukraine. 24km range with conventional rounds.',
                'specifications' => json_encode([
                    'manufacturer' => 'Rheinmetall/OTO Melara/Royal Ordnance',
                    'origin_country' => 'Germany/Italy/UK',
                    'caliber_mm' => 155,
                    'weight_kg' => 9300,
                    'range_km' => 24,
                    'rate_of_fire' => '6 rounds/min',
                    'crew' => 8,
                    'apu' => true,
                ]),
            ],
            [
                'designation' => 'ATMOS 2000',
                'nato_designation' => null,
                'common_name' => 'ATMOS',
                'country_code' => 'IL',
                'category_slug' => 'spa',
                'introduced_year' => 2001,
                'estimated_produced' => 150,
                'description' => 'Israeli truck-mounted 155mm howitzer by Soltam. 6x6 truck chassis provides high mobility. Automated loading, digital fire control. Multiple export customers. ATMOS 2000+ variant with extended range. Similar concept to French CAESAR.',
                'specifications' => json_encode([
                    'manufacturer' => 'Soltam Systems (Elbit)',
                    'origin_country' => 'Israel',
                    'caliber_mm' => 155,
                    'weight_tonnes' => 18,
                    'range_km' => 40,
                    'rate_of_fire' => '9 rounds/min',
                    'crew' => 4,
                    'ammunition' => 18,
                ]),
            ],
            [
                'designation' => 'Tornado-G',
                'nato_designation' => null,
                'common_name' => 'Tornado-G',
                'country_code' => 'RU',
                'category_slug' => 'mlrs',
                'introduced_year' => 2012,
                'estimated_produced' => 200,
                'description' => 'Russian 122mm multiple rocket launcher system modernizing BM-21 Grad. GPS/GLONASS guided rockets double effective range. Automated fire control, reduced crew. Recognizable by enclosed armored cabin. Extensively used in Ukraine.',
                'specifications' => json_encode([
                    'manufacturer' => 'Splav',
                    'origin_country' => 'Russia',
                    'tubes' => 40,
                    'caliber_mm' => 122,
                    'range_km' => 40,
                    'guidance' => 'GPS/GLONASS',
                    'crew' => 2,
                    'reload_min' => 5,
                ]),
            ],
            [
                'designation' => 'Tornado-S',
                'nato_designation' => null,
                'common_name' => 'Tornado-S',
                'country_code' => 'RU',
                'category_slug' => 'mlrs',
                'introduced_year' => 2017,
                'estimated_produced' => 100,
                'description' => 'Russian 300mm GPS-guided multiple rocket launcher system replacing BM-30 Smerch. 120km range with precision-guided rockets. Glonass/GPS correction. Thermobaric, cluster, and sensor-fuzed munitions. Most advanced Russian MLRS.',
                'specifications' => json_encode([
                    'manufacturer' => 'Splav',
                    'origin_country' => 'Russia',
                    'tubes' => 12,
                    'caliber_mm' => 300,
                    'range_km' => 120,
                    'guidance' => 'GLONASS/GPS',
                    'crew' => 3,
                    'cep_m' => 10,
                ]),
            ],
            [
                'designation' => 'RM-70',
                'nato_designation' => null,
                'common_name' => 'RM-70',
                'country_code' => 'CZ',
                'category_slug' => 'mlrs',
                'introduced_year' => 1972,
                'estimated_produced' => 500,
                'description' => 'Czechoslovak/Czech 122mm multiple rocket launcher based on BM-21. Mounted on Tatra 813 8x8 truck. Spare rocket pack allows rapid reload. Used by former Warsaw Pact countries and exported. Transferred to Ukraine by multiple NATO allies.',
                'specifications' => json_encode([
                    'manufacturer' => 'ZTS Dubnica',
                    'origin_country' => 'Czechoslovakia/Czech Republic',
                    'tubes' => 40,
                    'caliber_mm' => 122,
                    'range_km' => 20,
                    'crew' => 6,
                    'spare_pack' => true,
                ]),
            ],
        ];

        $this->insertEquipment($artillery, $categories, $countries);
        $this->command->info('Artillery seeded (9 items)');
    }

    private function seedAirDefense(): void
    {
        $categories = DB::table('equipment_categories')->pluck('id', 'slug');
        $countries = DB::table('countries')->pluck('id', 'iso_code');

        $airDefense = [
            [
                'designation' => 'NASAMS',
                'nato_designation' => null,
                'common_name' => 'NASAMS',
                'country_code' => 'NO',
                'category_slug' => 'sam',
                'introduced_year' => 1994,
                'estimated_produced' => 200,
                'description' => 'Norwegian/American advanced surface-to-air missile system by Kongsberg/Raytheon. Uses AMRAAM missiles adapted for ground launch. High mobility and network-centric operation. Supplied to Ukraine with excellent results against cruise missiles and drones. Protects Washington DC airspace.',
                'specifications' => json_encode([
                    'manufacturer' => 'Kongsberg/Raytheon',
                    'origin_country' => 'Norway/United States',
                    'missile' => 'AIM-120 AMRAAM',
                    'range_km' => 25,
                    'altitude_km' => 15,
                    'launchers_per_battery' => 6,
                    'missiles_per_launcher' => 6,
                    'operators' => 12,
                ]),
            ],
            [
                'designation' => 'S-300PM2',
                'nato_designation' => 'SA-20B Gargoyle',
                'common_name' => 'S-300PMU2 Favorit',
                'country_code' => 'RU',
                'category_slug' => 'sam',
                'introduced_year' => 1997,
                'estimated_produced' => 150,
                'description' => 'Russian long-range SAM system by Almaz-Antey. Export variant of S-300 with 200km range. 48N6E2 missiles. Widely exported to China, Iran, Syria, Algeria, Vietnam. Predecessor to S-400. Some units transferred to Ukraine by former Soviet states.',
                'specifications' => json_encode([
                    'manufacturer' => 'Almaz-Antey',
                    'origin_country' => 'Russia',
                    'missile' => '48N6E2',
                    'range_km' => 200,
                    'altitude_km' => 27,
                    'missiles_per_launcher' => 4,
                    'targets_per_battery' => 36,
                ]),
            ],
            [
                'designation' => 'Tor-M2',
                'nato_designation' => 'SA-15 Gauntlet',
                'common_name' => 'Tor-M2',
                'country_code' => 'RU',
                'category_slug' => 'sam',
                'introduced_year' => 2012,
                'estimated_produced' => 300,
                'description' => 'Russian short-range SAM system by Almaz-Antey. Designed to intercept precision-guided munitions and cruise missiles. 16 ready missiles per TLAR. Phased array radar with 48 target tracking. Very short reaction time. Wheeled and tracked variants. Combat proven in Syria.',
                'specifications' => json_encode([
                    'manufacturer' => 'Almaz-Antey',
                    'origin_country' => 'Russia',
                    'missile' => '9M338',
                    'range_km' => 15,
                    'altitude_km' => 10,
                    'missiles_per_vehicle' => 16,
                    'reaction_time_s' => 8,
                ]),
            ],
            [
                'designation' => 'SAMP/T',
                'nato_designation' => 'Mamba',
                'common_name' => 'SAMP/T',
                'country_code' => 'FR',
                'category_slug' => 'sam',
                'introduced_year' => 2011,
                'estimated_produced' => 30,
                'description' => 'Franco-Italian surface-to-air missile platform by Eurosam. Uses Aster 30 missiles with 120km range. Active radar homing with hit-to-kill. Anti-ballistic missile capability against TBMs. Deployed by France and Italy. Supplied to Ukraine for strategic air defense.',
                'specifications' => json_encode([
                    'manufacturer' => 'Eurosam',
                    'origin_country' => 'France/Italy',
                    'missile' => 'Aster 30',
                    'range_km' => 120,
                    'altitude_km' => 20,
                    'vls_cells' => 48,
                    'anti_tbm' => true,
                ]),
            ],
            [
                'designation' => 'SPYDER',
                'nato_designation' => null,
                'common_name' => 'SPYDER',
                'country_code' => 'IL',
                'category_slug' => 'sam',
                'introduced_year' => 2005,
                'estimated_produced' => 100,
                'description' => 'Israeli short-range air defense system by Rafael. Uses Python-5 and Derby missiles. Quick reaction capability with 360° coverage. Export success to India, Singapore, Philippines, Georgia. SR and MR variants with different ranges.',
                'specifications' => json_encode([
                    'manufacturer' => 'Rafael',
                    'origin_country' => 'Israel',
                    'missiles' => ['Python-5', 'Derby'],
                    'range_km' => 35,
                    'altitude_km' => 16,
                    'missiles_per_launcher' => 4,
                    'operators' => 10,
                ]),
            ],
            [
                'designation' => 'HQ-9',
                'nato_designation' => 'CSA-9',
                'common_name' => 'HQ-9',
                'country_code' => 'CN',
                'category_slug' => 'sam',
                'introduced_year' => 1997,
                'estimated_produced' => 200,
                'description' => 'Chinese long-range SAM system by CASIC. Comparable to S-300/Patriot. Active radar homing with 200km range. Export variant FD-2000 selected by Turkey (later cancelled). HQ-9B variant with extended range. Primary Chinese strategic air defense.',
                'specifications' => json_encode([
                    'manufacturer' => 'CASIC',
                    'origin_country' => 'China',
                    'range_km' => 200,
                    'altitude_km' => 30,
                    'missiles_per_launcher' => 4,
                    'guidance' => 'Active radar homing',
                    'anti_tbm' => true,
                ]),
            ],
            [
                'designation' => 'Gepard',
                'nato_designation' => null,
                'common_name' => 'Flakpanzer Gepard',
                'country_code' => 'DE',
                'category_slug' => 'sam',
                'introduced_year' => 1976,
                'estimated_produced' => 570,
                'description' => 'German self-propelled anti-aircraft gun by Krauss-Maffei. Twin 35mm Oerlikon guns with radar fire control. Leopard 1 chassis. Highly effective against drones as proven in Ukraine. 37 transferred to Ukraine. Now in high demand despite age.',
                'specifications' => json_encode([
                    'manufacturer' => 'Krauss-Maffei',
                    'origin_country' => 'Germany',
                    'guns' => '2x 35mm Oerlikon',
                    'rate_of_fire' => '1100 rounds/min',
                    'effective_range_m' => 5500,
                    'altitude_m' => 4000,
                    'chassis' => 'Leopard 1',
                    'crew' => 3,
                ]),
            ],
            [
                'designation' => 'Skyranger 30',
                'nato_designation' => null,
                'common_name' => 'Skyranger 30',
                'country_code' => 'DE',
                'category_slug' => 'sam',
                'introduced_year' => 2024,
                'estimated_produced' => 10,
                'description' => 'German air defense turret system by Rheinmetall. 30mm revolver cannon with programmable ammunition. Designed primarily for counter-UAS role. Can be mounted on various vehicles including Boxer. Selected by Germany to replace Gepard. Ordered by Ukraine.',
                'specifications' => json_encode([
                    'manufacturer' => 'Rheinmetall',
                    'origin_country' => 'Germany',
                    'gun' => '30mm Oerlikon KCE',
                    'rate_of_fire' => '1200 rounds/min',
                    'effective_range_km' => 3,
                    'ammunition' => 'Programmable airburst',
                    'counter_uas' => true,
                ]),
            ],
        ];

        $this->insertEquipment($airDefense, $categories, $countries);
        $this->command->info('Air defense systems seeded (8 items)');
    }

    private function seedSupportVehicles(): void
    {
        $categories = DB::table('equipment_categories')->pluck('id', 'slug');
        $countries = DB::table('countries')->pluck('id', 'iso_code');

        $vehicles = [
            [
                'designation' => 'Oshkosh M-ATV',
                'nato_designation' => null,
                'common_name' => 'M-ATV',
                'country_code' => 'US',
                'category_slug' => 'apc',
                'introduced_year' => 2009,
                'estimated_produced' => 10000,
                'description' => 'American mine-resistant ambush protected vehicle by Oshkosh Defense. Replaced HMMWV in high-threat areas. V-shaped hull defeats IED blasts. 4-person crew. Multiple variants for command, ambulance, special operations. Supplied to Ukraine and numerous allies.',
                'specifications' => json_encode([
                    'manufacturer' => 'Oshkosh Defense',
                    'origin_country' => 'United States',
                    'weight_tonnes' => 14.9,
                    'crew' => 4,
                    'max_speed_kmh' => 105,
                    'range_km' => 515,
                    'protection' => 'MRAP',
                    'armament' => 'Various weapon stations',
                ]),
            ],
            [
                'designation' => 'MaxxPro',
                'nato_designation' => null,
                'common_name' => 'MaxxPro',
                'country_code' => 'US',
                'category_slug' => 'apc',
                'introduced_year' => 2007,
                'estimated_produced' => 9000,
                'description' => 'American MRAP vehicle by Navistar Defense. Category I MRAP with monocoque V-hull. Protects against EFP and underbelly IED threats. 200+ transferred to Ukraine. Multiple variants including ambulance and command.',
                'specifications' => json_encode([
                    'manufacturer' => 'Navistar Defense',
                    'origin_country' => 'United States',
                    'weight_tonnes' => 15,
                    'crew' => 6,
                    'max_speed_kmh' => 105,
                    'protection' => 'MRAP Category I',
                ]),
            ],
            [
                'designation' => 'Mastiff PPV',
                'nato_designation' => null,
                'common_name' => 'Mastiff',
                'country_code' => 'GB',
                'category_slug' => 'apc',
                'introduced_year' => 2007,
                'estimated_produced' => 400,
                'description' => 'British protected patrol vehicle based on Cougar MRAP. 6x6 configuration. V-shaped hull and blast-resistant seats. Used extensively in Afghanistan. Replaced by Foxhound. Some transferred to Ukraine.',
                'specifications' => json_encode([
                    'manufacturer' => 'Force Protection/General Dynamics',
                    'origin_country' => 'United Kingdom/USA',
                    'weight_tonnes' => 23,
                    'crew' => 8,
                    'configuration' => '6x6',
                    'protection' => 'MRAP',
                ]),
            ],
            [
                'designation' => 'Bushmaster PMV',
                'nato_designation' => null,
                'common_name' => 'Bushmaster',
                'country_code' => 'AU',
                'category_slug' => 'apc',
                'introduced_year' => 1998,
                'estimated_produced' => 1200,
                'description' => 'Australian protected mobility vehicle by Thales Australia. 4x4 mine-resistant design. Proven in Afghanistan, Iraq. Exported to Netherlands, Jamaica, Japan. 90+ donated to Ukraine. Highly regarded for protection and reliability.',
                'specifications' => json_encode([
                    'manufacturer' => 'Thales Australia',
                    'origin_country' => 'Australia',
                    'weight_tonnes' => 15,
                    'crew' => 9,
                    'max_speed_kmh' => 100,
                    'range_km' => 800,
                    'configuration' => '4x4',
                ]),
            ],
            [
                'designation' => 'Kozak-2M1',
                'nato_designation' => null,
                'common_name' => 'Kozak-2',
                'country_code' => 'UA',
                'category_slug' => 'apc',
                'introduced_year' => 2016,
                'estimated_produced' => 500,
                'description' => 'Ukrainian armored vehicle by NPO Praktika based on Ford F-550. 4x4 MRAP-class protection. Multiple variants: personnel carrier, ambulance, command. Indigenous production supporting Ukrainian military. STANAG 2 protection level.',
                'specifications' => json_encode([
                    'manufacturer' => 'NPO Praktika',
                    'origin_country' => 'Ukraine',
                    'weight_tonnes' => 9,
                    'crew' => 10,
                    'max_speed_kmh' => 120,
                    'base_vehicle' => 'Ford F-550',
                    'protection' => 'STANAG Level 2',
                ]),
            ],
            [
                'designation' => 'Fennek',
                'nato_designation' => null,
                'common_name' => 'Fennek',
                'country_code' => 'DE',
                'category_slug' => 'apc',
                'introduced_year' => 2003,
                'estimated_produced' => 410,
                'description' => 'German/Dutch reconnaissance vehicle by Krauss-Maffei Wegmann and STORK PWV. Low profile 4x4 with extensible sensor mast. Primarily used for reconnaissance and forward observer roles. Joint program between Germany and Netherlands.',
                'specifications' => json_encode([
                    'manufacturer' => 'KMW/STORK',
                    'origin_country' => 'Germany/Netherlands',
                    'weight_tonnes' => 10.3,
                    'crew' => 3,
                    'max_speed_kmh' => 115,
                    'range_km' => 860,
                    'sensor_mast' => true,
                ]),
            ],
            [
                'designation' => 'RG-31 Nyala',
                'nato_designation' => null,
                'common_name' => 'RG-31',
                'country_code' => 'ZA',
                'category_slug' => 'apc',
                'introduced_year' => 1996,
                'estimated_produced' => 1400,
                'description' => 'South African mine-protected vehicle by Land Systems OMC (now Denel). V-hull design pioneered MRAP concept. Used by US, Canada, Spain. Combat proven in multiple peacekeeping and combat operations.',
                'specifications' => json_encode([
                    'manufacturer' => 'Denel Land Systems',
                    'origin_country' => 'South Africa',
                    'weight_tonnes' => 8.5,
                    'crew' => 10,
                    'max_speed_kmh' => 105,
                    'range_km' => 700,
                    'protection' => 'MRAP',
                ]),
            ],
            [
                'designation' => 'Dingo 2',
                'nato_designation' => null,
                'common_name' => 'Dingo 2',
                'country_code' => 'DE',
                'category_slug' => 'apc',
                'introduced_year' => 2007,
                'estimated_produced' => 900,
                'description' => 'German infantry mobility vehicle by Krauss-Maffei Wegmann. All-protected vehicle based on Unimog chassis. MRAP-level protection. Used by Germany, Austria, Belgium, Czech Republic, Luxembourg, Norway. Multiple variants available.',
                'specifications' => json_encode([
                    'manufacturer' => 'KMW',
                    'origin_country' => 'Germany',
                    'weight_tonnes' => 12.5,
                    'crew' => 8,
                    'max_speed_kmh' => 90,
                    'range_km' => 1000,
                    'base' => 'Unimog U5000',
                ]),
            ],
        ];

        $this->insertEquipment($vehicles, $categories, $countries);
        $this->command->info('Support vehicles seeded (8 items)');
    }

    private function insertEquipment(array $items, $categories, $countries): void
    {
        foreach ($items as $item) {
            $countryId = $countries[$item['country_code']] ?? null;
            $categoryId = $categories[$item['category_slug']] ?? null;

            if (!$countryId || !$categoryId) {
                $this->command->warn("Skipping {$item['designation']}: Missing country or category");
                continue;
            }

            DB::table('military_equipment')->updateOrInsert(
                ['designation' => $item['designation']],
                [
                    'uuid' => Str::uuid(),
                    'designation' => $item['designation'],
                    'nato_designation' => $item['nato_designation'],
                    'common_name' => $item['common_name'],
                    'country_id' => $countryId,
                    'category_id' => $categoryId,
                    'introduced_year' => $item['introduced_year'],
                    'estimated_produced' => $item['estimated_produced'],
                    'description' => $item['description'],
                    'specifications' => $item['specifications'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
