<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ConflictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Seeds realistic active and historical conflicts.
     */
    public function run(): void
    {
        $conflicts = [
            // Active Major Conflicts
            [
                'name' => 'Russo-Ukrainian War',
                'slug' => 'russia-ukraine-war',
                'description' => 'Full-scale invasion of Ukraine by the Russian Federation beginning February 24, 2022. Largest conventional military conflict in Europe since World War II. Involves extensive use of drones, precision missiles, and combined arms warfare. Major territorial changes in eastern and southern Ukraine.',
                'start_date' => '2022-02-24',
                'end_date' => null,
                'status' => 'active',
                'region' => 'Europe',
                'intensity' => 'high',
                'type' => 'interstate',
                'casualties_estimate' => '500000+',
                'displaced_estimate' => '14000000',
                'primary_parties' => json_encode(['Ukraine', 'Russia']),
                'secondary_parties' => json_encode(['Belarus', 'Wagner Group']),
                'keywords' => json_encode(['Ukraine', 'Russia', 'Donbas', 'Crimea', 'Kherson', 'Bakhmut', 'Avdiivka']),
            ],
            [
                'name' => 'Israel-Hamas War',
                'slug' => 'israel-hamas-war-2023',
                'description' => 'Conflict triggered by Hamas attack on October 7, 2023 resulting in Israeli ground invasion of Gaza Strip. Characterized by urban warfare, tunnel combat, and significant civilian casualties. Involves rocket attacks, precision strikes, and hostage situations.',
                'start_date' => '2023-10-07',
                'end_date' => null,
                'status' => 'active',
                'region' => 'Middle East',
                'intensity' => 'high',
                'type' => 'asymmetric',
                'casualties_estimate' => '40000+',
                'displaced_estimate' => '2000000',
                'primary_parties' => json_encode(['Israel', 'Hamas']),
                'secondary_parties' => json_encode(['Palestinian Islamic Jihad', 'Hezbollah']),
                'keywords' => json_encode(['Gaza', 'Israel', 'Hamas', 'October 7', 'Rafah', 'Khan Younis']),
            ],
            [
                'name' => 'Syrian Civil War',
                'slug' => 'syrian-civil-war',
                'description' => 'Multi-sided civil war in Syria ongoing since 2011. Involves Syrian government, various rebel factions, Kurdish forces, ISIS remnants, and foreign interventions by Russia, Iran, Turkey, and the US-led coalition. Characterized by siege warfare and mass displacement.',
                'start_date' => '2011-03-15',
                'end_date' => null,
                'status' => 'active',
                'region' => 'Middle East',
                'intensity' => 'medium',
                'type' => 'civil_war',
                'casualties_estimate' => '500000+',
                'displaced_estimate' => '13000000',
                'primary_parties' => json_encode(['Syrian Government', 'Syrian Opposition']),
                'secondary_parties' => json_encode(['Russia', 'Iran', 'Turkey', 'SDF', 'ISIS']),
                'keywords' => json_encode(['Syria', 'Assad', 'Idlib', 'Aleppo', 'Damascus', 'SDF', 'ISIS']),
            ],
            [
                'name' => 'Yemeni Civil War',
                'slug' => 'yemeni-civil-war',
                'description' => 'Civil war between Houthi rebels and internationally recognized government backed by Saudi-led coalition. Features extensive drone and missile attacks on Saudi Arabia and UAE. Severe humanitarian crisis with famine conditions.',
                'start_date' => '2014-09-21',
                'end_date' => null,
                'status' => 'active',
                'region' => 'Middle East',
                'intensity' => 'medium',
                'type' => 'civil_war',
                'casualties_estimate' => '150000+',
                'displaced_estimate' => '4000000',
                'primary_parties' => json_encode(['Houthi Movement', 'Yemeni Government']),
                'secondary_parties' => json_encode(['Saudi Arabia', 'UAE', 'Iran']),
                'keywords' => json_encode(['Yemen', 'Houthi', 'Sanaa', 'Aden', 'Red Sea']),
            ],
            [
                'name' => 'Myanmar Civil War',
                'slug' => 'myanmar-civil-war',
                'description' => 'Armed conflict following 2021 military coup. Involves military junta (Tatmadaw) against People\'s Defence Forces and ethnic armed organizations. Widespread resistance across the country with significant territorial losses for the military.',
                'start_date' => '2021-02-01',
                'end_date' => null,
                'status' => 'active',
                'region' => 'Southeast Asia',
                'intensity' => 'medium',
                'type' => 'civil_war',
                'casualties_estimate' => '50000+',
                'displaced_estimate' => '2500000',
                'primary_parties' => json_encode(['Myanmar Military', 'PDF/NUG']),
                'secondary_parties' => json_encode(['KIA', 'KNU', 'AA', 'TNLA']),
                'keywords' => json_encode(['Myanmar', 'Burma', 'Tatmadaw', 'PDF', 'Rakhine']),
            ],
            [
                'name' => 'Sudan Civil War',
                'slug' => 'sudan-civil-war-2023',
                'description' => 'Armed conflict between Sudanese Armed Forces and Rapid Support Forces beginning April 2023. Urban warfare in Khartoum, ethnic violence in Darfur. Massive humanitarian crisis and displacement.',
                'start_date' => '2023-04-15',
                'end_date' => null,
                'status' => 'active',
                'region' => 'Africa',
                'intensity' => 'high',
                'type' => 'civil_war',
                'casualties_estimate' => '15000+',
                'displaced_estimate' => '10000000',
                'primary_parties' => json_encode(['SAF', 'RSF']),
                'secondary_parties' => json_encode([]),
                'keywords' => json_encode(['Sudan', 'Khartoum', 'Darfur', 'RSF', 'Hemedti']),
            ],
            [
                'name' => 'Ethiopian Civil Conflict',
                'slug' => 'ethiopian-conflict',
                'description' => 'Multi-front conflict involving federal government, Tigray forces, Amhara militias, and Oromia insurgents. 2020-2022 Tigray War caused massive casualties. Ongoing tensions despite ceasefire agreements.',
                'start_date' => '2020-11-04',
                'end_date' => null,
                'status' => 'active',
                'region' => 'Africa',
                'intensity' => 'medium',
                'type' => 'civil_war',
                'casualties_estimate' => '600000+',
                'displaced_estimate' => '3000000',
                'primary_parties' => json_encode(['Ethiopian Government', 'TPLF']),
                'secondary_parties' => json_encode(['Eritrea', 'Amhara Fano', 'OLA']),
                'keywords' => json_encode(['Ethiopia', 'Tigray', 'Amhara', 'Oromia', 'Addis Ababa']),
            ],
            [
                'name' => 'Sahel Insurgency',
                'slug' => 'sahel-insurgency',
                'description' => 'Jihadist insurgency across Mali, Burkina Faso, and Niger by groups linked to Al-Qaeda and ISIS. French withdrawal and military coups have complicated counter-terrorism efforts. Wagner Group involvement.',
                'start_date' => '2012-01-16',
                'end_date' => null,
                'status' => 'active',
                'region' => 'Africa',
                'intensity' => 'medium',
                'type' => 'insurgency',
                'casualties_estimate' => '50000+',
                'displaced_estimate' => '4000000',
                'primary_parties' => json_encode(['Sahel Governments', 'JNIM', 'ISGS']),
                'secondary_parties' => json_encode(['Wagner Group', 'France']),
                'keywords' => json_encode(['Mali', 'Burkina Faso', 'Niger', 'JNIM', 'Sahel']),
            ],

            // Lower Intensity Active Conflicts
            [
                'name' => 'Nagorno-Karabakh Conflict',
                'slug' => 'nagorno-karabakh',
                'description' => 'Dispute over Nagorno-Karabakh region between Armenia and Azerbaijan. 2020 war resulted in Azerbaijani victory. September 2023 offensive led to complete Armenian exodus from the region.',
                'start_date' => '1988-02-20',
                'end_date' => '2023-09-20',
                'status' => 'concluded',
                'region' => 'Caucasus',
                'intensity' => 'low',
                'type' => 'territorial',
                'casualties_estimate' => '40000+',
                'displaced_estimate' => '120000',
                'primary_parties' => json_encode(['Azerbaijan', 'Armenia']),
                'secondary_parties' => json_encode(['Russia', 'Turkey']),
                'keywords' => json_encode(['Karabakh', 'Azerbaijan', 'Armenia', 'Artsakh', 'Stepanakert']),
            ],
            [
                'name' => 'Kashmir Conflict',
                'slug' => 'kashmir-conflict',
                'description' => 'Territorial dispute between India and Pakistan over Kashmir region. Recurring military clashes along Line of Control. Insurgency in Indian-administered Kashmir with periodic escalations.',
                'start_date' => '1947-10-22',
                'end_date' => null,
                'status' => 'active',
                'region' => 'South Asia',
                'intensity' => 'low',
                'type' => 'territorial',
                'casualties_estimate' => '100000+',
                'displaced_estimate' => '1000000',
                'primary_parties' => json_encode(['India', 'Pakistan']),
                'secondary_parties' => json_encode(['Kashmiri militants']),
                'keywords' => json_encode(['Kashmir', 'India', 'Pakistan', 'LOC', 'Srinagar']),
            ],
            [
                'name' => 'Taiwan Strait Tensions',
                'slug' => 'taiwan-strait',
                'description' => 'Strategic competition between China and Taiwan with increasing military activity. PLA air and naval incursions into Taiwan\'s ADIZ. Risk of potential military conflict over Taiwan\'s status.',
                'start_date' => '1949-10-01',
                'end_date' => null,
                'status' => 'tension',
                'region' => 'East Asia',
                'intensity' => 'low',
                'type' => 'territorial',
                'casualties_estimate' => null,
                'displaced_estimate' => null,
                'primary_parties' => json_encode(['China', 'Taiwan']),
                'secondary_parties' => json_encode(['United States', 'Japan']),
                'keywords' => json_encode(['Taiwan', 'China', 'PLA', 'Taipei', 'strait']),
            ],
            [
                'name' => 'Korean Peninsula Tensions',
                'slug' => 'korean-peninsula',
                'description' => 'Ongoing military standoff between North Korea and South Korea since 1953 armistice. Periodic provocations including missile tests and border incidents. Nuclear weapons development by DPRK.',
                'start_date' => '1950-06-25',
                'end_date' => null,
                'status' => 'tension',
                'region' => 'East Asia',
                'intensity' => 'low',
                'type' => 'interstate',
                'casualties_estimate' => null,
                'displaced_estimate' => null,
                'primary_parties' => json_encode(['North Korea', 'South Korea']),
                'secondary_parties' => json_encode(['United States', 'China']),
                'keywords' => json_encode(['North Korea', 'South Korea', 'DPRK', 'DMZ', 'Pyongyang']),
            ],

            // Historical Conflicts (for reference data)
            [
                'name' => 'Gulf War',
                'slug' => 'gulf-war-1991',
                'description' => 'Coalition military campaign to liberate Kuwait from Iraqi occupation. Featured extensive air campaign and rapid ground offensive. First large-scale deployment of precision-guided munitions.',
                'start_date' => '1990-08-02',
                'end_date' => '1991-02-28',
                'status' => 'concluded',
                'region' => 'Middle East',
                'intensity' => 'high',
                'type' => 'interstate',
                'casualties_estimate' => '50000',
                'displaced_estimate' => '5000000',
                'primary_parties' => json_encode(['Coalition', 'Iraq']),
                'secondary_parties' => json_encode([]),
                'keywords' => json_encode(['Kuwait', 'Iraq', 'Desert Storm', 'Saddam']),
            ],
            [
                'name' => 'Iraq War',
                'slug' => 'iraq-war-2003',
                'description' => 'US-led invasion and subsequent occupation of Iraq. Overthrow of Saddam Hussein followed by insurgency and sectarian conflict. Withdrawal completed 2011 with ongoing instability.',
                'start_date' => '2003-03-20',
                'end_date' => '2011-12-18',
                'status' => 'concluded',
                'region' => 'Middle East',
                'intensity' => 'high',
                'type' => 'interstate',
                'casualties_estimate' => '500000+',
                'displaced_estimate' => '4000000',
                'primary_parties' => json_encode(['Coalition', 'Iraq']),
                'secondary_parties' => json_encode(['Al-Qaeda in Iraq', 'Mahdi Army']),
                'keywords' => json_encode(['Iraq', 'Baghdad', 'Fallujah', 'WMD', 'insurgency']),
            ],
            [
                'name' => 'War in Afghanistan',
                'slug' => 'afghanistan-war',
                'description' => 'US-led intervention following 9/11 attacks. Twenty-year conflict ending with Taliban takeover in August 2021. Longest war in US history involving counter-terrorism and nation-building efforts.',
                'start_date' => '2001-10-07',
                'end_date' => '2021-08-30',
                'status' => 'concluded',
                'region' => 'Central Asia',
                'intensity' => 'medium',
                'type' => 'insurgency',
                'casualties_estimate' => '200000+',
                'displaced_estimate' => '6000000',
                'primary_parties' => json_encode(['Coalition/Afghan Government', 'Taliban']),
                'secondary_parties' => json_encode(['Al-Qaeda', 'ISIS-K']),
                'keywords' => json_encode(['Afghanistan', 'Taliban', 'Kabul', 'Kandahar', 'Helmand']),
            ],
            [
                'name' => 'Libyan Civil War',
                'slug' => 'libyan-civil-war',
                'description' => 'Two civil wars (2011 and 2014-2020) following NATO intervention and overthrow of Gaddafi. Ongoing political instability with rival governments. Foreign intervention by Turkey, UAE, Russia.',
                'start_date' => '2011-02-15',
                'end_date' => null,
                'status' => 'frozen',
                'region' => 'North Africa',
                'intensity' => 'low',
                'type' => 'civil_war',
                'casualties_estimate' => '50000+',
                'displaced_estimate' => '500000',
                'primary_parties' => json_encode(['GNA', 'LNA']),
                'secondary_parties' => json_encode(['Turkey', 'UAE', 'Russia', 'Wagner']),
                'keywords' => json_encode(['Libya', 'Tripoli', 'Benghazi', 'Haftar', 'GNA']),
            ],
        ];

        $typeMapping = [
            'interstate' => 'INTERSTATE',
            'civil_war' => 'CIVIL_WAR',
            'insurgency' => 'INSURGENCY',
            'asymmetric' => 'OTHER',
            'territorial' => 'BORDER_DISPUTE',
        ];

        $statusMapping = [
            'active' => true,
            'tension' => true,
            'concluded' => false,
            'frozen' => false,
        ];

        foreach ($conflicts as $conflict) {
            $name = $conflict['name'];
            $existingConflict = DB::table('conflicts')->where('name', $name)->first();

            if ($existingConflict) {
                continue;
            }

            DB::table('conflicts')->insert([
                'uuid' => Str::uuid(),
                'name' => $name,
                'short_name' => Str::limit($name, 97),
                'conflict_type' => $typeMapping[$conflict['type']] ?? 'OTHER',
                'intensity_level' => $conflict['intensity'] ?? 'low',
                'region' => $conflict['region'] ?? null,
                'start_date' => $conflict['start_date'],
                'end_date' => $conflict['end_date'] ?? null,
                'is_active' => $statusMapping[$conflict['status']] ?? false,
                'estimated_casualties' => isset($conflict['casualties_estimate']) ? json_encode(['estimate' => $conflict['casualties_estimate']]) : null,
                'description' => $conflict['description'] ?? null,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('Conflicts seeded: ' . count($conflicts) . ' conflicts');
    }
}
