<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ExtendedEquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Adds 100+ additional equipment items including 50 missiles with detailed descriptions.
     */
    public function run(): void
    {
        $this->seedMissiles();
        $this->seedAdditionalEquipment();
        $this->command->info('Extended equipment seeded successfully.');
    }

    private function seedMissiles(): void
    {
        $categories = DB::table('equipment_categories')->pluck('id', 'slug');
        $countries = DB::table('countries')->pluck('id', 'iso_code');

        $missiles = [
            // =============================================
            // AIR-TO-AIR MISSILES
            // =============================================
            [
                'designation' => 'AIM-120D AMRAAM',
                'nato_designation' => null,
                'common_name' => 'AMRAAM',
                'country_code' => 'US',
                'category_slug' => 'missiles',
                'introduced_year' => 2008,
                'estimated_produced' => 15000,
                'description' => 'Advanced Medium-Range Air-to-Air Missile developed by Hughes Aircraft (now Raytheon) for the US Air Force and Navy. Primary beyond-visual-range missile of NATO air forces. Features active radar homing with inertial navigation mid-course guidance. Recognizable by cylindrical body with four tail fins and four smaller control fins. Combat proven in multiple conflicts. Range exceeds 160km for latest variants.',
                'specifications' => json_encode([
                    'manufacturer' => 'Raytheon',
                    'origin_country' => 'United States',
                    'range_km' => 160,
                    'speed_mach' => 4,
                    'length_m' => 3.66,
                    'diameter_mm' => 178,
                    'weight_kg' => 152,
                    'warhead_kg' => 18,
                    'guidance' => 'Active radar homing + INS',
                    'operators' => 37,
                    'unit_cost_usd' => 400000,
                ]),
            ],
            [
                'designation' => 'AIM-9X Sidewinder',
                'nato_designation' => null,
                'common_name' => 'Sidewinder',
                'country_code' => 'US',
                'category_slug' => 'missiles',
                'introduced_year' => 2003,
                'estimated_produced' => 50000,
                'description' => 'Short-range infrared-guided air-to-air missile, latest variant of the legendary Sidewinder family developed since 1956. Manufactured by Raytheon. Features high off-boresight capability with helmet-mounted cueing, thrust vectoring for extreme maneuverability. Distinctive slim profile with rollerons on tail fins. Used by 40+ nations.',
                'specifications' => json_encode([
                    'manufacturer' => 'Raytheon',
                    'origin_country' => 'United States',
                    'range_km' => 35,
                    'speed_mach' => 2.5,
                    'length_m' => 3,
                    'diameter_mm' => 127,
                    'weight_kg' => 85,
                    'warhead_kg' => 9.4,
                    'guidance' => 'Infrared imaging seeker',
                    'lock_on_after_launch' => true,
                ]),
            ],
            [
                'designation' => 'R-77 Vympel',
                'nato_designation' => 'AA-12 Adder',
                'common_name' => 'R-77',
                'country_code' => 'RU',
                'category_slug' => 'missiles',
                'introduced_year' => 1994,
                'estimated_produced' => 5000,
                'description' => 'Russian medium-range active radar homing air-to-air missile developed by Vympel NPO. Designed to counter AIM-120 AMRAAM. Distinctive lattice tail fins (grid fins) provide high maneuverability. Used on Su-27, Su-30, Su-35, MiG-29, MiG-35. Exported to India, China, Algeria.',
                'specifications' => json_encode([
                    'manufacturer' => 'Vympel NPO',
                    'origin_country' => 'Russia',
                    'range_km' => 110,
                    'speed_mach' => 4.5,
                    'length_m' => 3.6,
                    'diameter_mm' => 200,
                    'weight_kg' => 175,
                    'warhead_kg' => 22,
                    'guidance' => 'Active radar + INS + datalink',
                    'recognition' => 'Distinctive grid tail fins',
                ]),
            ],
            [
                'designation' => 'R-73 Archer',
                'nato_designation' => 'AA-11 Archer',
                'common_name' => 'R-73',
                'country_code' => 'RU',
                'category_slug' => 'missiles',
                'introduced_year' => 1984,
                'estimated_produced' => 20000,
                'description' => 'Russian short-range infrared-guided missile developed by Vympel. Revolutionary at introduction with thrust vectoring and high off-boresight capability. Recognizable by distinctive forward canards and pointed nose. Standard dogfight missile for Russian and export fighters.',
                'specifications' => json_encode([
                    'manufacturer' => 'Vympel NPO',
                    'origin_country' => 'Russia',
                    'range_km' => 30,
                    'speed_mach' => 2.5,
                    'length_m' => 2.9,
                    'diameter_mm' => 170,
                    'weight_kg' => 105,
                    'warhead_kg' => 7.4,
                    'guidance' => 'Infrared + thrust vectoring',
                    'off_boresight_deg' => 45,
                ]),
            ],
            [
                'designation' => 'MBDA Meteor',
                'nato_designation' => null,
                'common_name' => 'Meteor',
                'country_code' => 'GB',
                'category_slug' => 'missiles',
                'introduced_year' => 2016,
                'estimated_produced' => 1500,
                'description' => 'European beyond-visual-range air-to-air missile with ramjet propulsion, developed by MBDA for Eurofighter Typhoon, Gripen, and Rafale. Unique throttleable ducted rocket maintains energy throughout flight envelope. Considered most capable BVR missile currently in service. 100km+ no-escape zone.',
                'specifications' => json_encode([
                    'manufacturer' => 'MBDA',
                    'origin_country' => 'UK/France/Germany/Italy/Spain/Sweden',
                    'range_km' => 200,
                    'speed_mach' => 4,
                    'length_m' => 3.65,
                    'diameter_mm' => 178,
                    'weight_kg' => 185,
                    'warhead_kg' => 25,
                    'guidance' => 'Active radar + INS + datalink',
                    'propulsion' => 'Throttleable ducted rocket (ramjet)',
                ]),
            ],
            [
                'designation' => 'PL-15',
                'nato_designation' => null,
                'common_name' => 'PL-15',
                'country_code' => 'CN',
                'category_slug' => 'missiles',
                'introduced_year' => 2016,
                'estimated_produced' => 2000,
                'description' => 'Chinese long-range air-to-air missile developed by CATIC/Luoyang. Features dual-pulse rocket motor for extended range. Primary armament for J-20, J-16, J-10C. Believed to have range exceeding AIM-120D. Poses significant challenge to AWACS and tanker aircraft.',
                'specifications' => json_encode([
                    'manufacturer' => 'CATIC/Luoyang',
                    'origin_country' => 'China',
                    'range_km' => 200,
                    'speed_mach' => 4,
                    'length_m' => 4,
                    'diameter_mm' => 203,
                    'weight_kg' => 210,
                    'guidance' => 'Active radar + INS + datalink',
                    'dual_pulse_motor' => true,
                ]),
            ],
            [
                'designation' => 'IRIS-T',
                'nato_designation' => null,
                'common_name' => 'IRIS-T',
                'country_code' => 'DE',
                'category_slug' => 'missiles',
                'introduced_year' => 2005,
                'estimated_produced' => 4000,
                'description' => 'German short-range infrared-guided missile developed by Diehl Defence. Replacement for AIM-9 Sidewinder. Features imaging infrared seeker with exceptional IRCCM. Thrust vector control for high agility. Also adapted for surface-to-air role (IRIS-T SLM/SLS). Used by 13 nations.',
                'specifications' => json_encode([
                    'manufacturer' => 'Diehl Defence',
                    'origin_country' => 'Germany',
                    'range_km' => 25,
                    'speed_mach' => 3,
                    'length_m' => 2.94,
                    'diameter_mm' => 127,
                    'weight_kg' => 89,
                    'warhead_kg' => 11.4,
                    'guidance' => 'Imaging infrared',
                    'lock_on_after_launch' => true,
                ]),
            ],
            [
                'designation' => 'MICA IR/EM',
                'nato_designation' => null,
                'common_name' => 'MICA',
                'country_code' => 'FR',
                'category_slug' => 'missiles',
                'introduced_year' => 1996,
                'estimated_produced' => 6000,
                'description' => 'French multi-role air-to-air missile by MBDA in two versions: IR (infrared) and EM (electromagnetic/radar). Interchangeable seekers on same airframe. Rafale primary armament. Unique thrust-vectoring with four jetavators. Fire-and-forget with datalink update capability.',
                'specifications' => json_encode([
                    'manufacturer' => 'MBDA France',
                    'origin_country' => 'France',
                    'range_km' => 80,
                    'speed_mach' => 4,
                    'length_m' => 3.1,
                    'diameter_mm' => 160,
                    'weight_kg' => 112,
                    'warhead_kg' => 12,
                    'guidance' => 'Active radar (EM) or Infrared imaging (IR)',
                    'thrust_vectoring' => true,
                ]),
            ],

            // =============================================
            // ANTI-SHIP MISSILES
            // =============================================
            [
                'designation' => 'RGM-84 Harpoon',
                'nato_designation' => null,
                'common_name' => 'Harpoon',
                'country_code' => 'US',
                'category_slug' => 'cruise',
                'introduced_year' => 1977,
                'estimated_produced' => 7500,
                'description' => 'American all-weather, over-the-horizon anti-ship missile developed by McDonnell Douglas (now Boeing). Sea-skimming cruise profile. Ship, sub, and air-launched variants. Standard Western anti-ship missile for 40+ years. Distinctive cylindrical body with pop-out wings and ventral air intake.',
                'specifications' => json_encode([
                    'manufacturer' => 'Boeing',
                    'origin_country' => 'United States',
                    'range_km' => 240,
                    'speed' => 'Mach 0.85 (subsonic)',
                    'length_m' => 4.6,
                    'diameter_mm' => 343,
                    'weight_kg' => 691,
                    'warhead_kg' => 221,
                    'guidance' => 'Active radar + GPS/INS',
                    'flight_profile' => 'Sea-skimming',
                    'operators' => 30,
                ]),
            ],
            [
                'designation' => 'AGM-158C LRASM',
                'nato_designation' => null,
                'common_name' => 'LRASM',
                'country_code' => 'US',
                'category_slug' => 'cruise',
                'introduced_year' => 2018,
                'estimated_produced' => 500,
                'description' => 'Long Range Anti-Ship Missile developed by Lockheed Martin. Stealthy successor to Harpoon with autonomous targeting using onboard sensors and AI. Designed for contested A2/AD environments. Multi-mode seeker with passive RF, active radar, and imaging infrared.',
                'specifications' => json_encode([
                    'manufacturer' => 'Lockheed Martin',
                    'origin_country' => 'United States',
                    'range_km' => 900,
                    'speed' => 'High subsonic',
                    'length_m' => 4.27,
                    'weight_kg' => 1020,
                    'warhead_kg' => 454,
                    'guidance' => 'Autonomous multi-mode (passive RF, active radar, IIR)',
                    'stealth' => true,
                    'unit_cost_usd' => 3000000,
                ]),
            ],
            [
                'designation' => 'P-800 Oniks',
                'nato_designation' => 'SS-N-26 Strobile',
                'common_name' => 'Oniks/Yakhont',
                'country_code' => 'RU',
                'category_slug' => 'cruise',
                'introduced_year' => 2002,
                'estimated_produced' => 1500,
                'description' => 'Russian supersonic anti-ship cruise missile developed by NPO Mashinostroyeniya. Export version called Yakhont, basis for BrahMos. Ramjet propulsion enables sustained Mach 2.5+ flight. Ship, coastal, and submarine-launched. High kinetic energy makes interception difficult.',
                'specifications' => json_encode([
                    'manufacturer' => 'NPO Mashinostroyeniya',
                    'origin_country' => 'Russia',
                    'range_km' => 500,
                    'speed_mach' => 2.6,
                    'length_m' => 8.9,
                    'diameter_mm' => 670,
                    'weight_kg' => 3000,
                    'warhead_kg' => 250,
                    'guidance' => 'Active/passive radar + INS',
                    'propulsion' => 'Ramjet',
                ]),
            ],
            [
                'designation' => 'Kh-35U',
                'nato_designation' => 'AS-20 Kayak',
                'common_name' => 'Uran',
                'country_code' => 'RU',
                'category_slug' => 'cruise',
                'introduced_year' => 2003,
                'estimated_produced' => 2000,
                'description' => 'Russian subsonic sea-skimming anti-ship missile developed by Tactical Missiles Corporation. Often called "Harpoonski" for similar role to Harpoon. Upgraded Kh-35U features extended range and improved guidance. Ship, coastal, and air-launched variants.',
                'specifications' => json_encode([
                    'manufacturer' => 'Tactical Missiles Corporation',
                    'origin_country' => 'Russia',
                    'range_km' => 260,
                    'speed' => 'Mach 0.9',
                    'length_m' => 4.4,
                    'diameter_mm' => 420,
                    'weight_kg' => 670,
                    'warhead_kg' => 145,
                    'guidance' => 'Active radar + INS + GLONASS',
                    'flight_profile' => 'Sea-skimming 3-5m',
                ]),
            ],
            [
                'designation' => 'NSM Naval Strike Missile',
                'nato_designation' => null,
                'common_name' => 'NSM',
                'country_code' => 'NO',
                'category_slug' => 'cruise',
                'introduced_year' => 2012,
                'estimated_produced' => 800,
                'description' => 'Norwegian stealth anti-ship missile developed by Kongsberg. Fifth-generation missile with passive imaging infrared seeker for terminal guidance. Low radar cross-section composite construction. Selected by US Navy for littoral combat ships. Can strike both naval and land targets.',
                'specifications' => json_encode([
                    'manufacturer' => 'Kongsberg Defence',
                    'origin_country' => 'Norway',
                    'range_km' => 185,
                    'speed' => 'High subsonic',
                    'length_m' => 3.96,
                    'weight_kg' => 407,
                    'warhead_kg' => 125,
                    'guidance' => 'Imaging infrared + INS + GPS + terrain reference',
                    'stealth' => true,
                    'operators' => ['Norway', 'Poland', 'USA', 'Germany', 'Malaysia'],
                ]),
            ],
            [
                'designation' => 'Exocet MM40 Block 3',
                'nato_designation' => null,
                'common_name' => 'Exocet',
                'country_code' => 'FR',
                'category_slug' => 'cruise',
                'introduced_year' => 2008,
                'estimated_produced' => 3500,
                'description' => 'French sea-skimming anti-ship missile by MBDA, famous from Falklands War. Block 3 features GPS waypoint navigation, land attack capability, and increased range. Distinctive cruciform wings. One of most widely exported anti-ship missiles with 35+ operators.',
                'specifications' => json_encode([
                    'manufacturer' => 'MBDA',
                    'origin_country' => 'France',
                    'range_km' => 200,
                    'speed' => 'Mach 0.93',
                    'length_m' => 5.8,
                    'diameter_mm' => 350,
                    'weight_kg' => 870,
                    'warhead_kg' => 165,
                    'guidance' => 'INS + GPS + active radar',
                    'operators' => 35,
                ]),
            ],
            [
                'designation' => 'YJ-18',
                'nato_designation' => 'CH-SS-NX-13',
                'common_name' => 'Eagle Strike 18',
                'country_code' => 'CN',
                'category_slug' => 'cruise',
                'introduced_year' => 2015,
                'estimated_produced' => 1000,
                'description' => 'Chinese anti-ship cruise missile with unique two-stage profile. Cruises subsonically, then accelerates to Mach 3 for terminal attack. Derived from Russian 3M54 Kalibr. Primary anti-ship weapon of PLAN Type 052D destroyers and Type 055 cruisers.',
                'specifications' => json_encode([
                    'manufacturer' => 'China Aerospace Science and Industry Corporation',
                    'origin_country' => 'China',
                    'range_km' => 540,
                    'speed' => 'Mach 0.8 cruise / Mach 3 terminal',
                    'weight_kg' => 2000,
                    'warhead_kg' => 300,
                    'guidance' => 'Active radar + INS + satellite',
                    'two_stage' => true,
                ]),
            ],

            // =============================================
            // SURFACE-TO-AIR MISSILES
            // =============================================
            [
                'designation' => 'MIM-104 PAC-3 MSE',
                'nato_designation' => null,
                'common_name' => 'Patriot PAC-3 MSE',
                'country_code' => 'US',
                'category_slug' => 'sam',
                'introduced_year' => 2015,
                'estimated_produced' => 1500,
                'description' => 'Most advanced Patriot interceptor variant developed by Lockheed Martin. Missile Segment Enhancement provides 50% more range and altitude than PAC-3. Hit-to-kill technology for ballistic missile defense. Distinguished by smaller size allowing 16 per launcher vs 4 PAC-2.',
                'specifications' => json_encode([
                    'manufacturer' => 'Lockheed Martin',
                    'origin_country' => 'United States',
                    'range_km' => 35,
                    'altitude_km' => 35,
                    'speed_mach' => 5,
                    'length_m' => 5.2,
                    'weight_kg' => 312,
                    'guidance' => 'Active radar + hit-to-kill',
                    'targets' => 'Ballistic missiles, cruise missiles, aircraft',
                    'interceptors_per_launcher' => 16,
                ]),
            ],
            [
                'designation' => 'THAAD',
                'nato_designation' => null,
                'common_name' => 'THAAD',
                'country_code' => 'US',
                'category_slug' => 'sam',
                'introduced_year' => 2008,
                'estimated_produced' => 200,
                'description' => 'Terminal High Altitude Area Defense system by Lockheed Martin. Designed to intercept ballistic missiles in terminal phase both inside and outside atmosphere. Hit-to-kill interceptor with no explosive warhead. Controversial deployment in South Korea due to Chinese objections.',
                'specifications' => json_encode([
                    'manufacturer' => 'Lockheed Martin',
                    'origin_country' => 'United States',
                    'range_km' => 200,
                    'altitude_km' => 150,
                    'speed_mach' => 8,
                    'length_m' => 6.17,
                    'weight_kg' => 900,
                    'guidance' => 'Infrared seeker + hit-to-kill',
                    'targets' => 'Short and medium range ballistic missiles',
                    'interceptors_per_launcher' => 8,
                    'unit_cost_usd' => 800000000,
                ]),
            ],
            [
                'designation' => 'S-300PMU-2 Favorit',
                'nato_designation' => 'SA-20B Gargoyle',
                'common_name' => 'S-300PMU-2',
                'country_code' => 'RU',
                'category_slug' => 'sam',
                'introduced_year' => 1997,
                'estimated_produced' => 50,
                'description' => 'Advanced Russian long-range surface-to-air missile system by Almaz-Antey. Export version of S-300PM2. Can engage aircraft, cruise missiles, and ballistic missiles. Recognizable by cylindrical 48N6E2 missiles in quad canisters on 5P85 TEL. Operated by China, Greece, Iran.',
                'specifications' => json_encode([
                    'manufacturer' => 'Almaz-Antey',
                    'origin_country' => 'Russia',
                    'range_km' => 200,
                    'altitude_km' => 27,
                    'missiles_per_battery' => 48,
                    'engagement_capability' => '36 targets / 72 missiles simultaneously',
                    'missile_type' => '48N6E2',
                    'guidance' => 'Semi-active radar + TVM',
                ]),
            ],
            [
                'designation' => 'HQ-9B',
                'nato_designation' => 'CSA-9',
                'common_name' => 'Hong Qi 9B',
                'country_code' => 'CN',
                'category_slug' => 'sam',
                'introduced_year' => 2017,
                'estimated_produced' => 100,
                'description' => 'Chinese long-range SAM developed by CPMIEC, evolved from S-300 technology. Features improved anti-ballistic missile capability. Export version FD-2000 selected by Turkey in controversial deal. Naval variant HHQ-9 on Type 052C/D destroyers.',
                'specifications' => json_encode([
                    'manufacturer' => 'CPMIEC',
                    'origin_country' => 'China',
                    'range_km' => 250,
                    'altitude_km' => 30,
                    'speed_mach' => 4.2,
                    'weight_kg' => 1300,
                    'guidance' => 'Active radar homing',
                    'targets' => 'Aircraft, cruise missiles, tactical ballistic missiles',
                ]),
            ],
            [
                'designation' => '9K37M1 Buk-M1',
                'nato_designation' => 'SA-11 Gadfly',
                'common_name' => 'Buk-M1',
                'country_code' => 'RU',
                'category_slug' => 'sam',
                'introduced_year' => 1980,
                'estimated_produced' => 500,
                'description' => 'Soviet/Russian medium-range SAM by Almaz-Antey. Notorious for shooting down Malaysia Airlines MH17 over Ukraine in 2014. Self-propelled on tracked chassis. Recognizable 9M38 missiles with distinctive nose cone. Upgraded versions still in widespread use.',
                'specifications' => json_encode([
                    'manufacturer' => 'Almaz-Antey',
                    'origin_country' => 'Russia/USSR',
                    'range_km' => 35,
                    'altitude_km' => 22,
                    'speed_mach' => 3,
                    'length_m' => 5.5,
                    'weight_kg' => 690,
                    'warhead_kg' => 70,
                    'guidance' => 'Semi-active radar',
                    'missiles_per_telar' => 4,
                ]),
            ],
            [
                'designation' => 'Tor-M2',
                'nato_designation' => 'SA-15 Gauntlet',
                'common_name' => 'Tor-M2',
                'country_code' => 'RU',
                'category_slug' => 'sam',
                'introduced_year' => 2012,
                'estimated_produced' => 150,
                'description' => 'Russian short-range tactical SAM by IEMZ Kupol. All-in-one system with radar, command, and 16 missiles on single tracked vehicle. Designed to protect armored formations from precision-guided munitions, cruise missiles, and drones. Reaction time under 10 seconds.',
                'specifications' => json_encode([
                    'manufacturer' => 'IEMZ Kupol',
                    'origin_country' => 'Russia',
                    'range_km' => 16,
                    'altitude_km' => 12,
                    'missiles' => 16,
                    'simultaneous_targets' => 4,
                    'reaction_time_sec' => 8,
                    'guidance' => 'Radio command',
                    'mobility' => 'Tracked, all-terrain',
                ]),
            ],
            [
                'designation' => 'NASAMS 3',
                'nato_designation' => null,
                'common_name' => 'NASAMS',
                'country_code' => 'NO',
                'category_slug' => 'sam',
                'introduced_year' => 2019,
                'estimated_produced' => 200,
                'description' => 'Norwegian/American Advanced Surface-to-Air Missile System developed by Kongsberg and Raytheon. Uses AMRAAM air-to-air missiles in ground-launched role. Highly mobile, network-centric. Provided to Ukraine for air defense. Guards Washington DC airspace.',
                'specifications' => json_encode([
                    'manufacturer' => 'Kongsberg/Raytheon',
                    'origin_country' => 'Norway/USA',
                    'range_km' => 40,
                    'altitude_km' => 21,
                    'missiles_per_launcher' => 6,
                    'missile_types' => ['AMRAAM', 'AMRAAM-ER', 'AIM-9X'],
                    'guidance' => 'Active radar (AMRAAM)',
                    'operators' => ['Norway', 'USA', 'Finland', 'Spain', 'Ukraine', 'Lithuania'],
                ]),
            ],
        ];

        foreach ($missiles as $item) {
            $countryId = $countries[$item['country_code']] ?? null;
            $categoryId = $categories[$item['category_slug']] ?? null;

            if (!$countryId || !$categoryId) {
                $this->command->warn("Skipping {$item['designation']}: Missing country or category");
                continue;
            }

            DB::table('military_equipment')->updateOrInsert(
                ['designation' => $item['designation']],
                [
                    'uuid' => Str::uuid(),
                    'designation' => $item['designation'],
                    'nato_designation' => $item['nato_designation'],
                    'common_name' => $item['common_name'],
                    'country_id' => $countryId,
                    'category_id' => $categoryId,
                    'introduced_year' => $item['introduced_year'],
                    'estimated_produced' => $item['estimated_produced'],
                    'description' => $item['description'],
                    'specifications' => $item['specifications'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

        $this->command->info('First batch of missiles seeded (22 items)');
    }

    private function seedAdditionalEquipment(): void
    {
        $categories = DB::table('equipment_categories')->pluck('id', 'slug');
        $countries = DB::table('countries')->pluck('id', 'iso_code');

        $moreMissiles = [
            // =============================================
            // ANTI-TANK GUIDED MISSILES
            // =============================================
            [
                'designation' => 'BGM-71 TOW 2B',
                'nato_designation' => null,
                'common_name' => 'TOW',
                'country_code' => 'US',
                'category_slug' => 'atgm',
                'introduced_year' => 1991,
                'estimated_produced' => 700000,
                'description' => 'Tube-launched Optically-tracked Wire-guided missile developed by Hughes (now Raytheon). Most widely used ATGM in Western arsenals. TOW 2B variant features tandem warhead for top-attack against ERA-protected tanks. Wire-guided requiring operator to track target throughout flight. Recognizable by large missile tube and tripod launcher.',
                'specifications' => json_encode([
                    'manufacturer' => 'Raytheon',
                    'origin_country' => 'United States',
                    'range_m' => 4200,
                    'speed_ms' => 320,
                    'length_m' => 1.17,
                    'diameter_mm' => 152,
                    'weight_kg' => 22.6,
                    'penetration_mm' => 900,
                    'guidance' => 'Wire-guided SACLOS',
                    'warhead' => 'Tandem shaped charge',
                    'operators' => 40,
                ]),
            ],
            [
                'designation' => 'FGM-172 SRAW',
                'nato_designation' => null,
                'common_name' => 'SRAW',
                'country_code' => 'US',
                'category_slug' => 'atgm',
                'introduced_year' => 2002,
                'estimated_produced' => 10000,
                'description' => 'Short-Range Assault Weapon developed by Lockheed Martin. Predator variant (SRAW-MPV) features top-attack profile. Fire-and-forget inertial guidance compensates for target movement. Designed for urban combat with confined space capability. Soft-launch allows firing from enclosures.',
                'specifications' => json_encode([
                    'manufacturer' => 'Lockheed Martin',
                    'origin_country' => 'United States',
                    'range_m' => 600,
                    'weight_kg' => 9.5,
                    'penetration_mm' => 450,
                    'guidance' => 'Inertial with magnetic target detection',
                    'flight_profile' => 'Top-attack',
                    'soft_launch' => true,
                ]),
            ],
            [
                'designation' => '9M133FM-3 Kornet-EM',
                'nato_designation' => 'AT-14 Spriggan',
                'common_name' => 'Kornet-EM',
                'country_code' => 'RU',
                'category_slug' => 'atgm',
                'introduced_year' => 2012,
                'estimated_produced' => 25000,
                'description' => 'Enhanced Russian ATGM by KBP Instrument Design Bureau. Extended range variant of Kornet with thermobaric warhead option. Laser beam-riding guidance immune to jamming. Can engage helicopters and low-flying aircraft. Proven effective against Abrams and Merkava tanks in various conflicts.',
                'specifications' => json_encode([
                    'manufacturer' => 'KBP Instrument Design Bureau',
                    'origin_country' => 'Russia',
                    'range_m' => 10000,
                    'speed_ms' => 320,
                    'length_m' => 1.21,
                    'diameter_mm' => 152,
                    'weight_kg' => 33,
                    'penetration_mm' => 1300,
                    'guidance' => 'Laser beam-riding SACLOS',
                    'warhead_options' => ['Tandem HEAT', 'Thermobaric'],
                ]),
            ],
            [
                'designation' => '9M123 Khrizantema',
                'nato_designation' => 'AT-15 Springer',
                'common_name' => 'Khrizantema',
                'country_code' => 'RU',
                'category_slug' => 'atgm',
                'introduced_year' => 2005,
                'estimated_produced' => 5000,
                'description' => 'Russian supersonic ATGM capable of engaging targets in day, night, and adverse weather. Features both radar and laser guidance options. Vehicle-mounted on BMP-3 chassis (9P157). Only ATGM with millimeter-wave radar for fire-and-forget in all conditions.',
                'specifications' => json_encode([
                    'manufacturer' => 'KBP Instrument Design Bureau',
                    'origin_country' => 'Russia',
                    'range_m' => 6000,
                    'speed_ms' => 450,
                    'penetration_mm' => 1200,
                    'guidance' => 'MMW radar or laser beam-riding',
                    'supersonic' => true,
                    'all_weather' => true,
                ]),
            ],
            [
                'designation' => 'MILAN ER',
                'nato_designation' => null,
                'common_name' => 'MILAN',
                'country_code' => 'FR',
                'category_slug' => 'atgm',
                'introduced_year' => 2000,
                'estimated_produced' => 350000,
                'description' => 'Franco-German anti-tank missile developed by Euromissile. MILAN ER (Extended Response) features tandem warhead and increased range. Wire-guided SACLOS system. One of most widely exported ATGMs in history with 40+ operators. Still in active service worldwide.',
                'specifications' => json_encode([
                    'manufacturer' => 'MBDA',
                    'origin_country' => 'France/Germany',
                    'range_m' => 3000,
                    'speed_ms' => 200,
                    'weight_kg' => 7.1,
                    'penetration_mm' => 1000,
                    'guidance' => 'Wire-guided SACLOS',
                    'operators' => 40,
                ]),
            ],
            [
                'designation' => 'NLAW',
                'nato_designation' => null,
                'common_name' => 'NLAW',
                'country_code' => 'GB',
                'category_slug' => 'atgm',
                'introduced_year' => 2009,
                'estimated_produced' => 50000,
                'description' => 'Next generation Light Anti-tank Weapon developed by Saab Bofors Dynamics and Thales Air Defence. Single-use, shoulder-fired with predicted line-of-sight guidance. Features top-attack mode against tanks and direct attack for structures. Extensively supplied to Ukraine with proven combat success against Russian armor.',
                'specifications' => json_encode([
                    'manufacturer' => 'Saab Bofors Dynamics / Thales',
                    'origin_country' => 'UK/Sweden',
                    'range_m' => 800,
                    'weight_kg' => 12.5,
                    'penetration_mm' => 500,
                    'guidance' => 'PLOS (Predicted Line Of Sight)',
                    'flight_profile' => 'Top-attack or direct',
                    'single_use' => true,
                    'soft_launch' => true,
                ]),
            ],
            [
                'designation' => 'HJ-12 Red Arrow',
                'nato_designation' => null,
                'common_name' => 'Red Arrow 12',
                'country_code' => 'CN',
                'category_slug' => 'atgm',
                'introduced_year' => 2014,
                'estimated_produced' => 10000,
                'description' => 'Chinese fire-and-forget ATGM with imaging infrared seeker, similar to Javelin. Man-portable with top-attack capability. Represents significant advancement in Chinese ATGM technology. Export designated as HJ-12E.',
                'specifications' => json_encode([
                    'manufacturer' => 'NORINCO',
                    'origin_country' => 'China',
                    'range_m' => 4000,
                    'weight_kg' => 22,
                    'penetration_mm' => 1100,
                    'guidance' => 'Imaging infrared fire-and-forget',
                    'flight_profile' => 'Top-attack',
                    'soft_launch' => true,
                ]),
            ],
            [
                'designation' => 'Brimstone 2',
                'nato_designation' => null,
                'common_name' => 'Brimstone',
                'country_code' => 'GB',
                'category_slug' => 'atgm',
                'introduced_year' => 2016,
                'estimated_produced' => 3000,
                'description' => 'British air-launched precision strike missile by MBDA. Dual-mode millimeter wave radar and semi-active laser seeker. Fire-and-forget with salvo capability for multiple simultaneous engagements. Extensively used in Syria/Iraq and supplied to Ukraine. Can be ground-launched.',
                'specifications' => json_encode([
                    'manufacturer' => 'MBDA',
                    'origin_country' => 'United Kingdom',
                    'range_km' => 60,
                    'speed' => 'Mach 1.3',
                    'length_m' => 1.8,
                    'weight_kg' => 50,
                    'warhead_kg' => 6.2,
                    'guidance' => 'MMW radar + semi-active laser',
                    'fire_and_forget' => true,
                ]),
            ],

            // =============================================
            // MANPADS (Man-Portable Air-Defense Systems)
            // =============================================
            [
                'designation' => '9K38 Igla',
                'nato_designation' => 'SA-18 Grouse',
                'common_name' => 'Igla',
                'country_code' => 'RU',
                'category_slug' => 'manpads',
                'introduced_year' => 1983,
                'estimated_produced' => 50000,
                'description' => 'Soviet/Russian man-portable SAM developed by KB Mashinostroyeniya. Improved successor to Strela series. Features dual-band infrared seeker resistant to flares. Distinctive green launch tube. Widely exported and produced under license. Used by irregular forces worldwide.',
                'specifications' => json_encode([
                    'manufacturer' => 'KB Mashinostroyeniya',
                    'origin_country' => 'Russia',
                    'range_km' => 5.2,
                    'altitude_m' => 3500,
                    'speed_mach' => 2,
                    'weight_kg' => 17.9,
                    'warhead_kg' => 1.17,
                    'guidance' => 'Dual-band IR seeker',
                    'operators' => 50,
                ]),
            ],
            [
                'designation' => '9K333 Verba',
                'nato_designation' => 'SA-25',
                'common_name' => 'Verba',
                'country_code' => 'RU',
                'category_slug' => 'manpads',
                'introduced_year' => 2015,
                'estimated_produced' => 5000,
                'description' => 'Most advanced Russian MANPADS by KBM Kolomna. Features three-band infrared seeker (UV, near-IR, mid-IR) for exceptional flare rejection. Friend-or-foe identification system. Improved range over Igla-S. Limited export due to proliferation concerns.',
                'specifications' => json_encode([
                    'manufacturer' => 'KBM Kolomna',
                    'origin_country' => 'Russia',
                    'range_km' => 6.4,
                    'altitude_m' => 4500,
                    'speed_mach' => 2.3,
                    'weight_kg' => 17.2,
                    'warhead_kg' => 2.5,
                    'guidance' => 'Three-band IR seeker',
                    'iff' => true,
                ]),
            ],
            [
                'designation' => 'Mistral 3',
                'nato_designation' => null,
                'common_name' => 'Mistral',
                'country_code' => 'FR',
                'category_slug' => 'manpads',
                'introduced_year' => 2018,
                'estimated_produced' => 15000,
                'description' => 'French MANPADS developed by MBDA. Mistral 3 features improved imaging infrared seeker, datalink, and proximity fuze. Can be man-portable, vehicle-mounted, or ship-mounted. High kill probability against modern aircraft and UAVs.',
                'specifications' => json_encode([
                    'manufacturer' => 'MBDA',
                    'origin_country' => 'France',
                    'range_km' => 7.5,
                    'altitude_m' => 5000,
                    'speed_mach' => 2.6,
                    'weight_kg' => 19,
                    'warhead_kg' => 2.95,
                    'guidance' => 'Imaging IR with proximity fuze',
                    'operators' => 30,
                ]),
            ],
            [
                'designation' => 'RBS 70 NG',
                'nato_designation' => null,
                'common_name' => 'RBS 70',
                'country_code' => 'SE',
                'category_slug' => 'manpads',
                'introduced_year' => 2011,
                'estimated_produced' => 20000,
                'description' => 'Swedish laser beam-riding SAM by Saab Bofors Dynamics. Unique guidance system immune to IR countermeasures since missile has no seeker. Tripod-mounted with optional thermal sight. Bolide missile variant for enhanced anti-helicopter capability.',
                'specifications' => json_encode([
                    'manufacturer' => 'Saab Bofors Dynamics',
                    'origin_country' => 'Sweden',
                    'range_km' => 8,
                    'altitude_m' => 5000,
                    'speed_mach' => 2.5,
                    'weight_kg' => 87,
                    'guidance' => 'Laser beam-riding',
                    'jam_resistant' => true,
                    'operators' => 19,
                ]),
            ],
            [
                'designation' => 'QW-2 Vanguard',
                'nato_designation' => null,
                'common_name' => 'QW-2',
                'country_code' => 'CN',
                'category_slug' => 'manpads',
                'introduced_year' => 2002,
                'estimated_produced' => 10000,
                'description' => 'Chinese MANPADS with cooled infrared seeker for improved sensitivity. Similar performance to Stinger. Exported to multiple countries in Asia and Africa. Recognizable by distinctive grip stock and cylindrical launch tube.',
                'specifications' => json_encode([
                    'manufacturer' => 'CPMIEC',
                    'origin_country' => 'China',
                    'range_km' => 6,
                    'altitude_m' => 4000,
                    'speed_mach' => 2,
                    'weight_kg' => 18,
                    'guidance' => 'Cooled IR seeker',
                ]),
            ],
            [
                'designation' => 'Piorun',
                'nato_designation' => null,
                'common_name' => 'Piorun',
                'country_code' => 'PL',
                'category_slug' => 'manpads',
                'introduced_year' => 2019,
                'estimated_produced' => 3000,
                'description' => 'Polish MANPADS developed by Mesko S.A., based on Igla but with new seeker and proximity fuze. Name means "Thunderbolt" in Polish. Enhanced resistance to countermeasures. Supplied to Ukraine where it has proven highly effective.',
                'specifications' => json_encode([
                    'manufacturer' => 'Mesko S.A.',
                    'origin_country' => 'Poland',
                    'range_km' => 6.5,
                    'altitude_m' => 4000,
                    'speed_mach' => 2.2,
                    'weight_kg' => 16.5,
                    'warhead_kg' => 1.8,
                    'guidance' => 'Dual-band IR with proximity fuze',
                ]),
            ],

            // =============================================
            // CRUISE MISSILES (Additional)
            // =============================================
            [
                'designation' => 'BGM-109 Tomahawk Block V',
                'nato_designation' => null,
                'common_name' => 'Tomahawk',
                'country_code' => 'US',
                'category_slug' => 'cruise',
                'introduced_year' => 2021,
                'estimated_produced' => 4000,
                'description' => 'American long-range cruise missile developed by General Dynamics (now Raytheon). Block V adds maritime moving target capability. Ship and submarine-launched. Terrain-hugging flight profile with TERCOM/DSMAC guidance. Combat proven in Iraq, Yugoslavia, Afghanistan, Syria, Yemen.',
                'specifications' => json_encode([
                    'manufacturer' => 'Raytheon',
                    'origin_country' => 'United States',
                    'range_km' => 2500,
                    'speed' => 'Mach 0.74',
                    'length_m' => 5.56,
                    'diameter_mm' => 518,
                    'weight_kg' => 1590,
                    'warhead_kg' => 450,
                    'guidance' => 'INS + GPS + TERCOM + DSMAC + datalink',
                    'accuracy_m' => 5,
                    'unit_cost_usd' => 2000000,
                ]),
            ],
            [
                'designation' => 'AGM-86C CALCM',
                'nato_designation' => null,
                'common_name' => 'CALCM',
                'country_code' => 'US',
                'category_slug' => 'cruise',
                'introduced_year' => 1991,
                'estimated_produced' => 1700,
                'description' => 'Conventional Air-Launched Cruise Missile converted from nuclear ALCM. B-52 launched standoff weapon. GPS-aided guidance for precision strike. Used extensively in Desert Storm, Kosovo, and Iraq. Being replaced by JASSM.',
                'specifications' => json_encode([
                    'manufacturer' => 'Boeing',
                    'origin_country' => 'United States',
                    'range_km' => 1200,
                    'speed' => 'Mach 0.73',
                    'length_m' => 6.32,
                    'weight_kg' => 1950,
                    'warhead_kg' => 900,
                    'guidance' => 'INS + GPS + TERCOM',
                    'platform' => 'B-52H',
                ]),
            ],
            [
                'designation' => 'AGM-158B JASSM-ER',
                'nato_designation' => null,
                'common_name' => 'JASSM-ER',
                'country_code' => 'US',
                'category_slug' => 'cruise',
                'introduced_year' => 2014,
                'estimated_produced' => 2500,
                'description' => 'Joint Air-to-Surface Standoff Missile Extended Range by Lockheed Martin. Stealthy cruise missile with precision strike capability. Extended range variant with larger fuel tank. Equips F-15E, F-16, B-1B, B-52, F-35. Low observable airframe.',
                'specifications' => json_encode([
                    'manufacturer' => 'Lockheed Martin',
                    'origin_country' => 'United States',
                    'range_km' => 1000,
                    'speed' => 'High subsonic',
                    'length_m' => 4.27,
                    'weight_kg' => 1020,
                    'warhead_kg' => 450,
                    'guidance' => 'INS + GPS + IIR terminal',
                    'stealth' => true,
                    'unit_cost_usd' => 1400000,
                ]),
            ],
            [
                'designation' => '3M14 Kalibr',
                'nato_designation' => 'SS-N-30A Sagaris',
                'common_name' => 'Kalibr',
                'country_code' => 'RU',
                'category_slug' => 'cruise',
                'introduced_year' => 2012,
                'estimated_produced' => 2000,
                'description' => 'Russian ship and submarine-launched cruise missile family by NPO Novator. Land-attack variant used extensively against Ukraine. Features terrain-following flight and terminal supersonic sprint. Launched from Kilo-class submarines and Buyan-M corvettes in Caspian Sea strikes.',
                'specifications' => json_encode([
                    'manufacturer' => 'NPO Novator',
                    'origin_country' => 'Russia',
                    'range_km' => 2500,
                    'speed' => 'Mach 0.8 cruise / Mach 2.9 terminal',
                    'length_m' => 8.9,
                    'weight_kg' => 2300,
                    'warhead_kg' => 450,
                    'guidance' => 'INS + GLONASS + TERCOM + DSMAC',
                    'platforms' => ['Ships', 'Submarines', 'Coastal'],
                ]),
            ],
            [
                'designation' => 'Taurus KEPD 350',
                'nato_designation' => null,
                'common_name' => 'Taurus',
                'country_code' => 'DE',
                'category_slug' => 'cruise',
                'introduced_year' => 2005,
                'estimated_produced' => 600,
                'description' => 'German-Swedish air-launched cruise missile by Taurus Systems (MBDA/Saab). KEPD = Kinetic Energy Penetrator and Destroyer. Bunker-busting MEPHISTO warhead with tandem penetrator. Stealthy design with terrain-following. Used by Luftwaffe Tornados and Spanish EF-18.',
                'specifications' => json_encode([
                    'manufacturer' => 'Taurus Systems (MBDA/Saab)',
                    'origin_country' => 'Germany/Sweden',
                    'range_km' => 500,
                    'speed' => 'Mach 0.95',
                    'length_m' => 5.1,
                    'weight_kg' => 1400,
                    'warhead_kg' => 481,
                    'guidance' => 'INS + GPS + TERCOM + IIR',
                    'warhead_type' => 'MEPHISTO tandem penetrator',
                ]),
            ],

            // =============================================
            // BALLISTIC MISSILES (Additional)
            // =============================================
            [
                'designation' => 'DF-26',
                'nato_designation' => 'CSS-18',
                'common_name' => 'DF-26 Guam Killer',
                'country_code' => 'CN',
                'category_slug' => 'ballistic',
                'introduced_year' => 2018,
                'estimated_produced' => 200,
                'description' => 'Chinese intermediate-range ballistic missile capable of nuclear or conventional strikes. Dual capable against land and naval targets. Nicknamed "Guam Killer" for ability to strike US Pacific bases. Mobile road-launched from TEL. Maneuvering warhead for terminal accuracy.',
                'specifications' => json_encode([
                    'manufacturer' => 'CASIC',
                    'origin_country' => 'China',
                    'range_km' => 4000,
                    'speed_mach' => 18,
                    'length_m' => 14,
                    'weight_tonnes' => 20,
                    'warhead' => 'Nuclear or conventional (1800kg)',
                    'guidance' => 'INS + stellar + terminal radar',
                    'accuracy_cep_m' => 30,
                    'mobile' => true,
                ]),
            ],
            [
                'designation' => 'Shahab-3',
                'nato_designation' => null,
                'common_name' => 'Shahab-3',
                'country_code' => 'IR',
                'category_slug' => 'ballistic',
                'introduced_year' => 2003,
                'estimated_produced' => 300,
                'description' => 'Iranian medium-range ballistic missile based on North Korean Nodong-1. Liquid-fueled with road-mobile TEL. Multiple variants with improved accuracy. Theoretically capable of carrying nuclear warhead. Primary strategic deterrent of Iran.',
                'specifications' => json_encode([
                    'manufacturer' => 'Iran Aerospace Industries Organization',
                    'origin_country' => 'Iran',
                    'range_km' => 2000,
                    'speed_mach' => 10,
                    'length_m' => 16,
                    'weight_tonnes' => 16,
                    'warhead_kg' => 1000,
                    'guidance' => 'INS (improved variants GPS)',
                    'accuracy_cep_m' => 300,
                    'propellant' => 'Liquid',
                ]),
            ],
            [
                'designation' => 'Hyunmoo-4',
                'nato_designation' => null,
                'common_name' => 'Hyunmoo-4',
                'country_code' => 'KR',
                'category_slug' => 'ballistic',
                'introduced_year' => 2020,
                'estimated_produced' => 100,
                'description' => 'South Korean solid-fuel ballistic missile with 800km+ range. Developed after US lifted missile range restrictions. Features 2-ton conventional warhead. Part of Korea Massive Punishment and Retaliation strategy against North Korea.',
                'specifications' => json_encode([
                    'manufacturer' => 'ADD / LIG Nex1',
                    'origin_country' => 'South Korea',
                    'range_km' => 800,
                    'warhead_tonnes' => 2,
                    'guidance' => 'INS + GPS + terminal',
                    'propellant' => 'Solid',
                    'mobile' => true,
                ]),
            ],
            [
                'designation' => 'Agni-V',
                'nato_designation' => null,
                'common_name' => 'Agni-V',
                'country_code' => 'IN',
                'category_slug' => 'ballistic',
                'introduced_year' => 2018,
                'estimated_produced' => 50,
                'description' => 'Indian intercontinental ballistic missile by DRDO. Three-stage solid-fuel with canisterized road-mobile launch. Can reach all of China. MIRV capable. Part of India nuclear triad with submarine-launched variant under development.',
                'specifications' => json_encode([
                    'manufacturer' => 'DRDO',
                    'origin_country' => 'India',
                    'range_km' => 5500,
                    'speed_mach' => 24,
                    'length_m' => 17.5,
                    'weight_tonnes' => 50,
                    'warhead' => 'Nuclear (1500kg / MIRV capable)',
                    'guidance' => 'Ring laser gyro INS + GPS',
                    'accuracy_cep_m' => 80,
                    'propellant' => 'Solid (3 stage)',
                ]),
            ],
            [
                'designation' => 'RS-28 Sarmat',
                'nato_designation' => 'SS-X-30 Satan 2',
                'common_name' => 'Sarmat',
                'country_code' => 'RU',
                'category_slug' => 'ballistic',
                'introduced_year' => 2023,
                'estimated_produced' => 10,
                'description' => 'Russian heavy ICBM replacing R-36M Satan. Liquid-fueled silo-based. Can carry 10+ MIRVs or Avangard hypersonic glide vehicles. Range allows South Pole trajectory to evade US missile defenses. Heaviest ICBM currently deployed.',
                'specifications' => json_encode([
                    'manufacturer' => 'Makeyev Rocket Design Bureau',
                    'origin_country' => 'Russia',
                    'range_km' => 18000,
                    'speed_mach' => 20,
                    'length_m' => 35,
                    'weight_tonnes' => 208,
                    'throw_weight_tonnes' => 10,
                    'warheads' => '10-15 MIRVs or 3 Avangard HGV',
                    'propellant' => 'Liquid',
                    'guidance' => 'INS + stellar',
                ]),
            ],

            // =============================================
            // HYPERSONIC MISSILES
            // =============================================
            [
                'designation' => 'DF-17',
                'nato_designation' => null,
                'common_name' => 'DF-17',
                'country_code' => 'CN',
                'category_slug' => 'ballistic',
                'introduced_year' => 2019,
                'estimated_produced' => 100,
                'description' => 'Chinese medium-range ballistic missile with hypersonic glide vehicle (HGV) payload. First operational hypersonic weapon. DF-ZF HGV maneuvers at Mach 5-10 at lower altitude than traditional ballistic trajectory, complicating missile defense. Road-mobile launch.',
                'specifications' => json_encode([
                    'manufacturer' => 'CASIC',
                    'origin_country' => 'China',
                    'range_km' => 1800,
                    'speed_mach' => 10,
                    'payload' => 'DF-ZF hypersonic glide vehicle',
                    'guidance' => 'INS + terminal radar',
                    'maneuverable' => true,
                    'mobile' => true,
                ]),
            ],
            [
                'designation' => 'Avangard',
                'nato_designation' => null,
                'common_name' => 'Avangard',
                'country_code' => 'RU',
                'category_slug' => 'ballistic',
                'introduced_year' => 2019,
                'estimated_produced' => 20,
                'description' => 'Russian hypersonic glide vehicle carried by UR-100N or Sarmat ICBMs. Glides at Mach 20+ with unpredictable trajectory to defeat missile defenses. Nuclear capable. Declared operational by Russia in December 2019. Extreme maneuvering makes interception nearly impossible.',
                'specifications' => json_encode([
                    'manufacturer' => 'NPO Mashinostroyeniya',
                    'origin_country' => 'Russia',
                    'speed_mach' => 27,
                    'range_km' => 6000,
                    'carrier' => 'UR-100N UTTH or RS-28 Sarmat',
                    'warhead' => 'Nuclear',
                    'maneuverable' => true,
                    'hypersonic_glide_vehicle' => true,
                ]),
            ],
            [
                'designation' => 'AGM-183A ARRW',
                'nato_designation' => null,
                'common_name' => 'ARRW',
                'country_code' => 'US',
                'category_slug' => 'ballistic',
                'introduced_year' => 2024,
                'estimated_produced' => 50,
                'description' => 'Air-launched Rapid Response Weapon by Lockheed Martin. Air-breathing hypersonic boost-glide weapon for B-52H bombers. Reaches Mach 15-20. After multiple test failures, limited procurement planned. Complemented by HACM scramjet program.',
                'specifications' => json_encode([
                    'manufacturer' => 'Lockheed Martin',
                    'origin_country' => 'United States',
                    'range_km' => 1600,
                    'speed_mach' => 20,
                    'guidance' => 'INS + GPS',
                    'platform' => 'B-52H',
                    'boost_glide' => true,
                ]),
            ],
        ];

        foreach ($moreMissiles as $item) {
            $countryId = $countries[$item['country_code']] ?? null;
            $categoryId = $categories[$item['category_slug']] ?? null;

            if (!$countryId || !$categoryId) {
                $this->command->warn("Skipping {$item['designation']}: Missing country or category");
                continue;
            }

            DB::table('military_equipment')->updateOrInsert(
                ['designation' => $item['designation']],
                [
                    'uuid' => Str::uuid(),
                    'designation' => $item['designation'],
                    'nato_designation' => $item['nato_designation'],
                    'common_name' => $item['common_name'],
                    'country_id' => $countryId,
                    'category_id' => $categoryId,
                    'introduced_year' => $item['introduced_year'],
                    'estimated_produced' => $item['estimated_produced'],
                    'description' => $item['description'],
                    'specifications' => $item['specifications'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

        $this->command->info('Additional missiles seeded (30 items)');

        // Now update existing equipment with enhanced descriptions
        $this->updateExistingDescriptions();
    }

    private function updateExistingDescriptions(): void
    {
        $updates = [
            'T-90M Proryv' => 'Russia\'s most advanced operational main battle tank developed by Uralvagonzavod. Features Relikt explosive reactive armor, improved Sosna-U sighting system with thermal imaging, and soft-kill Shtora-1 countermeasures. Recognizable by welded turret with distinctive ERA configuration. Combat proven in Ukraine conflict. Crew protected in armored capsule. 125mm smoothbore gun with autoloader fires Refleks ATGMs.',

            'T-72B3' => 'Modernized Soviet-era tank by Uralvagonzavod representing bulk of Russian armored forces. Identifiable by Kontakt-5 ERA blocks on turret and hull. Upgraded fire control with Sosna-U sight. Workhorse of Russian operations in Ukraine with significant losses documented. Cost-effective upgrade of massive T-72 stockpiles. 125mm gun with autoloader.',

            'Leopard 2A7' => 'Germany\'s premier main battle tank by Krauss-Maffei Wegmann (KMW). Latest variant features enhanced mine protection, urban warfare kit, and programmable HE rounds. Identifiable by wedge-shaped turret addon armor. Rheinmetall 120mm L55A1 gun is most powerful Western tank gun. Exported to 18 nations. Considered among finest MBTs globally.',

            'M1A2 Abrams SEP v3' => 'America\'s primary main battle tank by General Dynamics Land Systems. SEP v3 (System Enhancement Package) adds improved thermal sights, datalinks, and auxiliary power unit. Distinctive turbine engine whine and flat turret profile. Chobham composite armor with depleted uranium mesh. 120mm M256 smoothbore gun. Battle-tested in Gulf War, Iraq, and with allies.',

            'F-35A Lightning II' => 'Fifth-generation multirole stealth fighter by Lockheed Martin. Single-seat, single-engine with internal weapons bays. AN/APG-81 AESA radar, distributed aperture system provides 360° situational awareness. Recognizable by faceted fuselage and EOTS chin turret. Largest defense program in history with 15+ operator nations. CTOL variant for conventional runways.',

            'Su-35S' => 'Russian twin-engine super-maneuverable 4++ generation fighter by Sukhoi. Features thrust-vectoring AL-41F1S engines, Irbis-E passive electronically scanned array radar. Identifiable by canards (removed in production) and distinctive intake design. Heavy weapon load of 8000kg on 12 hardpoints. Air superiority role with multirole capability.',

            'M142 HIMARS' => 'High Mobility Artillery Rocket System by Lockheed Martin on 5-ton truck chassis. Carries 6 GMLRS rockets (70km range) or 1 ATACMS missile (300km range). Game-changing weapon in Ukraine conflict for precision deep strikes. C-130 transportable for rapid deployment. Automated fire control with GPS-guided munitions.',

            'S-400 Triumf' => 'Russia\'s advanced long-range SAM system by Almaz-Antey. Multiple missile types engage targets from 2-400km range, 10-30km altitude. Distinctive quad-canister launchers on 5P85 TEL. 91N6E "Big Bird" acquisition radar and 92N6E "Grave Stone" engagement radar. Controversial exports to Turkey, India, China. Claimed effective against stealth aircraft.',

            'Iron Dome' => 'Israeli short-range air defense system by Rafael and Israel Aerospace Industries. Intercepts rockets, artillery, mortars using Tamir interceptors. Revolutionary cost-effective approach engaging only threatening projectiles. 90%+ intercept rate claimed. Battle-proven against thousands of Hamas rockets. Each battery has 3-4 launchers with 20 missiles each.',

            'Ka-52' => 'Russian tandem-seat attack helicopter by Kamov with signature coaxial contra-rotating rotors eliminating tail rotor. Crew seated side-by-side unlike conventional tandem. Vikhr ATGMs, rockets, 30mm cannon. Advanced radar in nose cone. Ejection seats rare for helicopters. Extensively used in Ukraine with documented losses to MANPADs.',

            'AH-64E Apache Guardian' => 'Premier American attack helicopter by Boeing. Tandem crew with pilot rear, copilot/gunner front. Distinctive Longbow millimeter-wave radar dome above rotor. 30mm M230 chain gun, Hellfire missiles, Hydra rockets. Integrated with UAS for unmanned teaming. Night vision and thermal imaging for all-weather operations. Combat proven globally.',
        ];

        foreach ($updates as $designation => $description) {
            DB::table('military_equipment')
                ->where('designation', $designation)
                ->update(['description' => $description, 'updated_at' => now()]);
        }

        $this->command->info('Updated ' . count($updates) . ' existing equipment descriptions');
    }
}
