<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MilitaryEquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Populates equipment categories and military equipment with real-world data
     * from active conflict zones (Russia-Ukraine, Israel-Gaza, etc.)
     */
    public function run(): void
    {
        // Seed equipment categories first
        $this->seedCategories();

        // Seed military equipment
        $this->seedEquipment();

        $this->command->info('Military Equipment seeded successfully.');
    }

    private function seedCategories(): void
    {
        $categories = [
            // Main categories
            ['name' => 'Naval Vessels', 'slug' => 'naval', 'icon' => 'ship', 'sort_order' => 1],
            ['name' => 'Land Vehicles', 'slug' => 'land', 'icon' => 'tank', 'sort_order' => 2],
            ['name' => 'Aircraft', 'slug' => 'aircraft', 'icon' => 'plane', 'sort_order' => 3],
            ['name' => 'Helicopters', 'slug' => 'helicopters', 'icon' => 'helicopter', 'sort_order' => 4],
            ['name' => 'Missiles & Rockets', 'slug' => 'missiles', 'icon' => 'rocket', 'sort_order' => 5],
        ];

        foreach ($categories as $category) {
            DB::table('equipment_categories')->updateOrInsert(
                ['slug' => $category['slug']],
                array_merge($category, ['created_at' => now(), 'updated_at' => now()])
            );
        }

        // Subcategories
        $subcategories = [
            // Naval subcategories
            ['name' => 'Aircraft Carriers', 'slug' => 'carriers', 'parent_slug' => 'naval', 'icon' => 'ship', 'sort_order' => 1],
            ['name' => 'Destroyers', 'slug' => 'destroyers', 'parent_slug' => 'naval', 'icon' => 'ship', 'sort_order' => 2],
            ['name' => 'Frigates', 'slug' => 'frigates', 'parent_slug' => 'naval', 'icon' => 'ship', 'sort_order' => 3],
            ['name' => 'Submarines', 'slug' => 'submarines', 'parent_slug' => 'naval', 'icon' => 'submarine', 'sort_order' => 4],
            ['name' => 'Patrol Boats', 'slug' => 'patrol-boats', 'parent_slug' => 'naval', 'icon' => 'ship', 'sort_order' => 5],

            // Land subcategories
            ['name' => 'Main Battle Tanks', 'slug' => 'mbt', 'parent_slug' => 'land', 'icon' => 'tank', 'sort_order' => 1],
            ['name' => 'Infantry Fighting Vehicles', 'slug' => 'ifv', 'parent_slug' => 'land', 'icon' => 'truck-military', 'sort_order' => 2],
            ['name' => 'Armored Personnel Carriers', 'slug' => 'apc', 'parent_slug' => 'land', 'icon' => 'truck', 'sort_order' => 3],
            ['name' => 'Self-Propelled Artillery', 'slug' => 'spa', 'parent_slug' => 'land', 'icon' => 'crosshairs', 'sort_order' => 4],
            ['name' => 'Multiple Launch Rocket Systems', 'slug' => 'mlrs', 'parent_slug' => 'land', 'icon' => 'rocket', 'sort_order' => 5],
            ['name' => 'Air Defense Systems', 'slug' => 'sam', 'parent_slug' => 'land', 'icon' => 'shield-alt', 'sort_order' => 6],

            // Aircraft subcategories
            ['name' => 'Fighter Jets', 'slug' => 'fighters', 'parent_slug' => 'aircraft', 'icon' => 'fighter-jet', 'sort_order' => 1],
            ['name' => 'Bombers', 'slug' => 'bombers', 'parent_slug' => 'aircraft', 'icon' => 'plane', 'sort_order' => 2],
            ['name' => 'Transport Aircraft', 'slug' => 'transport-aircraft', 'parent_slug' => 'aircraft', 'icon' => 'plane', 'sort_order' => 3],
            ['name' => 'AWACS/AEW', 'slug' => 'awacs', 'parent_slug' => 'aircraft', 'icon' => 'satellite-dish', 'sort_order' => 4],
            ['name' => 'Unmanned Aerial Vehicles', 'slug' => 'uav', 'parent_slug' => 'aircraft', 'icon' => 'drone', 'sort_order' => 5],

            // Helicopter subcategories
            ['name' => 'Attack Helicopters', 'slug' => 'attack-heli', 'parent_slug' => 'helicopters', 'icon' => 'helicopter', 'sort_order' => 1],
            ['name' => 'Transport Helicopters', 'slug' => 'transport-heli', 'parent_slug' => 'helicopters', 'icon' => 'helicopter', 'sort_order' => 2],
            ['name' => 'Naval Helicopters', 'slug' => 'naval-heli', 'parent_slug' => 'helicopters', 'icon' => 'helicopter', 'sort_order' => 3],

            // Missile subcategories
            ['name' => 'MANPADS', 'slug' => 'manpads', 'parent_slug' => 'missiles', 'icon' => 'rocket', 'sort_order' => 1],
            ['name' => 'Anti-Tank Guided Missiles', 'slug' => 'atgm', 'parent_slug' => 'missiles', 'icon' => 'bullseye', 'sort_order' => 2],
            ['name' => 'Cruise Missiles', 'slug' => 'cruise', 'parent_slug' => 'missiles', 'icon' => 'rocket', 'sort_order' => 3],
            ['name' => 'Ballistic Missiles', 'slug' => 'ballistic', 'parent_slug' => 'missiles', 'icon' => 'rocket', 'sort_order' => 4],
        ];

        foreach ($subcategories as $sub) {
            $parent = DB::table('equipment_categories')->where('slug', $sub['parent_slug'])->first();
            if ($parent) {
                DB::table('equipment_categories')->updateOrInsert(
                    ['slug' => $sub['slug']],
                    [
                        'name' => $sub['name'],
                        'slug' => $sub['slug'],
                        'parent_id' => $parent->id,
                        'icon' => $sub['icon'],
                        'sort_order' => $sub['sort_order'],
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                );
            }
        }
    }

    private function seedEquipment(): void
    {
        // Get category IDs
        $categories = DB::table('equipment_categories')->pluck('id', 'slug');

        // Get country IDs (assuming countries are seeded)
        $countries = DB::table('countries')->pluck('id', 'iso_code');

        $equipment = [
            // ========================================
            // RUSSIAN EQUIPMENT
            // ========================================
            // Tanks
            [
                'designation' => 'T-90M Proryv',
                'nato_designation' => null,
                'common_name' => 'T-90M',
                'country_code' => 'RU',
                'category_slug' => 'mbt',
                'introduced_year' => 2020,
                'estimated_produced' => 500,
                'description' => 'Modernized main battle tank with improved armor, fire control, and active protection system.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'weight_tonnes' => 48,
                    'main_gun' => '125mm 2A46M-5 smoothbore',
                    'engine' => 'V-92S2F 1130hp diesel',
                    'max_speed_kmh' => 60,
                    'range_km' => 550,
                    'armor' => 'Relikt ERA + composite',
                ]),
            ],
            [
                'designation' => 'T-72B3',
                'nato_designation' => null,
                'common_name' => 'T-72B3',
                'country_code' => 'RU',
                'category_slug' => 'mbt',
                'introduced_year' => 2012,
                'estimated_produced' => 1400,
                'description' => 'Upgraded T-72B with modern fire control and ERA.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'weight_tonnes' => 46,
                    'main_gun' => '125mm 2A46M-5',
                    'engine' => 'V-92S2 1000hp',
                    'max_speed_kmh' => 65,
                ]),
            ],
            [
                'designation' => 'T-80BVM',
                'nato_designation' => null,
                'common_name' => 'T-80BVM',
                'country_code' => 'RU',
                'category_slug' => 'mbt',
                'introduced_year' => 2017,
                'estimated_produced' => 200,
                'description' => 'Modernized T-80B with gas turbine engine and Relikt ERA.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'weight_tonnes' => 46,
                    'main_gun' => '125mm 2A46M-4',
                    'engine' => 'GTD-1250 gas turbine 1250hp',
                    'max_speed_kmh' => 70,
                ]),
            ],

            // Russian IFVs
            [
                'designation' => 'BMP-3',
                'nato_designation' => null,
                'common_name' => 'BMP-3',
                'country_code' => 'RU',
                'category_slug' => 'ifv',
                'introduced_year' => 1987,
                'estimated_produced' => 2000,
                'description' => 'Infantry fighting vehicle with 100mm gun and 30mm autocannon.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'passengers' => 7,
                    'weight_tonnes' => 19,
                    'main_armament' => '100mm 2A70 rifled gun + 30mm 2A72 autocannon',
                    'engine' => 'UTD-29 500hp',
                ]),
            ],
            [
                'designation' => 'BTR-82A',
                'nato_designation' => null,
                'common_name' => 'BTR-82A',
                'country_code' => 'RU',
                'category_slug' => 'apc',
                'introduced_year' => 2013,
                'estimated_produced' => 1500,
                'description' => 'Wheeled armored personnel carrier with 30mm autocannon.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'passengers' => 7,
                    'wheels' => '8x8',
                    'weight_tonnes' => 16,
                    'main_armament' => '30mm 2A72 autocannon',
                ]),
            ],

            // Russian Artillery
            [
                'designation' => '2S19 Msta-S',
                'nato_designation' => null,
                'common_name' => 'Msta-S',
                'country_code' => 'RU',
                'category_slug' => 'spa',
                'introduced_year' => 1989,
                'estimated_produced' => 800,
                'description' => 'Self-propelled 152mm howitzer.',
                'specifications' => json_encode([
                    'crew' => 5,
                    'main_gun' => '152mm 2A64',
                    'range_km' => 29,
                    'rate_of_fire' => '7-8 rounds/min',
                ]),
            ],
            [
                'designation' => 'BM-21 Grad',
                'nato_designation' => null,
                'common_name' => 'Grad',
                'country_code' => 'RU',
                'category_slug' => 'mlrs',
                'introduced_year' => 1963,
                'estimated_produced' => 9000,
                'description' => '122mm multiple rocket launcher system.',
                'specifications' => json_encode([
                    'tubes' => 40,
                    'caliber' => '122mm',
                    'range_km' => 20,
                    'reload_time_min' => 10,
                ]),
            ],
            [
                'designation' => 'BM-27 Uragan',
                'nato_designation' => null,
                'common_name' => 'Uragan',
                'country_code' => 'RU',
                'category_slug' => 'mlrs',
                'introduced_year' => 1975,
                'estimated_produced' => 800,
                'description' => '220mm heavy multiple rocket launcher.',
                'specifications' => json_encode([
                    'tubes' => 16,
                    'caliber' => '220mm',
                    'range_km' => 35,
                ]),
            ],

            // Russian Air Defense
            [
                'designation' => 'S-400 Triumf',
                'nato_designation' => 'SA-21 Growler',
                'common_name' => 'S-400',
                'country_code' => 'RU',
                'category_slug' => 'sam',
                'introduced_year' => 2007,
                'estimated_produced' => 100,
                'description' => 'Long-range surface-to-air missile system.',
                'specifications' => json_encode([
                    'missiles_per_battery' => 32,
                    'range_km' => 400,
                    'altitude_km' => 30,
                    'target_speed_ms' => 4800,
                ]),
            ],
            [
                'designation' => 'Buk-M3',
                'nato_designation' => 'SA-17 Grizzly',
                'common_name' => 'Buk-M3',
                'country_code' => 'RU',
                'category_slug' => 'sam',
                'introduced_year' => 2016,
                'estimated_produced' => 100,
                'description' => 'Medium-range surface-to-air missile system.',
                'specifications' => json_encode([
                    'missiles_per_vehicle' => 6,
                    'range_km' => 70,
                    'altitude_km' => 35,
                ]),
            ],
            [
                'designation' => '9K33 Osa',
                'nato_designation' => 'SA-8 Gecko',
                'common_name' => 'Osa',
                'country_code' => 'RU',
                'category_slug' => 'sam',
                'introduced_year' => 1971,
                'estimated_produced' => 1200,
                'description' => 'Short-range tactical surface-to-air missile system.',
                'specifications' => json_encode([
                    'missiles' => 6,
                    'range_km' => 15,
                    'altitude_km' => 12,
                ]),
            ],

            // Russian Aircraft
            [
                'designation' => 'Su-35S',
                'nato_designation' => 'Flanker-E',
                'common_name' => 'Su-35S',
                'country_code' => 'RU',
                'category_slug' => 'fighters',
                'introduced_year' => 2014,
                'estimated_produced' => 140,
                'description' => 'Super-maneuverable 4++ generation multirole fighter.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 2.25,
                    'range_km' => 3600,
                    'combat_radius_km' => 1600,
                    'hardpoints' => 12,
                ]),
            ],
            [
                'designation' => 'Su-57',
                'nato_designation' => 'Felon',
                'common_name' => 'Su-57',
                'country_code' => 'RU',
                'category_slug' => 'fighters',
                'introduced_year' => 2020,
                'estimated_produced' => 22,
                'description' => 'Fifth-generation stealth multirole fighter.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 2,
                    'range_km' => 3500,
                    'stealth' => true,
                    'supercruise' => true,
                ]),
            ],
            [
                'designation' => 'Tu-22M3',
                'nato_designation' => 'Backfire',
                'common_name' => 'Tu-22M3',
                'country_code' => 'RU',
                'category_slug' => 'bombers',
                'introduced_year' => 1983,
                'estimated_produced' => 268,
                'description' => 'Long-range supersonic maritime strike bomber.',
                'specifications' => json_encode([
                    'crew' => 4,
                    'max_speed_mach' => 1.88,
                    'range_km' => 6800,
                    'payload_kg' => 24000,
                ]),
            ],

            // Russian Helicopters
            [
                'designation' => 'Ka-52',
                'nato_designation' => 'Hokum-B',
                'common_name' => 'Alligator',
                'country_code' => 'RU',
                'category_slug' => 'attack-heli',
                'introduced_year' => 2011,
                'estimated_produced' => 160,
                'description' => 'All-weather attack helicopter with coaxial rotor.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'max_speed_kmh' => 300,
                    'range_km' => 460,
                    'main_armament' => '30mm 2A42 cannon',
                    'missiles' => 12,
                ]),
            ],
            [
                'designation' => 'Mi-28N',
                'nato_designation' => 'Havoc',
                'common_name' => 'Night Hunter',
                'country_code' => 'RU',
                'category_slug' => 'attack-heli',
                'introduced_year' => 2009,
                'estimated_produced' => 130,
                'description' => 'All-weather day-night attack helicopter.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'max_speed_kmh' => 305,
                    'range_km' => 450,
                    'main_armament' => '30mm 2A42 cannon',
                ]),
            ],

            // Russian Missiles
            [
                'designation' => '3M22 Zircon',
                'nato_designation' => 'SS-N-33',
                'common_name' => 'Zircon',
                'country_code' => 'RU',
                'category_slug' => 'cruise',
                'introduced_year' => 2023,
                'estimated_produced' => null,
                'description' => 'Hypersonic anti-ship cruise missile.',
                'specifications' => json_encode([
                    'speed_mach' => 9,
                    'range_km' => 1000,
                    'warhead_kg' => 300,
                ]),
            ],
            [
                'designation' => '9M133 Kornet',
                'nato_designation' => 'AT-14 Spriggan',
                'common_name' => 'Kornet',
                'country_code' => 'RU',
                'category_slug' => 'atgm',
                'introduced_year' => 1998,
                'estimated_produced' => 35000,
                'description' => 'Laser-guided anti-tank guided missile.',
                'specifications' => json_encode([
                    'guidance' => 'SACLOS laser beam-riding',
                    'range_m' => 5500,
                    'penetration_mm' => 1200,
                    'warhead' => 'tandem HEAT',
                ]),
            ],

            // ========================================
            // UKRAINIAN EQUIPMENT
            // ========================================
            [
                'designation' => 'T-84 Oplot',
                'nato_designation' => null,
                'common_name' => 'Oplot',
                'country_code' => 'UA',
                'category_slug' => 'mbt',
                'introduced_year' => 1999,
                'estimated_produced' => 100,
                'description' => 'Ukrainian main battle tank based on T-80.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'weight_tonnes' => 51,
                    'main_gun' => '125mm KBA3',
                    'engine' => '6TD-2 1200hp',
                ]),
            ],
            [
                'designation' => 'BTR-4 Bucephalus',
                'nato_designation' => null,
                'common_name' => 'BTR-4',
                'country_code' => 'UA',
                'category_slug' => 'apc',
                'introduced_year' => 2008,
                'estimated_produced' => 200,
                'description' => 'Modern 8x8 wheeled APC with modular turret.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'passengers' => 7,
                    'weight_tonnes' => 17,
                    'main_armament' => '30mm ZTM-1',
                ]),
            ],
            [
                'designation' => 'Bayraktar TB2',
                'nato_designation' => null,
                'common_name' => 'Bayraktar TB2',
                'country_code' => 'TR',
                'category_slug' => 'uav',
                'introduced_year' => 2014,
                'estimated_produced' => 500,
                'description' => 'Turkish medium-altitude long-endurance UAV.',
                'specifications' => json_encode([
                    'wingspan_m' => 12,
                    'endurance_hours' => 27,
                    'ceiling_m' => 8200,
                    'payload_kg' => 150,
                ]),
            ],

            // ========================================
            // US EQUIPMENT (Supplied to Ukraine)
            // ========================================
            [
                'designation' => 'M1A2 Abrams SEP v3',
                'nato_designation' => null,
                'common_name' => 'Abrams',
                'country_code' => 'US',
                'category_slug' => 'mbt',
                'introduced_year' => 2020,
                'estimated_produced' => 1500,
                'description' => 'Main battle tank with advanced composite armor.',
                'specifications' => json_encode([
                    'crew' => 4,
                    'weight_tonnes' => 67,
                    'main_gun' => '120mm M256 smoothbore',
                    'engine' => 'AGT1500 gas turbine 1500hp',
                    'max_speed_kmh' => 68,
                ]),
            ],
            [
                'designation' => 'M2A3 Bradley',
                'nato_designation' => null,
                'common_name' => 'Bradley',
                'country_code' => 'US',
                'category_slug' => 'ifv',
                'introduced_year' => 2000,
                'estimated_produced' => 6000,
                'description' => 'Infantry fighting vehicle with TOW missiles.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'passengers' => 6,
                    'weight_tonnes' => 30,
                    'main_armament' => '25mm M242 Bushmaster',
                    'missiles' => 'TOW-2',
                ]),
            ],
            [
                'designation' => 'M142 HIMARS',
                'nato_designation' => null,
                'common_name' => 'HIMARS',
                'country_code' => 'US',
                'category_slug' => 'mlrs',
                'introduced_year' => 2005,
                'estimated_produced' => 550,
                'description' => 'High Mobility Artillery Rocket System.',
                'specifications' => json_encode([
                    'rockets' => 6,
                    'caliber' => '227mm',
                    'range_km' => 300,
                    'gmlrs_range_km' => 80,
                ]),
            ],
            [
                'designation' => 'FGM-148 Javelin',
                'nato_designation' => null,
                'common_name' => 'Javelin',
                'country_code' => 'US',
                'category_slug' => 'atgm',
                'introduced_year' => 1996,
                'estimated_produced' => 50000,
                'description' => 'Fire-and-forget anti-tank missile with top-attack mode.',
                'specifications' => json_encode([
                    'guidance' => 'Infrared imaging',
                    'range_m' => 4750,
                    'penetration_mm' => 800,
                    'weight_kg' => 22.3,
                ]),
            ],
            [
                'designation' => 'FIM-92 Stinger',
                'nato_designation' => null,
                'common_name' => 'Stinger',
                'country_code' => 'US',
                'category_slug' => 'manpads',
                'introduced_year' => 1981,
                'estimated_produced' => 70000,
                'description' => 'Infrared homing surface-to-air missile.',
                'specifications' => json_encode([
                    'guidance' => 'IR homing',
                    'range_km' => 8,
                    'altitude_m' => 3800,
                    'weight_kg' => 15.2,
                ]),
            ],
            [
                'designation' => 'MIM-104 Patriot',
                'nato_designation' => null,
                'common_name' => 'Patriot',
                'country_code' => 'US',
                'category_slug' => 'sam',
                'introduced_year' => 1984,
                'estimated_produced' => 1100,
                'description' => 'Long-range surface-to-air missile system.',
                'specifications' => json_encode([
                    'range_km' => 160,
                    'altitude_km' => 24,
                    'interceptors_per_battery' => 16,
                ]),
            ],
            [
                'designation' => 'F-16C/D Fighting Falcon',
                'nato_designation' => null,
                'common_name' => 'F-16',
                'country_code' => 'US',
                'category_slug' => 'fighters',
                'introduced_year' => 1978,
                'estimated_produced' => 4600,
                'description' => 'Multirole fighter aircraft.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 2,
                    'range_km' => 4220,
                    'hardpoints' => 9,
                ]),
            ],
            [
                'designation' => 'F-35A Lightning II',
                'nato_designation' => null,
                'common_name' => 'F-35A',
                'country_code' => 'US',
                'category_slug' => 'fighters',
                'introduced_year' => 2015,
                'estimated_produced' => 1000,
                'description' => 'Fifth-generation stealth multirole fighter.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 1.6,
                    'range_km' => 2200,
                    'stealth' => true,
                    'vtol' => false,
                ]),
            ],
            [
                'designation' => 'AH-64E Apache Guardian',
                'nato_designation' => null,
                'common_name' => 'Apache',
                'country_code' => 'US',
                'category_slug' => 'attack-heli',
                'introduced_year' => 2011,
                'estimated_produced' => 700,
                'description' => 'Advanced attack helicopter with Longbow radar.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'max_speed_kmh' => 293,
                    'range_km' => 476,
                    'main_armament' => '30mm M230 chain gun',
                    'missiles' => 16,
                ]),
            ],

            // ========================================
            // GERMAN EQUIPMENT
            // ========================================
            [
                'designation' => 'Leopard 2A7',
                'nato_designation' => null,
                'common_name' => 'Leopard 2',
                'country_code' => 'DE',
                'category_slug' => 'mbt',
                'introduced_year' => 2014,
                'estimated_produced' => 200,
                'description' => 'German main battle tank, latest variant.',
                'specifications' => json_encode([
                    'crew' => 4,
                    'weight_tonnes' => 67,
                    'main_gun' => '120mm L55A1',
                    'engine' => 'MTU MB 873 1500hp',
                ]),
            ],
            [
                'designation' => 'Marder 1A5',
                'nato_designation' => null,
                'common_name' => 'Marder',
                'country_code' => 'DE',
                'category_slug' => 'ifv',
                'introduced_year' => 2002,
                'estimated_produced' => 350,
                'description' => 'German infantry fighting vehicle.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'passengers' => 6,
                    'weight_tonnes' => 35,
                    'main_armament' => '20mm Rh202',
                ]),
            ],
            [
                'designation' => 'PzH 2000',
                'nato_designation' => null,
                'common_name' => 'Panzerhaubitze 2000',
                'country_code' => 'DE',
                'category_slug' => 'spa',
                'introduced_year' => 1998,
                'estimated_produced' => 300,
                'description' => 'Self-propelled 155mm howitzer.',
                'specifications' => json_encode([
                    'crew' => 5,
                    'main_gun' => '155mm L52',
                    'range_km' => 56,
                    'rate_of_fire' => '10 rounds/min',
                ]),
            ],
            [
                'designation' => 'IRIS-T SLM',
                'nato_designation' => null,
                'common_name' => 'IRIS-T',
                'country_code' => 'DE',
                'category_slug' => 'sam',
                'introduced_year' => 2022,
                'estimated_produced' => 40,
                'description' => 'Medium-range surface-to-air missile system.',
                'specifications' => json_encode([
                    'range_km' => 40,
                    'altitude_km' => 20,
                    'missiles' => 8,
                ]),
            ],

            // ========================================
            // UK EQUIPMENT
            // ========================================
            [
                'designation' => 'Challenger 2',
                'nato_designation' => null,
                'common_name' => 'Challenger 2',
                'country_code' => 'GB',
                'category_slug' => 'mbt',
                'introduced_year' => 1998,
                'estimated_produced' => 386,
                'description' => 'British main battle tank with rifled gun.',
                'specifications' => json_encode([
                    'crew' => 4,
                    'weight_tonnes' => 75,
                    'main_gun' => '120mm L30A1 rifled',
                    'engine' => 'Perkins CV12 1200hp',
                ]),
            ],
            [
                'designation' => 'AS-90',
                'nato_designation' => null,
                'common_name' => 'AS-90',
                'country_code' => 'GB',
                'category_slug' => 'spa',
                'introduced_year' => 1993,
                'estimated_produced' => 179,
                'description' => 'Self-propelled 155mm howitzer.',
                'specifications' => json_encode([
                    'crew' => 5,
                    'main_gun' => '155mm L31',
                    'range_km' => 24.7,
                ]),
            ],
            [
                'designation' => 'Starstreak',
                'nato_designation' => null,
                'common_name' => 'Starstreak',
                'country_code' => 'GB',
                'category_slug' => 'manpads',
                'introduced_year' => 1997,
                'estimated_produced' => 5000,
                'description' => 'High-velocity surface-to-air missile.',
                'specifications' => json_encode([
                    'guidance' => 'Laser beam-riding',
                    'speed_mach' => 4,
                    'range_km' => 7,
                    'darts' => 3,
                ]),
            ],
            [
                'designation' => 'Storm Shadow',
                'nato_designation' => null,
                'common_name' => 'Storm Shadow',
                'country_code' => 'GB',
                'category_slug' => 'cruise',
                'introduced_year' => 2003,
                'estimated_produced' => 900,
                'description' => 'Long-range air-launched cruise missile.',
                'specifications' => json_encode([
                    'range_km' => 560,
                    'speed' => 'subsonic',
                    'guidance' => 'INS + terrain reference + GPS',
                    'warhead_kg' => 450,
                ]),
            ],

            // ========================================
            // FRENCH EQUIPMENT
            // ========================================
            [
                'designation' => 'Leclerc',
                'nato_designation' => null,
                'common_name' => 'Leclerc',
                'country_code' => 'FR',
                'category_slug' => 'mbt',
                'introduced_year' => 1992,
                'estimated_produced' => 862,
                'description' => 'French main battle tank with autoloader.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'weight_tonnes' => 57,
                    'main_gun' => '120mm CN120-26/52',
                    'engine' => 'SACM V8X 1500hp',
                ]),
            ],
            [
                'designation' => 'AMX-10 RC',
                'nato_designation' => null,
                'common_name' => 'AMX-10 RC',
                'country_code' => 'FR',
                'category_slug' => 'ifv',
                'introduced_year' => 1981,
                'estimated_produced' => 337,
                'description' => 'Wheeled armored reconnaissance vehicle.',
                'specifications' => json_encode([
                    'crew' => 4,
                    'wheels' => '6x6',
                    'weight_tonnes' => 17,
                    'main_gun' => '105mm CN105 F1',
                ]),
            ],
            [
                'designation' => 'CAESAR',
                'nato_designation' => null,
                'common_name' => 'CAESAR',
                'country_code' => 'FR',
                'category_slug' => 'spa',
                'introduced_year' => 2008,
                'estimated_produced' => 500,
                'description' => 'Truck-mounted 155mm howitzer.',
                'specifications' => json_encode([
                    'crew' => 5,
                    'main_gun' => '155mm L52',
                    'range_km' => 42,
                    'mobility' => 'wheeled',
                ]),
            ],
            [
                'designation' => 'SCALP-EG',
                'nato_designation' => null,
                'common_name' => 'SCALP',
                'country_code' => 'FR',
                'category_slug' => 'cruise',
                'introduced_year' => 2003,
                'estimated_produced' => 600,
                'description' => 'Air-launched cruise missile (French Storm Shadow).',
                'specifications' => json_encode([
                    'range_km' => 560,
                    'speed' => 'subsonic',
                    'warhead_kg' => 450,
                ]),
            ],
            [
                'designation' => 'Rafale',
                'nato_designation' => null,
                'common_name' => 'Rafale',
                'country_code' => 'FR',
                'category_slug' => 'fighters',
                'introduced_year' => 2001,
                'estimated_produced' => 230,
                'description' => 'Twin-engine multirole fighter.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 1.8,
                    'range_km' => 3700,
                    'hardpoints' => 14,
                ]),
            ],

            // ========================================
            // ISRAELI EQUIPMENT
            // ========================================
            [
                'designation' => 'Merkava Mk.4',
                'nato_designation' => null,
                'common_name' => 'Merkava Mk.4',
                'country_code' => 'IL',
                'category_slug' => 'mbt',
                'introduced_year' => 2004,
                'estimated_produced' => 360,
                'description' => 'Israeli main battle tank with Trophy APS.',
                'specifications' => json_encode([
                    'crew' => 4,
                    'weight_tonnes' => 65,
                    'main_gun' => '120mm MG253 smoothbore',
                    'engine' => 'MTU MT 883 1500hp',
                    'aps' => 'Trophy',
                ]),
            ],
            [
                'designation' => 'Namer',
                'nato_designation' => null,
                'common_name' => 'Namer',
                'country_code' => 'IL',
                'category_slug' => 'apc',
                'introduced_year' => 2008,
                'estimated_produced' => 120,
                'description' => 'Heavy APC based on Merkava chassis.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'passengers' => 9,
                    'weight_tonnes' => 60,
                    'aps' => 'Trophy',
                ]),
            ],
            [
                'designation' => 'Iron Dome',
                'nato_designation' => null,
                'common_name' => 'Iron Dome',
                'country_code' => 'IL',
                'category_slug' => 'sam',
                'introduced_year' => 2011,
                'estimated_produced' => 15,
                'description' => 'Mobile air defense system for short-range rockets.',
                'specifications' => json_encode([
                    'interceptors_per_battery' => 60,
                    'range_km' => 70,
                    'intercept_rate' => '90%',
                ]),
            ],
            [
                'designation' => 'David\'s Sling',
                'nato_designation' => null,
                'common_name' => 'David\'s Sling',
                'country_code' => 'IL',
                'category_slug' => 'sam',
                'introduced_year' => 2017,
                'estimated_produced' => 6,
                'description' => 'Medium-range air and missile defense system.',
                'specifications' => json_encode([
                    'range_km' => 300,
                    'targets' => 'cruise missiles, ballistic missiles, aircraft',
                ]),
            ],
            [
                'designation' => 'Spike ATGM',
                'nato_designation' => null,
                'common_name' => 'Spike',
                'country_code' => 'IL',
                'category_slug' => 'atgm',
                'introduced_year' => 1997,
                'estimated_produced' => 33000,
                'description' => 'Family of fire-and-forget anti-tank missiles.',
                'specifications' => json_encode([
                    'variants' => ['MR', 'LR', 'ER', 'NLOS'],
                    'range_km' => '2.5-25',
                    'guidance' => 'electro-optical',
                ]),
            ],
            [
                'designation' => 'F-35I Adir',
                'nato_designation' => null,
                'common_name' => 'F-35I Adir',
                'country_code' => 'IL',
                'category_slug' => 'fighters',
                'introduced_year' => 2017,
                'estimated_produced' => 50,
                'description' => 'Israeli variant of F-35A with unique avionics.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 1.6,
                    'stealth' => true,
                    'israeli_systems' => true,
                ]),
            ],

            // ========================================
            // CHINESE EQUIPMENT
            // ========================================
            [
                'designation' => 'Type 99A',
                'nato_designation' => null,
                'common_name' => 'Type 99A',
                'country_code' => 'CN',
                'category_slug' => 'mbt',
                'introduced_year' => 2011,
                'estimated_produced' => 600,
                'description' => 'Chinese third-generation main battle tank.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'weight_tonnes' => 58,
                    'main_gun' => '125mm ZPT-98',
                    'engine' => '1500hp diesel',
                ]),
            ],
            [
                'designation' => 'J-20',
                'nato_designation' => 'Black Eagle',
                'common_name' => 'J-20 Mighty Dragon',
                'country_code' => 'CN',
                'category_slug' => 'fighters',
                'introduced_year' => 2017,
                'estimated_produced' => 200,
                'description' => 'Fifth-generation stealth multirole fighter with canard-delta configuration. Features Type 1475 AESA radar, infrared sensors, and networked EW system. One of four operational stealth fighters globally.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 2,
                    'length_m' => 20.4,
                    'max_weight_tonnes' => 34,
                    'payload_kg' => 11000,
                    'unit_cost_million' => 110,
                    'stealth' => true,
                    'supercruise' => true,
                ]),
            ],
            [
                'designation' => 'DF-21D',
                'nato_designation' => 'CSS-5 Mod 4',
                'common_name' => 'Carrier Killer',
                'country_code' => 'CN',
                'category_slug' => 'ballistic',
                'introduced_year' => 2010,
                'estimated_produced' => 100,
                'description' => 'Anti-ship ballistic missile.',
                'specifications' => json_encode([
                    'range_km' => 1500,
                    'warhead_kg' => 600,
                    'guidance' => 'terminal maneuvering',
                ]),
            ],
            [
                'designation' => 'Type 055',
                'nato_designation' => 'Renhai-class',
                'common_name' => 'Type 055 Destroyer',
                'country_code' => 'CN',
                'category_slug' => 'destroyers',
                'introduced_year' => 2020,
                'estimated_produced' => 8,
                'description' => 'Chinese large guided-missile destroyer, among the most powerful surface combatants in the world.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 13000,
                    'length_m' => 180,
                    'vls_cells' => 112,
                    'crew' => 300,
                    'speed_knots' => 30,
                ]),
            ],
            [
                'designation' => 'Liaoning',
                'nato_designation' => null,
                'common_name' => 'Liaoning',
                'country_code' => 'CN',
                'category_slug' => 'carriers',
                'introduced_year' => 2012,
                'estimated_produced' => 1,
                'description' => 'STOBAR aircraft carrier, refurbished former Soviet Kuznetsov-class.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 60000,
                    'length_m' => 305,
                    'aircraft' => 40,
                    'crew' => 2000,
                ]),
            ],

            // ========================================
            // SOUTH KOREAN EQUIPMENT
            // ========================================
            [
                'designation' => 'K2 Black Panther',
                'nato_designation' => null,
                'common_name' => 'K2 Black Panther',
                'country_code' => 'KR',
                'category_slug' => 'mbt',
                'introduced_year' => 2014,
                'estimated_produced' => 260,
                'description' => 'Advanced fourth-generation main battle tank with autoloader, hydropneumatic suspension, and active protection system. One of the world\'s most advanced MBTs.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'weight_tonnes' => 55,
                    'main_gun' => '120mm L55 smoothbore',
                    'engine' => 'MTU MT 883 1500hp',
                    'max_speed_kmh' => 70,
                    'aps' => 'Active Kill System',
                    'autoloader' => true,
                ]),
            ],
            [
                'designation' => 'K9 Thunder',
                'nato_designation' => null,
                'common_name' => 'K9 Thunder',
                'country_code' => 'KR',
                'category_slug' => 'spa',
                'introduced_year' => 1999,
                'estimated_produced' => 1700,
                'description' => 'Self-propelled 155mm howitzer exported to multiple NATO countries.',
                'specifications' => json_encode([
                    'crew' => 5,
                    'main_gun' => '155mm L52',
                    'range_km' => 40,
                    'rate_of_fire' => '6 rounds/min',
                ]),
            ],
            [
                'designation' => 'FA-50',
                'nato_designation' => null,
                'common_name' => 'FA-50 Fighting Eagle',
                'country_code' => 'KR',
                'category_slug' => 'fighters',
                'introduced_year' => 2013,
                'estimated_produced' => 120,
                'description' => 'Light combat aircraft derived from T-50 Golden Eagle trainer.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 1.5,
                    'range_km' => 2600,
                    'hardpoints' => 7,
                ]),
            ],

            // ========================================
            // JAPANESE EQUIPMENT
            // ========================================
            [
                'designation' => 'Type 10',
                'nato_designation' => null,
                'common_name' => 'Type 10 Hitomaru',
                'country_code' => 'JP',
                'category_slug' => 'mbt',
                'introduced_year' => 2012,
                'estimated_produced' => 117,
                'description' => 'Japanese fourth-generation main battle tank with modular armor and C4I systems.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'weight_tonnes' => 48,
                    'main_gun' => '120mm L44',
                    'engine' => '1200hp diesel',
                    'max_speed_kmh' => 70,
                ]),
            ],
            [
                'designation' => 'F-2',
                'nato_designation' => null,
                'common_name' => 'F-2 Viper Zero',
                'country_code' => 'JP',
                'category_slug' => 'fighters',
                'introduced_year' => 2000,
                'estimated_produced' => 94,
                'description' => 'Multirole fighter based on F-16 with larger wings and AESA radar.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 2,
                    'range_km' => 4000,
                    'hardpoints' => 13,
                ]),
            ],
            [
                'designation' => 'Izumo-class',
                'nato_designation' => null,
                'common_name' => 'Izumo',
                'country_code' => 'JP',
                'category_slug' => 'carriers',
                'introduced_year' => 2015,
                'estimated_produced' => 2,
                'description' => 'Helicopter destroyer being converted to light aircraft carrier for F-35B.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 27000,
                    'length_m' => 248,
                    'aircraft' => 14,
                    'crew' => 520,
                ]),
            ],

            // ========================================
            // INDIAN EQUIPMENT
            // ========================================
            [
                'designation' => 'Arjun Mk.2',
                'nato_designation' => null,
                'common_name' => 'Arjun Mk.2',
                'country_code' => 'IN',
                'category_slug' => 'mbt',
                'introduced_year' => 2020,
                'estimated_produced' => 118,
                'description' => 'Indigenous Indian main battle tank with improved armor and firepower.',
                'specifications' => json_encode([
                    'crew' => 4,
                    'weight_tonnes' => 68,
                    'main_gun' => '120mm rifled',
                    'engine' => 'MTU 1400hp',
                ]),
            ],
            [
                'designation' => 'HAL Tejas Mk.1',
                'nato_designation' => null,
                'common_name' => 'Tejas',
                'country_code' => 'IN',
                'category_slug' => 'fighters',
                'introduced_year' => 2016,
                'estimated_produced' => 40,
                'description' => 'Indigenous light combat aircraft with delta wing configuration.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 1.8,
                    'range_km' => 3000,
                    'hardpoints' => 8,
                ]),
            ],
            [
                'designation' => 'BrahMos',
                'nato_designation' => null,
                'common_name' => 'BrahMos',
                'country_code' => 'IN',
                'category_slug' => 'cruise',
                'introduced_year' => 2006,
                'estimated_produced' => 500,
                'description' => 'Supersonic cruise missile jointly developed with Russia.',
                'specifications' => json_encode([
                    'speed_mach' => 3,
                    'range_km' => 450,
                    'warhead_kg' => 300,
                    'platforms' => ['ship', 'submarine', 'aircraft', 'land'],
                ]),
            ],
            [
                'designation' => 'INS Vikrant',
                'nato_designation' => null,
                'common_name' => 'INS Vikrant',
                'country_code' => 'IN',
                'category_slug' => 'carriers',
                'introduced_year' => 2022,
                'estimated_produced' => 1,
                'description' => 'Indigenous aircraft carrier, first built in India.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 45000,
                    'length_m' => 262,
                    'aircraft' => 30,
                    'crew' => 1700,
                ]),
            ],

            // ========================================
            // TURKISH EQUIPMENT
            // ========================================
            [
                'designation' => 'Altay',
                'nato_designation' => null,
                'common_name' => 'Altay',
                'country_code' => 'TR',
                'category_slug' => 'mbt',
                'introduced_year' => 2023,
                'estimated_produced' => 10,
                'description' => 'Indigenous Turkish main battle tank based on K2 design.',
                'specifications' => json_encode([
                    'crew' => 4,
                    'weight_tonnes' => 65,
                    'main_gun' => '120mm L55',
                    'engine' => '1500hp',
                ]),
            ],
            [
                'designation' => 'T129 ATAK',
                'nato_designation' => null,
                'common_name' => 'T129 ATAK',
                'country_code' => 'TR',
                'category_slug' => 'attack-heli',
                'introduced_year' => 2014,
                'estimated_produced' => 60,
                'description' => 'Attack helicopter developed from AgustaWestland A129.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'max_speed_kmh' => 278,
                    'range_km' => 561,
                    'main_armament' => '20mm cannon',
                ]),
            ],
            [
                'designation' => 'TF Kaan',
                'nato_designation' => null,
                'common_name' => 'KAAN',
                'country_code' => 'TR',
                'category_slug' => 'fighters',
                'introduced_year' => 2029,
                'estimated_produced' => 0,
                'description' => 'Fifth-generation stealth fighter under development.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 2,
                    'stealth' => true,
                    'status' => 'In development',
                ]),
            ],
            [
                'designation' => 'Akinci',
                'nato_designation' => null,
                'common_name' => 'Bayraktar Akinci',
                'country_code' => 'TR',
                'category_slug' => 'uav',
                'introduced_year' => 2021,
                'estimated_produced' => 30,
                'description' => 'High-altitude long-endurance UCAV with twin engines.',
                'specifications' => json_encode([
                    'wingspan_m' => 20,
                    'endurance_hours' => 24,
                    'ceiling_m' => 12200,
                    'payload_kg' => 1350,
                ]),
            ],

            // ========================================
            // EUROPEAN EQUIPMENT (Multi-national)
            // ========================================
            [
                'designation' => 'Eurofighter Typhoon',
                'nato_designation' => null,
                'common_name' => 'Typhoon',
                'country_code' => 'DE',
                'category_slug' => 'fighters',
                'introduced_year' => 2003,
                'estimated_produced' => 680,
                'description' => 'Twin-engine multirole fighter developed by European consortium (UK, Germany, Italy, Spain).',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 2,
                    'range_km' => 3790,
                    'hardpoints' => 13,
                    'operators' => ['Germany', 'UK', 'Italy', 'Spain', 'Austria', 'Saudi Arabia', 'Qatar', 'Kuwait'],
                ]),
            ],
            [
                'designation' => 'A400M Atlas',
                'nato_designation' => null,
                'common_name' => 'A400M Atlas',
                'country_code' => 'DE',
                'category_slug' => 'transport-aircraft',
                'introduced_year' => 2013,
                'estimated_produced' => 110,
                'description' => 'Four-engine turboprop military transport aircraft.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'payload_kg' => 37000,
                    'range_km' => 8700,
                    'max_speed_kmh' => 780,
                ]),
            ],
            [
                'designation' => 'NH90',
                'nato_designation' => null,
                'common_name' => 'NH90',
                'country_code' => 'DE',
                'category_slug' => 'transport-heli',
                'introduced_year' => 2006,
                'estimated_produced' => 450,
                'description' => 'Medium-sized military helicopter in tactical and naval variants.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'passengers' => 20,
                    'max_speed_kmh' => 300,
                    'range_km' => 800,
                ]),
            ],

            // ========================================
            // SWEDISH EQUIPMENT
            // ========================================
            [
                'designation' => 'JAS 39 Gripen E',
                'nato_designation' => null,
                'common_name' => 'Gripen E',
                'country_code' => 'SE',
                'category_slug' => 'fighters',
                'introduced_year' => 2019,
                'estimated_produced' => 96,
                'description' => 'Fourth-generation multirole fighter with low operating costs.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 2,
                    'range_km' => 3200,
                    'hardpoints' => 10,
                ]),
            ],
            [
                'designation' => 'Stridsvagn 122',
                'nato_designation' => null,
                'common_name' => 'Strv 122',
                'country_code' => 'SE',
                'category_slug' => 'mbt',
                'introduced_year' => 1997,
                'estimated_produced' => 120,
                'description' => 'Swedish variant of Leopard 2A5 with enhanced armor.',
                'specifications' => json_encode([
                    'crew' => 4,
                    'weight_tonnes' => 63,
                    'main_gun' => '120mm L44',
                    'engine' => '1500hp',
                ]),
            ],
            [
                'designation' => 'CV90',
                'nato_designation' => null,
                'common_name' => 'CV90',
                'country_code' => 'SE',
                'category_slug' => 'ifv',
                'introduced_year' => 1993,
                'estimated_produced' => 1300,
                'description' => 'Tracked infantry fighting vehicle family exported worldwide.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'passengers' => 8,
                    'weight_tonnes' => 35,
                    'main_armament' => '40mm Bofors',
                ]),
            ],
            [
                'designation' => 'Archer',
                'nato_designation' => null,
                'common_name' => 'Archer',
                'country_code' => 'SE',
                'category_slug' => 'spa',
                'introduced_year' => 2013,
                'estimated_produced' => 48,
                'description' => 'Fully automated 155mm self-propelled howitzer on Volvo truck chassis.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'main_gun' => '155mm L52',
                    'range_km' => 50,
                    'rate_of_fire' => '8 rounds/min',
                    'fully_automated' => true,
                ]),
            ],

            // ========================================
            // US NAVAL VESSELS
            // ========================================
            [
                'designation' => 'Gerald R. Ford-class',
                'nato_designation' => null,
                'common_name' => 'Gerald R. Ford',
                'country_code' => 'US',
                'category_slug' => 'carriers',
                'introduced_year' => 2017,
                'estimated_produced' => 1,
                'description' => 'Newest supercarrier class with electromagnetic catapults (EMALS). Replacing Nimitz-class on one-for-one basis.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 100000,
                    'length_m' => 337,
                    'aircraft' => 75,
                    'crew' => 4660,
                    'reactors' => 2,
                    'catapults' => 'EMALS',
                ]),
            ],
            [
                'designation' => 'Nimitz-class',
                'nato_designation' => null,
                'common_name' => 'Nimitz',
                'country_code' => 'US',
                'category_slug' => 'carriers',
                'introduced_year' => 1975,
                'estimated_produced' => 10,
                'description' => 'Nuclear-powered supercarrier, backbone of US Navy carrier force.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 100000,
                    'length_m' => 333,
                    'aircraft' => 85,
                    'crew' => 5700,
                    'reactors' => 2,
                ]),
            ],
            [
                'designation' => 'Arleigh Burke-class',
                'nato_designation' => null,
                'common_name' => 'Arleigh Burke',
                'country_code' => 'US',
                'category_slug' => 'destroyers',
                'introduced_year' => 1991,
                'estimated_produced' => 73,
                'description' => 'Guided-missile destroyer with Aegis combat system. Primary surface combatant of US Navy with 75 in service.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 9700,
                    'length_m' => 155,
                    'vls_cells' => 96,
                    'crew' => 329,
                    'speed_knots' => 30,
                    'aegis' => true,
                ]),
            ],
            [
                'designation' => 'Zumwalt-class',
                'nato_designation' => null,
                'common_name' => 'Zumwalt',
                'country_code' => 'US',
                'category_slug' => 'destroyers',
                'introduced_year' => 2016,
                'estimated_produced' => 3,
                'description' => 'Stealth guided-missile destroyer with tumblehome hull design.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 15900,
                    'length_m' => 190,
                    'vls_cells' => 80,
                    'crew' => 140,
                    'stealth' => true,
                ]),
            ],
            [
                'designation' => 'Constellation-class',
                'nato_designation' => null,
                'common_name' => 'Constellation',
                'country_code' => 'US',
                'category_slug' => 'frigates',
                'introduced_year' => 2029,
                'estimated_produced' => 0,
                'description' => 'Modern multi-mission guided-missile frigate based on FREMM design. Up to 20 planned.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 7300,
                    'length_m' => 151,
                    'vls_cells' => 32,
                    'crew' => 200,
                    'status' => 'Under construction',
                ]),
            ],
            [
                'designation' => 'Virginia-class',
                'nato_designation' => null,
                'common_name' => 'Virginia',
                'country_code' => 'US',
                'category_slug' => 'submarines',
                'introduced_year' => 2004,
                'estimated_produced' => 23,
                'description' => 'Nuclear-powered attack submarine with modular payload capability.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 7900,
                    'length_m' => 115,
                    'torpedoes' => 4,
                    'vls_cells' => 12,
                    'crew' => 134,
                    'depth_m' => 240,
                ]),
            ],

            // ========================================
            // MORE US EQUIPMENT
            // ========================================
            [
                'designation' => 'F-22 Raptor',
                'nato_designation' => null,
                'common_name' => 'F-22 Raptor',
                'country_code' => 'US',
                'category_slug' => 'fighters',
                'introduced_year' => 2005,
                'estimated_produced' => 195,
                'description' => 'Fifth-generation stealth air superiority fighter. Most advanced air-to-air fighter in service, export banned.',
                'specifications' => json_encode([
                    'crew' => 1,
                    'max_speed_mach' => 2.25,
                    'range_km' => 2960,
                    'stealth' => true,
                    'supercruise' => true,
                    'thrust_vectoring' => true,
                ]),
            ],
            [
                'designation' => 'M1126 Stryker',
                'nato_designation' => null,
                'common_name' => 'Stryker',
                'country_code' => 'US',
                'category_slug' => 'apc',
                'introduced_year' => 2002,
                'estimated_produced' => 4500,
                'description' => '8-wheeled armored vehicle family. Infantry Carrier Vehicle carries 9-man squad plus crew of 2. Can reach 60+ mph with 300+ mile range.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'passengers' => 9,
                    'wheels' => '8x8',
                    'weight_tonnes' => 19,
                    'max_speed_kmh' => 97,
                    'range_km' => 500,
                    'variants' => 10,
                ]),
            ],
            [
                'designation' => 'M1296 Dragoon',
                'nato_designation' => null,
                'common_name' => 'Stryker Dragoon',
                'country_code' => 'US',
                'category_slug' => 'ifv',
                'introduced_year' => 2017,
                'estimated_produced' => 83,
                'description' => 'First Stryker variant equipped as IFV with 30mm cannon and airburst munitions.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'passengers' => 6,
                    'main_armament' => '30mm XM813 autocannon',
                    'weight_tonnes' => 20,
                ]),
            ],
            [
                'designation' => 'UH-60M Black Hawk',
                'nato_designation' => null,
                'common_name' => 'Black Hawk',
                'country_code' => 'US',
                'category_slug' => 'transport-heli',
                'introduced_year' => 1979,
                'estimated_produced' => 4000,
                'description' => 'Medium-lift utility helicopter, most widely used military helicopter.',
                'specifications' => json_encode([
                    'crew' => 4,
                    'passengers' => 14,
                    'max_speed_kmh' => 295,
                    'range_km' => 590,
                ]),
            ],
            [
                'designation' => 'CH-47F Chinook',
                'nato_designation' => null,
                'common_name' => 'Chinook',
                'country_code' => 'US',
                'category_slug' => 'transport-heli',
                'introduced_year' => 1962,
                'estimated_produced' => 1200,
                'description' => 'Twin-rotor heavy-lift helicopter.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'passengers' => 55,
                    'max_speed_kmh' => 315,
                    'payload_kg' => 12700,
                ]),
            ],
            [
                'designation' => 'B-2 Spirit',
                'nato_designation' => null,
                'common_name' => 'B-2 Spirit',
                'country_code' => 'US',
                'category_slug' => 'bombers',
                'introduced_year' => 1997,
                'estimated_produced' => 21,
                'description' => 'Stealth strategic bomber with flying wing design.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'max_speed_kmh' => 1010,
                    'range_km' => 11100,
                    'payload_kg' => 23000,
                    'stealth' => true,
                ]),
            ],
            [
                'designation' => 'B-21 Raider',
                'nato_designation' => null,
                'common_name' => 'B-21 Raider',
                'country_code' => 'US',
                'category_slug' => 'bombers',
                'introduced_year' => 2027,
                'estimated_produced' => 0,
                'description' => 'Next-generation stealth bomber under development. 100+ planned.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'stealth' => true,
                    'nuclear_capable' => true,
                    'status' => 'In development',
                ]),
            ],
            [
                'designation' => 'MQ-9 Reaper',
                'nato_designation' => null,
                'common_name' => 'Reaper',
                'country_code' => 'US',
                'category_slug' => 'uav',
                'introduced_year' => 2007,
                'estimated_produced' => 400,
                'description' => 'Medium-altitude long-endurance unmanned combat aerial vehicle.',
                'specifications' => json_encode([
                    'wingspan_m' => 20,
                    'endurance_hours' => 27,
                    'ceiling_m' => 15000,
                    'payload_kg' => 1700,
                    'hardpoints' => 7,
                ]),
            ],
            [
                'designation' => 'M270 MLRS',
                'nato_designation' => null,
                'common_name' => 'MLRS',
                'country_code' => 'US',
                'category_slug' => 'mlrs',
                'introduced_year' => 1983,
                'estimated_produced' => 1300,
                'description' => 'Multiple Launch Rocket System on tracked chassis.',
                'specifications' => json_encode([
                    'rockets' => 12,
                    'caliber' => '227mm',
                    'range_km' => 300,
                    'crew' => 3,
                ]),
            ],
            [
                'designation' => 'MGM-140 ATACMS',
                'nato_designation' => null,
                'common_name' => 'ATACMS',
                'country_code' => 'US',
                'category_slug' => 'ballistic',
                'introduced_year' => 1991,
                'estimated_produced' => 3700,
                'description' => 'Army Tactical Missile System for MLRS/HIMARS.',
                'specifications' => json_encode([
                    'range_km' => 300,
                    'warhead_kg' => 230,
                    'guidance' => 'GPS + INS',
                ]),
            ],
            [
                'designation' => 'PrSM',
                'nato_designation' => null,
                'common_name' => 'Precision Strike Missile',
                'country_code' => 'US',
                'category_slug' => 'ballistic',
                'introduced_year' => 2024,
                'estimated_produced' => 100,
                'description' => 'GPS-guided missile replacing ATACMS with extended range. Range 310-400 miles.',
                'specifications' => json_encode([
                    'range_km' => 650,
                    'guidance' => 'GPS',
                    'platforms' => ['HIMARS', 'MLRS'],
                ]),
            ],

            // ========================================
            // RUSSIAN NAVAL VESSELS
            // ========================================
            [
                'designation' => 'Admiral Kuznetsov',
                'nato_designation' => null,
                'common_name' => 'Admiral Kuznetsov',
                'country_code' => 'RU',
                'category_slug' => 'carriers',
                'introduced_year' => 1990,
                'estimated_produced' => 1,
                'description' => 'Russia\'s only aircraft carrier, STOBAR configuration.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 55000,
                    'length_m' => 305,
                    'aircraft' => 33,
                    'crew' => 2000,
                ]),
            ],
            [
                'designation' => 'Admiral Gorshkov-class',
                'nato_designation' => null,
                'common_name' => 'Admiral Gorshkov',
                'country_code' => 'RU',
                'category_slug' => 'frigates',
                'introduced_year' => 2018,
                'estimated_produced' => 4,
                'description' => 'Modern guided-missile frigate with Zircon hypersonic missiles.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 5400,
                    'length_m' => 135,
                    'vls_cells' => 32,
                    'crew' => 210,
                ]),
            ],
            [
                'designation' => 'Borei-class',
                'nato_designation' => 'Dolgorukiy-class',
                'common_name' => 'Borei',
                'country_code' => 'RU',
                'category_slug' => 'submarines',
                'introduced_year' => 2013,
                'estimated_produced' => 5,
                'description' => 'Nuclear-powered ballistic missile submarine (SSBN).',
                'specifications' => json_encode([
                    'displacement_tonnes' => 24000,
                    'length_m' => 170,
                    'missiles' => 16,
                    'crew' => 107,
                    'slbm' => 'Bulava',
                ]),
            ],
            [
                'designation' => 'Yasen-class',
                'nato_designation' => 'Graney-class',
                'common_name' => 'Yasen',
                'country_code' => 'RU',
                'category_slug' => 'submarines',
                'introduced_year' => 2014,
                'estimated_produced' => 3,
                'description' => 'Nuclear-powered cruise missile submarine (SSGN).',
                'specifications' => json_encode([
                    'displacement_tonnes' => 13800,
                    'length_m' => 139,
                    'torpedoes' => 10,
                    'missiles' => 32,
                ]),
            ],

            // ========================================
            // MORE RUSSIAN EQUIPMENT
            // ========================================
            [
                'designation' => 'T-14 Armata',
                'nato_designation' => null,
                'common_name' => 'T-14 Armata',
                'country_code' => 'RU',
                'category_slug' => 'mbt',
                'introduced_year' => 2021,
                'estimated_produced' => 20,
                'description' => 'Next-generation main battle tank with unmanned turret and crew capsule.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'weight_tonnes' => 55,
                    'main_gun' => '125mm 2A82-1M',
                    'engine' => '1500hp',
                    'aps' => 'Afganit',
                    'unmanned_turret' => true,
                ]),
            ],
            [
                'designation' => 'Pantsir-S1',
                'nato_designation' => 'SA-22 Greyhound',
                'common_name' => 'Pantsir-S1',
                'country_code' => 'RU',
                'category_slug' => 'sam',
                'introduced_year' => 2012,
                'estimated_produced' => 200,
                'description' => 'Combined short-range missile and gun system for point defense.',
                'specifications' => json_encode([
                    'missiles' => 12,
                    'guns' => '2x 30mm',
                    'range_km' => 20,
                    'altitude_km' => 15,
                ]),
            ],
            [
                'designation' => 'Iskander-M',
                'nato_designation' => 'SS-26 Stone',
                'common_name' => 'Iskander-M',
                'country_code' => 'RU',
                'category_slug' => 'ballistic',
                'introduced_year' => 2006,
                'estimated_produced' => 500,
                'description' => 'Short-range ballistic missile system.',
                'specifications' => json_encode([
                    'range_km' => 500,
                    'cep_m' => 5,
                    'warhead_kg' => 700,
                    'speed_mach' => 7,
                ]),
            ],
            [
                'designation' => 'Kh-101',
                'nato_designation' => 'AS-23 Kodiak',
                'common_name' => 'Kh-101',
                'country_code' => 'RU',
                'category_slug' => 'cruise',
                'introduced_year' => 2012,
                'estimated_produced' => 1000,
                'description' => 'Air-launched stealth cruise missile.',
                'specifications' => json_encode([
                    'range_km' => 4500,
                    'speed_kmh' => 970,
                    'warhead_kg' => 400,
                    'guidance' => 'INS + GLONASS + terrain',
                ]),
            ],
            [
                'designation' => 'Mi-24P',
                'nato_designation' => 'Hind',
                'common_name' => 'Mi-24P Hind',
                'country_code' => 'RU',
                'category_slug' => 'attack-heli',
                'introduced_year' => 1981,
                'estimated_produced' => 2500,
                'description' => 'Large attack helicopter that can also transport troops.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'passengers' => 8,
                    'max_speed_kmh' => 335,
                    'main_armament' => '30mm GSh-30K',
                ]),
            ],
            [
                'designation' => 'Mi-8/17',
                'nato_designation' => 'Hip',
                'common_name' => 'Mi-8',
                'country_code' => 'RU',
                'category_slug' => 'transport-heli',
                'introduced_year' => 1967,
                'estimated_produced' => 17000,
                'description' => 'Most-produced helicopter in history, transport and assault versions.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'passengers' => 24,
                    'max_speed_kmh' => 250,
                    'range_km' => 465,
                ]),
            ],
            [
                'designation' => 'Orlan-10',
                'nato_designation' => null,
                'common_name' => 'Orlan-10',
                'country_code' => 'RU',
                'category_slug' => 'uav',
                'introduced_year' => 2010,
                'estimated_produced' => 3000,
                'description' => 'Reconnaissance UAV widely used for artillery spotting.',
                'specifications' => json_encode([
                    'wingspan_m' => 3.1,
                    'endurance_hours' => 16,
                    'ceiling_m' => 5000,
                    'payload_kg' => 5,
                ]),
            ],
            [
                'designation' => 'Lancet',
                'nato_designation' => null,
                'common_name' => 'Lancet',
                'country_code' => 'RU',
                'category_slug' => 'uav',
                'introduced_year' => 2021,
                'estimated_produced' => 5000,
                'description' => 'Loitering munition (kamikaze drone) widely used in Ukraine.',
                'specifications' => json_encode([
                    'wingspan_m' => 2.4,
                    'endurance_min' => 40,
                    'range_km' => 70,
                    'warhead_kg' => 5,
                ]),
            ],
            [
                'designation' => '2S35 Koalitsiya-SV',
                'nato_designation' => null,
                'common_name' => 'Koalitsiya-SV',
                'country_code' => 'RU',
                'category_slug' => 'spa',
                'introduced_year' => 2020,
                'estimated_produced' => 12,
                'description' => 'Next-generation self-propelled 152mm howitzer with autoloader.',
                'specifications' => json_encode([
                    'crew' => 3,
                    'main_gun' => '152mm 2A88',
                    'range_km' => 70,
                    'rate_of_fire' => '16 rounds/min',
                ]),
            ],
            [
                'designation' => 'BM-30 Smerch',
                'nato_designation' => null,
                'common_name' => 'Smerch',
                'country_code' => 'RU',
                'category_slug' => 'mlrs',
                'introduced_year' => 1987,
                'estimated_produced' => 200,
                'description' => 'Heavy 300mm multiple rocket launcher.',
                'specifications' => json_encode([
                    'tubes' => 12,
                    'caliber' => '300mm',
                    'range_km' => 90,
                ]),
            ],
            [
                'designation' => 'TOS-1A Solntsepyok',
                'nato_designation' => null,
                'common_name' => 'TOS-1A',
                'country_code' => 'RU',
                'category_slug' => 'mlrs',
                'introduced_year' => 2001,
                'estimated_produced' => 50,
                'description' => 'Thermobaric multiple rocket launcher on tank chassis.',
                'specifications' => json_encode([
                    'tubes' => 24,
                    'caliber' => '220mm',
                    'range_km' => 6,
                    'warhead' => 'thermobaric',
                ]),
            ],
            [
                'designation' => 'MiG-31BM',
                'nato_designation' => 'Foxhound',
                'common_name' => 'MiG-31BM',
                'country_code' => 'RU',
                'category_slug' => 'fighters',
                'introduced_year' => 2008,
                'estimated_produced' => 100,
                'description' => 'Modernized supersonic interceptor for Kinzhal missile.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'max_speed_mach' => 2.83,
                    'range_km' => 3000,
                    'radar_range_km' => 400,
                ]),
            ],
            [
                'designation' => 'Kh-47M2 Kinzhal',
                'nato_designation' => 'AS-24 Killjoy',
                'common_name' => 'Kinzhal',
                'country_code' => 'RU',
                'category_slug' => 'ballistic',
                'introduced_year' => 2018,
                'estimated_produced' => 100,
                'description' => 'Air-launched hypersonic aeroballistic missile.',
                'specifications' => json_encode([
                    'speed_mach' => 10,
                    'range_km' => 2000,
                    'warhead_kg' => 480,
                    'platform' => 'MiG-31K',
                ]),
            ],

            // ========================================
            // UK NAVAL VESSELS
            // ========================================
            [
                'designation' => 'Queen Elizabeth-class',
                'nato_designation' => null,
                'common_name' => 'HMS Queen Elizabeth',
                'country_code' => 'GB',
                'category_slug' => 'carriers',
                'introduced_year' => 2017,
                'estimated_produced' => 2,
                'description' => 'Largest warships ever built for Royal Navy, STOVL configuration for F-35B.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 65000,
                    'length_m' => 284,
                    'aircraft' => 40,
                    'crew' => 1600,
                ]),
            ],
            [
                'designation' => 'Type 45',
                'nato_designation' => 'Daring-class',
                'common_name' => 'Type 45 Destroyer',
                'country_code' => 'GB',
                'category_slug' => 'destroyers',
                'introduced_year' => 2009,
                'estimated_produced' => 6,
                'description' => 'Air defence destroyer with PAAMS missile system.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 8500,
                    'length_m' => 152,
                    'vls_cells' => 48,
                    'crew' => 191,
                ]),
            ],
            [
                'designation' => 'Type 26',
                'nato_designation' => 'City-class',
                'common_name' => 'Type 26 Frigate',
                'country_code' => 'GB',
                'category_slug' => 'frigates',
                'introduced_year' => 2027,
                'estimated_produced' => 0,
                'description' => 'Anti-submarine warfare frigate under construction. 8 planned for UK.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 8000,
                    'length_m' => 149,
                    'vls_cells' => 24,
                    'status' => 'Under construction',
                ]),
            ],
            [
                'designation' => 'Astute-class',
                'nato_designation' => null,
                'common_name' => 'Astute',
                'country_code' => 'GB',
                'category_slug' => 'submarines',
                'introduced_year' => 2010,
                'estimated_produced' => 5,
                'description' => 'Nuclear-powered attack submarine (SSN). 7 planned.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 7400,
                    'length_m' => 97,
                    'torpedoes' => 6,
                    'tomahawks' => 38,
                ]),
            ],

            // ========================================
            // FRENCH NAVAL VESSELS
            // ========================================
            [
                'designation' => 'Charles de Gaulle',
                'nato_designation' => null,
                'common_name' => 'Charles de Gaulle',
                'country_code' => 'FR',
                'category_slug' => 'carriers',
                'introduced_year' => 2001,
                'estimated_produced' => 1,
                'description' => 'France\'s only aircraft carrier, nuclear-powered with CATOBAR.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 42500,
                    'length_m' => 261,
                    'aircraft' => 40,
                    'crew' => 1950,
                    'nuclear' => true,
                ]),
            ],
            [
                'designation' => 'FREMM',
                'nato_designation' => 'Aquitaine-class',
                'common_name' => 'FREMM Frigate',
                'country_code' => 'FR',
                'category_slug' => 'frigates',
                'introduced_year' => 2012,
                'estimated_produced' => 8,
                'description' => 'Multi-mission frigate, basis for US Constellation-class.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 6000,
                    'length_m' => 142,
                    'vls_cells' => 32,
                    'crew' => 145,
                ]),
            ],
            [
                'designation' => 'Barracuda-class',
                'nato_designation' => 'Suffren-class',
                'common_name' => 'Barracuda',
                'country_code' => 'FR',
                'category_slug' => 'submarines',
                'introduced_year' => 2022,
                'estimated_produced' => 2,
                'description' => 'Nuclear-powered attack submarine. 6 planned.',
                'specifications' => json_encode([
                    'displacement_tonnes' => 5300,
                    'length_m' => 99,
                    'torpedoes' => 4,
                    'missiles' => 'SCALP Naval',
                ]),
            ],
            [
                'designation' => 'Tigre',
                'nato_designation' => null,
                'common_name' => 'Eurocopter Tiger',
                'country_code' => 'FR',
                'category_slug' => 'attack-heli',
                'introduced_year' => 2003,
                'estimated_produced' => 180,
                'description' => 'Franco-German attack helicopter.',
                'specifications' => json_encode([
                    'crew' => 2,
                    'max_speed_kmh' => 290,
                    'range_km' => 800,
                    'main_armament' => '30mm GIAT cannon',
                ]),
            ],
        ];

        foreach ($equipment as $item) {
            $countryId = $countries[$item['country_code']] ?? null;
            $categoryId = $categories[$item['category_slug']] ?? null;

            if (!$countryId || !$categoryId) {
                $this->command->warn("Skipping {$item['designation']}: Missing country or category");
                continue;
            }

            DB::table('military_equipment')->updateOrInsert(
                ['designation' => $item['designation']],
                [
                    'uuid' => Str::uuid(),
                    'designation' => $item['designation'],
                    'nato_designation' => $item['nato_designation'],
                    'common_name' => $item['common_name'],
                    'country_id' => $countryId,
                    'category_id' => $categoryId,
                    'introduced_year' => $item['introduced_year'],
                    'estimated_produced' => $item['estimated_produced'],
                    'description' => $item['description'],
                    'specifications' => $item['specifications'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
