<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            // OSINT Skills
            [
                'name' => 'Geolocation Analysis',
                'description' => 'Analyze images and videos to determine their geographic location using visual clues, landmarks, and environmental features.',
                'keywords' => ['geolocation', 'geolocate', 'location', 'where', 'place', 'coordinates', 'find location', 'identify location', 'map', 'landmark'],
                'aliases' => ['geo analysis', 'location finding', 'image geolocation', 'photo location'],
                'category' => Skill::CATEGORY_GEOLOCATION,
                'icon' => 'map-pin',
                'capabilities' => [
                    'Analyze visual clues in images',
                    'Identify landmarks and geographical features',
                    'Cross-reference with satellite imagery',
                    'Determine coordinates from visual evidence',
                    'Verify claimed locations',
                ],
                'required_inputs' => ['image_url', 'context'],
                'output_format' => [
                    'coordinates' => ['latitude', 'longitude'],
                    'confidence' => 'percentage',
                    'evidence' => 'array of clues',
                ],
                'instructions' => 'Analyze the provided image or video for geographical indicators. Look for: road signs, building styles, vegetation, sun position, terrain features, language on signs, vehicle types, and architectural styles.',
                'example_prompts' => [
                    'Where was this photo taken?',
                    'Can you geolocate this image?',
                    'What location does this video show?',
                    'Find the coordinates of this place',
                ],
                'priority' => 90,
                'match_threshold' => 0.15,
            ],
            [
                'name' => 'Image Verification',
                'description' => 'Verify the authenticity of images by checking for manipulation, reverse image search, and metadata analysis.',
                'keywords' => ['verify', 'verification', 'authentic', 'fake', 'real', 'manipulated', 'photoshop', 'edited', 'original', 'deepfake'],
                'aliases' => ['image check', 'photo verification', 'authenticity check', 'fake detection'],
                'category' => Skill::CATEGORY_VERIFICATION,
                'icon' => 'shield-check',
                'capabilities' => [
                    'Detect image manipulation',
                    'Analyze EXIF metadata',
                    'Perform reverse image search',
                    'Identify AI-generated images',
                    'Check for inconsistencies',
                ],
                'required_inputs' => ['image_url'],
                'output_format' => [
                    'is_authentic' => 'boolean',
                    'confidence' => 'percentage',
                    'findings' => 'array',
                ],
                'instructions' => 'Examine the image for signs of manipulation: lighting inconsistencies, edge artifacts, clone stamping, perspective errors, and metadata anomalies.',
                'example_prompts' => [
                    'Is this image authentic?',
                    'Has this photo been manipulated?',
                    'Verify if this image is real',
                    'Check this photo for editing',
                ],
                'priority' => 85,
                'match_threshold' => 0.15,
            ],
            [
                'name' => 'Video Analysis',
                'description' => 'Analyze video content for authenticity, timeline reconstruction, and evidence extraction.',
                'keywords' => ['video', 'footage', 'clip', 'recording', 'film', 'analyze video', 'video evidence'],
                'aliases' => ['footage analysis', 'video verification', 'video examination'],
                'category' => Skill::CATEGORY_MEDIA,
                'icon' => 'video',
                'capabilities' => [
                    'Extract frames for analysis',
                    'Verify video authenticity',
                    'Timeline reconstruction',
                    'Audio analysis',
                    'Object and person tracking',
                ],
                'required_inputs' => ['video_url'],
                'output_format' => [
                    'analysis' => 'object',
                    'timeline' => 'array',
                    'key_frames' => 'array',
                ],
                'instructions' => 'Analyze the video frame by frame. Look for: temporal inconsistencies, audio-video sync issues, compression artifacts, and visual anomalies.',
                'example_prompts' => [
                    'Analyze this video',
                    'What does this footage show?',
                    'Extract key information from this video',
                ],
                'priority' => 80,
                'match_threshold' => 0.2,
            ],
            [
                'name' => 'Military Equipment Identification',
                'description' => 'Identify military vehicles, weapons, and equipment from images and videos.',
                'keywords' => ['military', 'weapon', 'tank', 'aircraft', 'vehicle', 'equipment', 'identify', 'army', 'navy', 'air force', 'missile', 'artillery', 'helicopter', 'jet', 'rifle', 'armored'],
                'aliases' => ['equipment id', 'weapon identification', 'military analysis', 'vehicle identification'],
                'category' => Skill::CATEGORY_MILITARY,
                'icon' => 'shield',
                'capabilities' => [
                    'Identify vehicle types and models',
                    'Recognize weapon systems',
                    'Determine country of origin',
                    'Assess equipment condition',
                    'Cross-reference with military databases',
                ],
                'required_inputs' => ['image_url'],
                'output_format' => [
                    'equipment' => 'array of identified items',
                    'confidence' => 'percentage per item',
                    'details' => 'specifications',
                ],
                'instructions' => 'Examine the image for military equipment. Identify: vehicle silhouettes, weapon configurations, unit markings, camouflage patterns, and distinctive features.',
                'example_prompts' => [
                    'What tank is this?',
                    'Identify this military vehicle',
                    'What weapon system is shown?',
                    'What aircraft is in this photo?',
                ],
                'priority' => 95,
                'match_threshold' => 0.15,
            ],
            [
                'name' => 'Social Media Investigation',
                'description' => 'Investigate social media accounts and posts for intelligence gathering and verification.',
                'keywords' => ['social media', 'twitter', 'facebook', 'telegram', 'instagram', 'account', 'profile', 'post', 'investigate', 'research'],
                'aliases' => ['socmint', 'social investigation', 'account analysis', 'profile research'],
                'category' => Skill::CATEGORY_OSINT,
                'icon' => 'users',
                'capabilities' => [
                    'Profile analysis',
                    'Network mapping',
                    'Content verification',
                    'Timeline reconstruction',
                    'Cross-platform correlation',
                ],
                'required_inputs' => ['account_url', 'platform'],
                'output_format' => [
                    'profile' => 'object',
                    'connections' => 'array',
                    'activity_pattern' => 'object',
                ],
                'instructions' => 'Analyze the social media presence: posting patterns, connections, content themes, location indicators, and account authenticity markers.',
                'example_prompts' => [
                    'Analyze this social media account',
                    'What can you find about this profile?',
                    'Investigate this Twitter account',
                ],
                'priority' => 75,
                'match_threshold' => 0.2,
            ],
            [
                'name' => 'Timeline Reconstruction',
                'description' => 'Build chronological timelines of events from multiple sources and evidence.',
                'keywords' => ['timeline', 'chronology', 'when', 'sequence', 'order', 'events', 'time', 'date', 'history'],
                'aliases' => ['event timeline', 'chronological analysis', 'time mapping'],
                'category' => Skill::CATEGORY_ANALYSIS,
                'icon' => 'clock',
                'capabilities' => [
                    'Correlate timestamps across sources',
                    'Identify temporal inconsistencies',
                    'Build event sequences',
                    'Cross-reference with known events',
                    'Visualize timelines',
                ],
                'required_inputs' => ['events', 'sources'],
                'output_format' => [
                    'timeline' => 'array of dated events',
                    'gaps' => 'array of unknown periods',
                    'conflicts' => 'array of inconsistencies',
                ],
                'instructions' => 'Collect all temporal data points and arrange chronologically. Identify gaps, conflicts, and correlations with external events.',
                'example_prompts' => [
                    'Build a timeline of these events',
                    'When did this happen?',
                    'What is the sequence of events?',
                ],
                'priority' => 70,
                'match_threshold' => 0.2,
            ],
            [
                'name' => 'Language Translation',
                'description' => 'Translate text, documents, and media content between languages.',
                'keywords' => ['translate', 'translation', 'language', 'interpret', 'foreign', 'russian', 'ukrainian', 'arabic', 'chinese', 'spanish'],
                'aliases' => ['translator', 'language conversion', 'text translation'],
                'category' => Skill::CATEGORY_TRANSLATION,
                'icon' => 'globe',
                'capabilities' => [
                    'Text translation',
                    'Document translation',
                    'Script identification',
                    'Contextual translation',
                    'Technical terminology',
                ],
                'required_inputs' => ['text', 'source_language', 'target_language'],
                'output_format' => [
                    'translation' => 'string',
                    'detected_language' => 'string',
                    'confidence' => 'percentage',
                ],
                'instructions' => 'Translate the provided content while maintaining context and technical accuracy. Identify idioms and cultural references.',
                'example_prompts' => [
                    'Translate this text',
                    'What does this say in English?',
                    'Translate from Russian',
                ],
                'priority' => 65,
                'match_threshold' => 0.2,
            ],
            [
                'name' => 'Satellite Imagery Analysis',
                'description' => 'Analyze satellite and aerial imagery for changes, structures, and military activity.',
                'keywords' => ['satellite', 'aerial', 'imagery', 'overhead', 'space', 'earth observation', 'sentinel', 'maxar', 'planet'],
                'aliases' => ['sat imagery', 'overhead analysis', 'space imagery'],
                'category' => Skill::CATEGORY_GEOLOCATION,
                'icon' => 'satellite',
                'capabilities' => [
                    'Change detection',
                    'Structure identification',
                    'Damage assessment',
                    'Activity pattern analysis',
                    'Measurement and scaling',
                ],
                'required_inputs' => ['image_url', 'coordinates'],
                'output_format' => [
                    'features' => 'array',
                    'changes' => 'array',
                    'measurements' => 'object',
                ],
                'instructions' => 'Analyze satellite imagery for: military installations, vehicle movements, structural damage, construction activity, and terrain features.',
                'example_prompts' => [
                    'Analyze this satellite image',
                    'What changes are visible in these images?',
                    'Identify structures in this aerial photo',
                ],
                'priority' => 85,
                'match_threshold' => 0.2,
            ],
            [
                'name' => 'Document Analysis',
                'description' => 'Analyze documents for authenticity, extract information, and identify sources.',
                'keywords' => ['document', 'paper', 'report', 'file', 'letter', 'official', 'analyze document', 'extract', 'pdf'],
                'aliases' => ['doc analysis', 'paper analysis', 'file examination'],
                'category' => Skill::CATEGORY_ANALYSIS,
                'icon' => 'file-text',
                'capabilities' => [
                    'Text extraction',
                    'Authenticity verification',
                    'Metadata analysis',
                    'Format identification',
                    'Content summarization',
                ],
                'required_inputs' => ['document_url'],
                'output_format' => [
                    'content' => 'string',
                    'metadata' => 'object',
                    'authenticity' => 'object',
                ],
                'instructions' => 'Extract and analyze document content. Check for: formatting consistency, official markers, metadata, and content authenticity.',
                'example_prompts' => [
                    'Analyze this document',
                    'What information is in this file?',
                    'Is this document authentic?',
                ],
                'priority' => 70,
                'match_threshold' => 0.2,
            ],
            [
                'name' => 'Conflict Mapping',
                'description' => 'Map conflict zones, front lines, and military positions from multiple sources.',
                'keywords' => ['conflict', 'war', 'battle', 'front line', 'position', 'territory', 'control', 'advance', 'retreat', 'offensive'],
                'aliases' => ['war mapping', 'battle mapping', 'military mapping'],
                'category' => Skill::CATEGORY_MILITARY,
                'icon' => 'map',
                'capabilities' => [
                    'Front line mapping',
                    'Territory control analysis',
                    'Position verification',
                    'Movement tracking',
                    'Strategic analysis',
                ],
                'required_inputs' => ['sources', 'region'],
                'output_format' => [
                    'map_data' => 'geojson',
                    'positions' => 'array',
                    'analysis' => 'string',
                ],
                'instructions' => 'Aggregate information from multiple sources to map conflict zones. Cross-reference claims with verified imagery and reports.',
                'example_prompts' => [
                    'Map the current front lines',
                    'Where is fighting happening?',
                    'Show territorial control',
                ],
                'priority' => 88,
                'match_threshold' => 0.2,
            ],
            [
                'name' => 'Casualty Verification',
                'description' => 'Verify reported casualties and losses using open source evidence.',
                'keywords' => ['casualty', 'casualties', 'losses', 'killed', 'wounded', 'destroyed', 'damage', 'loss'],
                'aliases' => ['loss verification', 'damage assessment', 'casualty count'],
                'category' => Skill::CATEGORY_VERIFICATION,
                'icon' => 'alert-triangle',
                'capabilities' => [
                    'Visual evidence verification',
                    'Cross-referencing reports',
                    'Equipment loss tracking',
                    'Personnel casualty verification',
                    'Source reliability assessment',
                ],
                'required_inputs' => ['claim', 'evidence'],
                'output_format' => [
                    'verified' => 'boolean',
                    'confidence' => 'percentage',
                    'evidence' => 'array',
                ],
                'instructions' => 'Verify casualty claims by cross-referencing visual evidence, official statements, and independent reports. Assess source reliability.',
                'example_prompts' => [
                    'Verify these reported losses',
                    'Is this casualty claim accurate?',
                    'How many confirmed losses?',
                ],
                'priority' => 80,
                'match_threshold' => 0.2,
            ],
            [
                'name' => 'Network Analysis',
                'description' => 'Map relationships and connections between entities, organizations, and individuals.',
                'keywords' => ['network', 'connection', 'relationship', 'link', 'association', 'organization', 'structure', 'hierarchy'],
                'aliases' => ['link analysis', 'relationship mapping', 'connection analysis'],
                'category' => Skill::CATEGORY_ANALYSIS,
                'icon' => 'share-2',
                'capabilities' => [
                    'Entity relationship mapping',
                    'Organizational structure analysis',
                    'Connection strength assessment',
                    'Pattern identification',
                    'Visualization generation',
                ],
                'required_inputs' => ['entities', 'data_sources'],
                'output_format' => [
                    'nodes' => 'array',
                    'edges' => 'array',
                    'clusters' => 'array',
                ],
                'instructions' => 'Identify and map connections between entities. Analyze: communication patterns, financial links, organizational roles, and historical associations.',
                'example_prompts' => [
                    'Map the connections between these entities',
                    'Who is connected to this organization?',
                    'Show the network structure',
                ],
                'priority' => 72,
                'match_threshold' => 0.2,
            ],
            [
                'name' => 'Open Source Research',
                'description' => 'Conduct comprehensive research using publicly available sources and databases.',
                'keywords' => ['research', 'search', 'find', 'lookup', 'discover', 'information', 'data', 'source', 'investigate'],
                'aliases' => ['osint research', 'information gathering', 'data collection'],
                'category' => Skill::CATEGORY_RESEARCH,
                'icon' => 'search',
                'capabilities' => [
                    'Multi-source research',
                    'Database querying',
                    'Public records search',
                    'Academic research',
                    'News monitoring',
                ],
                'required_inputs' => ['query', 'scope'],
                'output_format' => [
                    'results' => 'array',
                    'sources' => 'array',
                    'summary' => 'string',
                ],
                'instructions' => 'Conduct thorough research using multiple open sources. Verify information across sources and assess reliability.',
                'example_prompts' => [
                    'Research this topic',
                    'Find information about...',
                    'What sources mention this?',
                ],
                'priority' => 60,
                'match_threshold' => 0.25,
            ],
            [
                'name' => 'Weather and Environmental Analysis',
                'description' => 'Analyze weather conditions and environmental factors for verification and context.',
                'keywords' => ['weather', 'environment', 'climate', 'sun', 'shadow', 'rain', 'snow', 'wind', 'temperature', 'season'],
                'aliases' => ['weather analysis', 'environmental verification', 'chronolocation'],
                'category' => Skill::CATEGORY_VERIFICATION,
                'icon' => 'cloud',
                'capabilities' => [
                    'Weather verification',
                    'Shadow analysis for time',
                    'Seasonal indicators',
                    'Environmental cross-referencing',
                    'Historical weather lookup',
                ],
                'required_inputs' => ['image_url', 'claimed_date', 'claimed_location'],
                'output_format' => [
                    'weather_match' => 'boolean',
                    'time_estimate' => 'string',
                    'confidence' => 'percentage',
                ],
                'instructions' => 'Analyze environmental indicators in media. Compare with historical weather data to verify claimed time and location.',
                'example_prompts' => [
                    'What time of day was this taken?',
                    'Does the weather match the claimed date?',
                    'Analyze the shadows in this image',
                ],
                'priority' => 68,
                'match_threshold' => 0.2,
            ],
            [
                'name' => 'Unit and Insignia Identification',
                'description' => 'Identify military units, insignia, patches, and markings.',
                'keywords' => ['unit', 'insignia', 'patch', 'badge', 'marking', 'emblem', 'symbol', 'division', 'brigade', 'battalion'],
                'aliases' => ['unit id', 'insignia identification', 'patch identification'],
                'category' => Skill::CATEGORY_MILITARY,
                'icon' => 'award',
                'capabilities' => [
                    'Unit insignia recognition',
                    'Military patch identification',
                    'Vehicle markings analysis',
                    'Uniform identification',
                    'Order of battle research',
                ],
                'required_inputs' => ['image_url'],
                'output_format' => [
                    'unit' => 'object',
                    'country' => 'string',
                    'confidence' => 'percentage',
                ],
                'instructions' => 'Identify military insignia, patches, and unit markings. Cross-reference with known databases and order of battle information.',
                'example_prompts' => [
                    'What unit is this insignia from?',
                    'Identify this military patch',
                    'What do these vehicle markings mean?',
                ],
                'priority' => 82,
                'match_threshold' => 0.2,
            ],
        ];

        foreach ($skills as $skillData) {
            Skill::updateOrCreate(
                ['name' => $skillData['name']],
                array_merge($skillData, ['uuid' => Str::uuid()])
            );
        }

        $this->command->info('Created ' . count($skills) . ' default OSINT skills.');
    }
}
