<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TrainingEnvironmentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Creates training environments and scenarios for OSINT skill development
     * ranging from beginner tutorials to advanced certification tests.
     */
    public function run(): void
    {
        $now = now();

        $environments = [
            // ===============================================
            // BEGINNER TUTORIALS
            // ===============================================
            [
                'uuid' => Str::uuid()->toString(),
                'name' => 'Introduction to OSINT Event Documentation',
                'description' => 'Learn the fundamentals of documenting events in the OSINT platform. This tutorial walks you through creating your first event entry, adding media, and understanding verification workflows.',
                'environment_type' => 'tutorial',
                'difficulty' => 'beginner',
                'base_scenario' => json_encode([
                    'scenario_name' => 'Sample Conflict Zone',
                    'scenario_description' => 'A simulated conflict zone with pre-populated actors and basic events for learning.',
                    'initial_data' => [
                        'conflicts' => [
                            ['name' => 'Training Conflict Alpha', 'status' => 'active'],
                        ],
                        'actors' => [
                            ['name' => 'Blue Force', 'type' => 'state_actor'],
                            ['name' => 'Red Force', 'type' => 'state_actor'],
                        ],
                        'sample_events' => 3,
                        'sample_equipment' => true,
                    ],
                    'sandbox_mode' => true,
                    'data_persists' => false,
                ]),
                'objectives' => json_encode([
                    [
                        'id' => 'obj_1',
                        'title' => 'Create Your First Event',
                        'description' => 'Add a new event to the platform with basic information (title, date, location).',
                        'type' => 'action',
                        'required_action' => 'create_event',
                        'hints' => [
                            'Click the "New Event" button in the sidebar',
                            'Fill in the required fields: title, date, and approximate location',
                            'Select an event type that matches your scenario',
                        ],
                        'points' => 10,
                    ],
                    [
                        'id' => 'obj_2',
                        'title' => 'Add Media Evidence',
                        'description' => 'Attach at least one image or video to your event as evidence.',
                        'type' => 'action',
                        'required_action' => 'add_media',
                        'hints' => [
                            'In the event editor, find the Media section',
                            'Upload an image or paste a URL to external media',
                            'Add a caption describing what the media shows',
                        ],
                        'points' => 15,
                    ],
                    [
                        'id' => 'obj_3',
                        'title' => 'Add a Source Citation',
                        'description' => 'Link your event to at least one source with proper attribution.',
                        'type' => 'action',
                        'required_action' => 'add_source',
                        'hints' => [
                            'Navigate to the Sources section of your event',
                            'Add the URL where you found the information',
                            'Include the source name and date accessed',
                        ],
                        'points' => 15,
                    ],
                    [
                        'id' => 'obj_4',
                        'title' => 'Set Location on Map',
                        'description' => 'Use the map interface to set precise coordinates for your event.',
                        'type' => 'action',
                        'required_action' => 'set_geolocation',
                        'hints' => [
                            'Click the map button to open the geolocation interface',
                            'Use the search box or click directly on the map',
                            'Adjust the marker to the exact location',
                        ],
                        'points' => 20,
                    ],
                    [
                        'id' => 'obj_5',
                        'title' => 'Submit for Verification',
                        'description' => 'Mark your event as ready for verification by other analysts.',
                        'type' => 'action',
                        'required_action' => 'submit_verification',
                        'hints' => [
                            'Review all your entered information',
                            'Click the Submit for Verification button',
                            'Your event will enter the verification queue',
                        ],
                        'points' => 10,
                    ],
                ]),
                'success_criteria' => json_encode([
                    'min_objectives_completed' => 5,
                    'min_points' => 60,
                    'required_objectives' => ['obj_1', 'obj_4'],
                    'time_limit' => null,
                    'completion_message' => 'Congratulations! You have completed the Introduction to Event Documentation. You now understand the basics of adding events to the platform.',
                    'badge_awarded' => 'event_creator_novice',
                ]),
                'time_limit_minutes' => null,
                'skills_covered' => json_encode([
                    'event-documentation',
                    'source-attribution',
                    'basic-geolocation',
                    'media-handling',
                ]),
                'is_active' => true,
                'is_public' => true,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'name' => 'Understanding Equipment Identification',
                'description' => 'Learn how to identify and document military equipment from imagery. This tutorial covers basic recognition techniques and proper equipment logging.',
                'environment_type' => 'tutorial',
                'difficulty' => 'beginner',
                'base_scenario' => json_encode([
                    'scenario_name' => 'Equipment Recognition Training',
                    'scenario_description' => 'A collection of equipment images for identification practice.',
                    'initial_data' => [
                        'equipment_images' => [
                            ['category' => 'tanks', 'count' => 5, 'difficulty' => 'easy'],
                            ['category' => 'aircraft', 'count' => 3, 'difficulty' => 'easy'],
                            ['category' => 'vehicles', 'count' => 5, 'difficulty' => 'easy'],
                        ],
                        'equipment_database_access' => true,
                        'hint_system_enabled' => true,
                    ],
                    'sandbox_mode' => true,
                    'data_persists' => false,
                ]),
                'objectives' => json_encode([
                    [
                        'id' => 'obj_1',
                        'title' => 'Explore the Equipment Database',
                        'description' => 'Browse the equipment database to familiarize yourself with common military equipment.',
                        'type' => 'exploration',
                        'required_action' => 'view_equipment_database',
                        'completion_criteria' => ['categories_viewed' => 3, 'items_viewed' => 10],
                        'hints' => [
                            'Use the equipment search to find specific types',
                            'Note the identifying features in each equipment profile',
                            'Compare similar equipment to understand differences',
                        ],
                        'points' => 10,
                    ],
                    [
                        'id' => 'obj_2',
                        'title' => 'Identify a Main Battle Tank',
                        'description' => 'Correctly identify the tank model shown in the provided image.',
                        'type' => 'quiz',
                        'quiz_config' => [
                            'image_id' => 'training_tank_001',
                            'correct_answer' => 'T-72B3',
                            'options' => ['T-72B3', 'T-80U', 'T-90A', 'Leopard 2A4'],
                            'explanation' => 'The T-72B3 can be identified by its distinctive Kontakt-5 ERA placement, the Sosna-U sight system, and the characteristic road wheels.',
                        ],
                        'hints' => [
                            'Look at the ERA (Explosive Reactive Armor) pattern',
                            'Check the commander\'s sight and turret profile',
                            'Compare road wheel patterns with the database',
                        ],
                        'points' => 20,
                    ],
                    [
                        'id' => 'obj_3',
                        'title' => 'Identify Military Aircraft',
                        'description' => 'Correctly identify the aircraft model from the provided image.',
                        'type' => 'quiz',
                        'quiz_config' => [
                            'image_id' => 'training_aircraft_001',
                            'correct_answer' => 'Su-34',
                            'options' => ['Su-34', 'Su-30SM', 'MiG-29', 'Su-35'],
                            'explanation' => 'The Su-34 is distinguished by its side-by-side cockpit configuration, distinctive nose shape, and the characteristic tail stinger.',
                        ],
                        'hints' => [
                            'Look at the cockpit configuration',
                            'Note the nose and air intake shape',
                            'Check the tail configuration',
                        ],
                        'points' => 20,
                    ],
                    [
                        'id' => 'obj_4',
                        'title' => 'Document Equipment in an Event',
                        'description' => 'Add identified equipment to a practice event with correct categorization.',
                        'type' => 'action',
                        'required_action' => 'add_equipment_to_event',
                        'completion_criteria' => ['equipment_added' => 1, 'correct_identification' => true],
                        'hints' => [
                            'Create or edit an event',
                            'Use the Equipment section to add items',
                            'Search for the correct equipment type',
                            'Add notes about identifying features',
                        ],
                        'points' => 25,
                    ],
                    [
                        'id' => 'obj_5',
                        'title' => 'Explain Your Identification',
                        'description' => 'Write a brief explanation of how you identified the equipment.',
                        'type' => 'text_entry',
                        'completion_criteria' => ['min_words' => 50, 'keywords_required' => ['identify', 'feature']],
                        'hints' => [
                            'Describe the visual features you used',
                            'Mention any reference materials consulted',
                            'Note your confidence level and why',
                        ],
                        'points' => 15,
                    ],
                ]),
                'success_criteria' => json_encode([
                    'min_objectives_completed' => 4,
                    'min_points' => 65,
                    'required_objectives' => ['obj_2', 'obj_4'],
                    'time_limit' => null,
                    'completion_message' => 'Well done! You have completed the Equipment Identification tutorial. You can now identify common military equipment and document it properly.',
                    'badge_awarded' => 'equipment_spotter_novice',
                ]),
                'time_limit_minutes' => null,
                'skills_covered' => json_encode([
                    'equipment-recognition',
                    'military-vehicle-identification',
                    'aircraft-identification',
                    'documentation',
                ]),
                'is_active' => true,
                'is_public' => true,
            ],

            // ===============================================
            // GEOLOCATION EXERCISES
            // ===============================================
            [
                'uuid' => Str::uuid()->toString(),
                'name' => 'Geolocation Fundamentals',
                'description' => 'Practice core geolocation skills by locating images using visible landmarks, environmental clues, and mapping tools. Starts with easier images and progresses to more challenging scenarios.',
                'environment_type' => 'exercise',
                'difficulty' => 'intermediate',
                'base_scenario' => json_encode([
                    'scenario_name' => 'Geolocation Challenge',
                    'scenario_description' => 'A series of images from various locations that must be geolocated using OSINT techniques.',
                    'initial_data' => [
                        'challenge_images' => [
                            [
                                'id' => 'geo_easy_001',
                                'difficulty' => 'easy',
                                'region' => 'Ukraine',
                                'clues' => ['visible_sign', 'distinctive_building', 'road_layout'],
                                'target_accuracy_meters' => 500,
                            ],
                            [
                                'id' => 'geo_easy_002',
                                'difficulty' => 'easy',
                                'region' => 'Syria',
                                'clues' => ['mosque', 'street_sign', 'architecture_style'],
                                'target_accuracy_meters' => 500,
                            ],
                            [
                                'id' => 'geo_medium_001',
                                'difficulty' => 'medium',
                                'region' => 'Eastern Europe',
                                'clues' => ['power_lines', 'vegetation', 'road_marking_style'],
                                'target_accuracy_meters' => 250,
                            ],
                            [
                                'id' => 'geo_medium_002',
                                'difficulty' => 'medium',
                                'region' => 'Middle East',
                                'clues' => ['shadow_direction', 'infrastructure', 'terrain'],
                                'target_accuracy_meters' => 250,
                            ],
                            [
                                'id' => 'geo_hard_001',
                                'difficulty' => 'hard',
                                'region' => 'Rural area',
                                'clues' => ['vegetation_type', 'terrain_features', 'sun_position'],
                                'target_accuracy_meters' => 100,
                            ],
                        ],
                        'tools_available' => [
                            'google_maps',
                            'google_earth',
                            'yandex_maps',
                            'suncalc',
                            'reverse_image_search',
                        ],
                    ],
                    'sandbox_mode' => true,
                    'data_persists' => false,
                ]),
                'objectives' => json_encode([
                    [
                        'id' => 'obj_1',
                        'title' => 'Geolocate Easy Image 1',
                        'description' => 'Find the location of the first image within 500 meters.',
                        'type' => 'geolocation',
                        'target_image' => 'geo_easy_001',
                        'correct_location' => ['lat' => 48.4647, 'lng' => 35.0462],
                        'accuracy_required_meters' => 500,
                        'hints' => [
                            'Look for text in the image - what language is it?',
                            'The building style is distinctive to a certain region',
                            'Use the visible road layout to narrow down location',
                        ],
                        'points' => 15,
                    ],
                    [
                        'id' => 'obj_2',
                        'title' => 'Geolocate Easy Image 2',
                        'description' => 'Find the location of the second image within 500 meters.',
                        'type' => 'geolocation',
                        'target_image' => 'geo_easy_002',
                        'correct_location' => ['lat' => 36.2021, 'lng' => 37.1343],
                        'accuracy_required_meters' => 500,
                        'hints' => [
                            'The mosque architecture can help identify the city',
                            'Arabic text on signs may indicate the city name',
                            'Check Google Maps satellite view for mosque locations',
                        ],
                        'points' => 15,
                    ],
                    [
                        'id' => 'obj_3',
                        'title' => 'Geolocate Medium Image 1',
                        'description' => 'Find the location of the third image within 250 meters.',
                        'type' => 'geolocation',
                        'target_image' => 'geo_medium_001',
                        'correct_location' => ['lat' => 49.8397, 'lng' => 24.0297],
                        'accuracy_required_meters' => 250,
                        'hints' => [
                            'Power line configurations vary by country',
                            'Vegetation and agricultural patterns are regional',
                            'Road marking styles differ between countries',
                        ],
                        'points' => 25,
                    ],
                    [
                        'id' => 'obj_4',
                        'title' => 'Geolocate Medium Image 2',
                        'description' => 'Find the location of the fourth image within 250 meters.',
                        'type' => 'geolocation',
                        'target_image' => 'geo_medium_002',
                        'correct_location' => ['lat' => 33.5138, 'lng' => 36.2765],
                        'accuracy_required_meters' => 250,
                        'hints' => [
                            'Use shadow direction with SunCalc to estimate time',
                            'Infrastructure style helps narrow the country',
                            'Terrain features can be matched with satellite imagery',
                        ],
                        'points' => 25,
                    ],
                    [
                        'id' => 'obj_5',
                        'title' => 'Geolocate Hard Image',
                        'description' => 'Find the location of the challenging image within 100 meters.',
                        'type' => 'geolocation',
                        'target_image' => 'geo_hard_001',
                        'correct_location' => ['lat' => 47.9987, 'lng' => 37.8054],
                        'accuracy_required_meters' => 100,
                        'hints' => [
                            'Analyze vegetation type for climate zone',
                            'Unique terrain features may be visible on satellite',
                            'Combine multiple clues for triangulation',
                        ],
                        'points' => 40,
                    ],
                    [
                        'id' => 'obj_6',
                        'title' => 'Document Your Methodology',
                        'description' => 'Write a methodology report explaining how you geolocated at least one image.',
                        'type' => 'text_entry',
                        'completion_criteria' => [
                            'min_words' => 100,
                            'keywords_required' => ['identify', 'map', 'confirm'],
                        ],
                        'hints' => [
                            'Describe your step-by-step process',
                            'Mention the tools you used',
                            'Explain how you confirmed the location',
                        ],
                        'points' => 20,
                    ],
                ]),
                'success_criteria' => json_encode([
                    'min_objectives_completed' => 4,
                    'min_points' => 80,
                    'required_objectives' => ['obj_1', 'obj_2'],
                    'time_limit' => 90,
                    'completion_message' => 'Excellent work! You have demonstrated solid geolocation skills. Continue practicing with more challenging images to improve your speed and accuracy.',
                    'badge_awarded' => 'geolocation_intermediate',
                ]),
                'time_limit_minutes' => 90,
                'skills_covered' => json_encode([
                    'geolocation',
                    'landmark-recognition',
                    'shadow-analysis',
                    'satellite-imagery',
                    'mapping-tools',
                ]),
                'is_active' => true,
                'is_public' => true,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'name' => 'Advanced Chronolocation Challenge',
                'description' => 'Determine not just WHERE but WHEN images and videos were taken using shadow analysis, weather data, and environmental clues.',
                'environment_type' => 'exercise',
                'difficulty' => 'advanced',
                'base_scenario' => json_encode([
                    'scenario_name' => 'Time Detective',
                    'scenario_description' => 'Given images with known locations, determine the date and time they were captured.',
                    'initial_data' => [
                        'challenge_media' => [
                            [
                                'id' => 'chrono_001',
                                'type' => 'image',
                                'known_location' => ['lat' => 48.8584, 'lng' => 2.2945],
                                'clues' => ['shadow_length', 'shadow_direction'],
                                'target_time_accuracy_hours' => 2,
                            ],
                            [
                                'id' => 'chrono_002',
                                'type' => 'image',
                                'known_location' => ['lat' => 50.4501, 'lng' => 30.5234],
                                'clues' => ['weather_conditions', 'vegetation_state', 'shadow'],
                                'target_date_accuracy_days' => 7,
                            ],
                            [
                                'id' => 'chrono_003',
                                'type' => 'video',
                                'known_location' => ['lat' => 34.0522, 'lng' => -118.2437],
                                'clues' => ['sun_position', 'activity_patterns', 'visible_clocks'],
                                'target_time_accuracy_hours' => 1,
                            ],
                        ],
                        'tools_available' => [
                            'suncalc',
                            'weather_history',
                            'astronomical_data',
                            'google_earth_historical',
                        ],
                    ],
                    'sandbox_mode' => true,
                    'data_persists' => false,
                ]),
                'objectives' => json_encode([
                    [
                        'id' => 'obj_1',
                        'title' => 'Determine Time from Shadows',
                        'description' => 'Calculate the approximate time of day from shadow analysis.',
                        'type' => 'chronolocation',
                        'target_media' => 'chrono_001',
                        'correct_datetime' => '2024-06-15T14:30:00',
                        'time_accuracy_hours' => 2,
                        'hints' => [
                            'Measure the shadow length relative to object height',
                            'Use SunCalc to find when the sun creates that shadow angle',
                            'Consider the shadow direction for east/west determination',
                        ],
                        'points' => 30,
                    ],
                    [
                        'id' => 'obj_2',
                        'title' => 'Determine Season/Date from Environment',
                        'description' => 'Estimate the date based on environmental and weather clues.',
                        'type' => 'chronolocation',
                        'target_media' => 'chrono_002',
                        'correct_datetime' => '2024-03-20',
                        'date_accuracy_days' => 7,
                        'hints' => [
                            'Vegetation state indicates the season',
                            'Check historical weather data for matching conditions',
                            'Look for any date indicators in the scene',
                        ],
                        'points' => 35,
                    ],
                    [
                        'id' => 'obj_3',
                        'title' => 'Video Chronolocation',
                        'description' => 'Determine the time a video was recorded using multiple clues.',
                        'type' => 'chronolocation',
                        'target_media' => 'chrono_003',
                        'correct_datetime' => '2024-08-10T08:45:00',
                        'time_accuracy_hours' => 1,
                        'hints' => [
                            'Look for any visible clocks or timestamps',
                            'Traffic patterns indicate time of day',
                            'Sun position in video frames can be calculated',
                        ],
                        'points' => 40,
                    ],
                    [
                        'id' => 'obj_4',
                        'title' => 'Write Chronolocation Report',
                        'description' => 'Document your complete chronolocation methodology for one of the challenges.',
                        'type' => 'report',
                        'completion_criteria' => [
                            'min_words' => 200,
                            'sections_required' => ['methodology', 'tools_used', 'confidence_level'],
                        ],
                        'points' => 25,
                    ],
                ]),
                'success_criteria' => json_encode([
                    'min_objectives_completed' => 3,
                    'min_points' => 90,
                    'required_objectives' => ['obj_1'],
                    'time_limit' => 120,
                    'completion_message' => 'Outstanding! You have mastered advanced chronolocation techniques. These skills are essential for verifying the authenticity of imagery in conflict documentation.',
                    'badge_awarded' => 'chronolocation_expert',
                ]),
                'time_limit_minutes' => 120,
                'skills_covered' => json_encode([
                    'chronolocation',
                    'shadow-analysis',
                    'weather-correlation',
                    'video-verification',
                    'suncalc',
                ]),
                'is_active' => true,
                'is_public' => true,
            ],

            // ===============================================
            // EQUIPMENT IDENTIFICATION QUIZ
            // ===============================================
            [
                'uuid' => Str::uuid()->toString(),
                'name' => 'Equipment Identification Challenge',
                'description' => 'Test your military equipment recognition skills with this timed quiz featuring tanks, aircraft, ships, and artillery systems from various nations.',
                'environment_type' => 'exercise',
                'difficulty' => 'intermediate',
                'base_scenario' => json_encode([
                    'scenario_name' => 'Equipment Recognition Quiz',
                    'scenario_description' => 'A comprehensive quiz testing identification of military equipment.',
                    'initial_data' => [
                        'quiz_configuration' => [
                            'total_questions' => 25,
                            'categories' => [
                                ['name' => 'Main Battle Tanks', 'questions' => 6],
                                ['name' => 'Infantry Fighting Vehicles', 'questions' => 4],
                                ['name' => 'Artillery Systems', 'questions' => 4],
                                ['name' => 'Aircraft', 'questions' => 5],
                                ['name' => 'Helicopters', 'questions' => 3],
                                ['name' => 'Naval Vessels', 'questions' => 3],
                            ],
                            'answer_format' => 'multiple_choice',
                            'options_per_question' => 4,
                            'show_explanation_after' => true,
                        ],
                        'passing_score' => 70,
                        'equipment_database_access' => false,
                    ],
                    'sandbox_mode' => false,
                    'data_persists' => true,
                ]),
                'objectives' => json_encode([
                    [
                        'id' => 'obj_1',
                        'title' => 'Complete Tank Identification Section',
                        'description' => 'Correctly identify at least 4 of 6 main battle tanks.',
                        'type' => 'quiz_section',
                        'section' => 'Main Battle Tanks',
                        'min_correct' => 4,
                        'points' => 30,
                    ],
                    [
                        'id' => 'obj_2',
                        'title' => 'Complete IFV/APC Section',
                        'description' => 'Correctly identify at least 3 of 4 infantry fighting vehicles.',
                        'type' => 'quiz_section',
                        'section' => 'Infantry Fighting Vehicles',
                        'min_correct' => 3,
                        'points' => 20,
                    ],
                    [
                        'id' => 'obj_3',
                        'title' => 'Complete Artillery Section',
                        'description' => 'Correctly identify at least 3 of 4 artillery systems.',
                        'type' => 'quiz_section',
                        'section' => 'Artillery Systems',
                        'min_correct' => 3,
                        'points' => 20,
                    ],
                    [
                        'id' => 'obj_4',
                        'title' => 'Complete Aircraft Section',
                        'description' => 'Correctly identify at least 3 of 5 aircraft.',
                        'type' => 'quiz_section',
                        'section' => 'Aircraft',
                        'min_correct' => 3,
                        'points' => 25,
                    ],
                    [
                        'id' => 'obj_5',
                        'title' => 'Complete Helicopter Section',
                        'description' => 'Correctly identify at least 2 of 3 helicopters.',
                        'type' => 'quiz_section',
                        'section' => 'Helicopters',
                        'min_correct' => 2,
                        'points' => 15,
                    ],
                    [
                        'id' => 'obj_6',
                        'title' => 'Complete Naval Section',
                        'description' => 'Correctly identify at least 2 of 3 naval vessels.',
                        'type' => 'quiz_section',
                        'section' => 'Naval Vessels',
                        'min_correct' => 2,
                        'points' => 15,
                    ],
                    [
                        'id' => 'obj_7',
                        'title' => 'Achieve Overall Passing Score',
                        'description' => 'Score at least 70% across all sections.',
                        'type' => 'overall_score',
                        'min_percentage' => 70,
                        'points' => 25,
                    ],
                ]),
                'success_criteria' => json_encode([
                    'min_objectives_completed' => 5,
                    'min_points' => 100,
                    'required_objectives' => ['obj_7'],
                    'time_limit' => 45,
                    'completion_message' => 'Great job! You have demonstrated proficient equipment identification skills. Review any questions you missed to continue improving.',
                    'badge_awarded' => 'equipment_identifier_intermediate',
                ]),
                'time_limit_minutes' => 45,
                'skills_covered' => json_encode([
                    'equipment-recognition',
                    'military-vehicle-identification',
                    'aircraft-identification',
                    'naval-vessel-identification',
                    'artillery-identification',
                ]),
                'is_active' => true,
                'is_public' => true,
            ],

            // ===============================================
            // OSINT CERTIFICATION TEST
            // ===============================================
            [
                'uuid' => Str::uuid()->toString(),
                'name' => 'OSINT Analyst Certification Examination',
                'description' => 'Comprehensive examination testing all core OSINT skills. Passing this certification demonstrates proficiency in event documentation, geolocation, equipment identification, source verification, and analytical reporting.',
                'environment_type' => 'certification',
                'difficulty' => 'advanced',
                'base_scenario' => json_encode([
                    'scenario_name' => 'Certification Examination',
                    'scenario_description' => 'A multi-part examination covering all aspects of OSINT analysis.',
                    'initial_data' => [
                        'exam_structure' => [
                            'total_sections' => 5,
                            'total_points' => 500,
                            'passing_score' => 350,
                            'sections' => [
                                [
                                    'name' => 'Theoretical Knowledge',
                                    'type' => 'multiple_choice',
                                    'questions' => 20,
                                    'points' => 100,
                                ],
                                [
                                    'name' => 'Geolocation Practical',
                                    'type' => 'practical',
                                    'challenges' => 3,
                                    'points' => 120,
                                ],
                                [
                                    'name' => 'Equipment Identification',
                                    'type' => 'quiz',
                                    'questions' => 15,
                                    'points' => 75,
                                ],
                                [
                                    'name' => 'Source Verification',
                                    'type' => 'practical',
                                    'challenges' => 2,
                                    'points' => 80,
                                ],
                                [
                                    'name' => 'Analytical Report',
                                    'type' => 'report',
                                    'prompts' => 1,
                                    'points' => 125,
                                ],
                            ],
                        ],
                        'proctored' => true,
                        'one_attempt_per_period' => '30d',
                        'tools_available' => [
                            'google_maps',
                            'suncalc',
                            'reverse_image_search',
                            'equipment_database',
                        ],
                    ],
                    'sandbox_mode' => false,
                    'data_persists' => true,
                ]),
                'objectives' => json_encode([
                    [
                        'id' => 'section_1',
                        'title' => 'Section 1: Theoretical Knowledge',
                        'description' => 'Complete the theoretical knowledge examination covering OSINT methodology, ethics, and best practices.',
                        'type' => 'exam_section',
                        'section_type' => 'multiple_choice',
                        'questions' => 20,
                        'topics' => [
                            'OSINT methodology',
                            'Source reliability assessment',
                            'Ethical considerations',
                            'Legal frameworks',
                            'Verification techniques',
                        ],
                        'passing_score' => 70,
                        'points' => 100,
                    ],
                    [
                        'id' => 'section_2',
                        'title' => 'Section 2: Geolocation Practical',
                        'description' => 'Geolocate three images of varying difficulty within the time limit.',
                        'type' => 'exam_section',
                        'section_type' => 'geolocation',
                        'challenges' => [
                            ['difficulty' => 'easy', 'accuracy' => 500, 'points' => 30],
                            ['difficulty' => 'medium', 'accuracy' => 250, 'points' => 40],
                            ['difficulty' => 'hard', 'accuracy' => 100, 'points' => 50],
                        ],
                        'time_limit_minutes' => 45,
                        'points' => 120,
                    ],
                    [
                        'id' => 'section_3',
                        'title' => 'Section 3: Equipment Identification',
                        'description' => 'Identify military equipment from conflict zone imagery.',
                        'type' => 'exam_section',
                        'section_type' => 'equipment_quiz',
                        'questions' => 15,
                        'categories' => ['tanks', 'aircraft', 'artillery', 'missiles', 'naval'],
                        'passing_score' => 65,
                        'points' => 75,
                    ],
                    [
                        'id' => 'section_4',
                        'title' => 'Section 4: Source Verification',
                        'description' => 'Evaluate the credibility of provided sources and identify potential disinformation.',
                        'type' => 'exam_section',
                        'section_type' => 'verification',
                        'challenges' => [
                            ['type' => 'source_credibility', 'items' => 5],
                            ['type' => 'disinformation_detection', 'items' => 3],
                        ],
                        'time_limit_minutes' => 30,
                        'points' => 80,
                    ],
                    [
                        'id' => 'section_5',
                        'title' => 'Section 5: Analytical Report',
                        'description' => 'Write a comprehensive analytical report based on the provided scenario.',
                        'type' => 'exam_section',
                        'section_type' => 'report',
                        'requirements' => [
                            'min_words' => 500,
                            'required_sections' => [
                                'executive_summary',
                                'methodology',
                                'findings',
                                'source_assessment',
                                'conclusions',
                            ],
                            'evidence_citations' => 3,
                        ],
                        'rubric' => [
                            'clarity_and_structure' => 25,
                            'methodology_explanation' => 25,
                            'evidence_analysis' => 35,
                            'source_attribution' => 20,
                            'conclusions_quality' => 20,
                        ],
                        'time_limit_minutes' => 60,
                        'points' => 125,
                    ],
                    [
                        'id' => 'overall',
                        'title' => 'Certification Requirements',
                        'description' => 'Achieve the overall passing score and minimum requirements.',
                        'type' => 'certification_requirements',
                        'requirements' => [
                            'overall_passing_score' => 350,
                            'no_section_below' => 50,
                            'all_sections_attempted' => true,
                        ],
                    ],
                ]),
                'success_criteria' => json_encode([
                    'min_objectives_completed' => 5,
                    'min_points' => 350,
                    'required_objectives' => ['section_1', 'section_2', 'section_3', 'section_4', 'section_5'],
                    'no_section_below_percentage' => 50,
                    'time_limit' => 180,
                    'completion_message' => 'Congratulations! You have successfully passed the OSINT Analyst Certification Examination. You are now certified as a proficient OSINT analyst. Your certificate will be generated and added to your profile.',
                    'badge_awarded' => 'certified_osint_analyst',
                    'certificate_issued' => true,
                    'certificate_validity_years' => 2,
                ]),
                'time_limit_minutes' => 180,
                'skills_covered' => json_encode([
                    'geolocation',
                    'chronolocation',
                    'equipment-recognition',
                    'source-verification',
                    'disinformation-detection',
                    'analytical-writing',
                    'osint-methodology',
                    'ethical-considerations',
                ]),
                'is_active' => true,
                'is_public' => true,
            ],

            // ===============================================
            // ADDITIONAL SPECIALIZED EXERCISES
            // ===============================================
            [
                'uuid' => Str::uuid()->toString(),
                'name' => 'Disinformation Detection Workshop',
                'description' => 'Learn to identify and analyze disinformation campaigns, including fake accounts, manipulated media, and coordinated inauthentic behavior.',
                'environment_type' => 'exercise',
                'difficulty' => 'advanced',
                'base_scenario' => json_encode([
                    'scenario_name' => 'Disinformation Battlefield',
                    'scenario_description' => 'Practice identifying various disinformation tactics using real-world examples.',
                    'initial_data' => [
                        'case_studies' => [
                            ['type' => 'fake_account_network', 'difficulty' => 'medium'],
                            ['type' => 'manipulated_media', 'difficulty' => 'medium'],
                            ['type' => 'coordinated_campaign', 'difficulty' => 'hard'],
                            ['type' => 'deepfake_detection', 'difficulty' => 'hard'],
                        ],
                        'tools_available' => [
                            'account_analysis',
                            'media_forensics',
                            'network_visualization',
                            'reverse_image_search',
                        ],
                    ],
                    'sandbox_mode' => true,
                    'data_persists' => false,
                ]),
                'objectives' => json_encode([
                    [
                        'id' => 'obj_1',
                        'title' => 'Identify Fake Account Indicators',
                        'description' => 'Analyze a set of social media accounts and identify which are likely fake.',
                        'type' => 'analysis',
                        'correct_identifications' => 5,
                        'false_positive_tolerance' => 1,
                        'points' => 30,
                    ],
                    [
                        'id' => 'obj_2',
                        'title' => 'Detect Manipulated Media',
                        'description' => 'Identify which images in a set have been manipulated and explain how.',
                        'type' => 'media_analysis',
                        'images' => 6,
                        'manipulated_count' => 3,
                        'points' => 35,
                    ],
                    [
                        'id' => 'obj_3',
                        'title' => 'Map Coordinated Campaign',
                        'description' => 'Use network analysis tools to map a coordinated disinformation campaign.',
                        'type' => 'network_analysis',
                        'deliverables' => ['network_visualization', 'key_actors_identified', 'timeline'],
                        'points' => 40,
                    ],
                    [
                        'id' => 'obj_4',
                        'title' => 'Deepfake Detection Challenge',
                        'description' => 'Identify which videos are deepfakes and document the telltale signs.',
                        'type' => 'video_analysis',
                        'videos' => 4,
                        'deepfake_count' => 2,
                        'points' => 35,
                    ],
                    [
                        'id' => 'obj_5',
                        'title' => 'Write Disinformation Report',
                        'description' => 'Compile your findings into a comprehensive disinformation analysis report.',
                        'type' => 'report',
                        'min_words' => 300,
                        'required_sections' => ['executive_summary', 'methodology', 'findings', 'recommendations'],
                        'points' => 30,
                    ],
                ]),
                'success_criteria' => json_encode([
                    'min_objectives_completed' => 4,
                    'min_points' => 120,
                    'required_objectives' => ['obj_1', 'obj_2'],
                    'time_limit' => 120,
                    'completion_message' => 'Excellent work! You have demonstrated strong disinformation detection skills. These abilities are critical for maintaining information integrity.',
                    'badge_awarded' => 'disinfo_detective',
                ]),
                'time_limit_minutes' => 120,
                'skills_covered' => json_encode([
                    'disinformation-detection',
                    'account-analysis',
                    'media-forensics',
                    'network-analysis',
                    'deepfake-detection',
                ]),
                'is_active' => true,
                'is_public' => true,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'name' => 'Satellite Imagery Analysis Fundamentals',
                'description' => 'Learn to analyze satellite imagery for damage assessment, change detection, and military activity monitoring.',
                'environment_type' => 'tutorial',
                'difficulty' => 'intermediate',
                'base_scenario' => json_encode([
                    'scenario_name' => 'Eyes in the Sky',
                    'scenario_description' => 'Practice satellite imagery analysis using before/after comparisons and multi-spectral data.',
                    'initial_data' => [
                        'imagery_sets' => [
                            ['location' => 'Infrastructure', 'type' => 'optical', 'resolution' => '0.5m'],
                            ['location' => 'Urban Area', 'type' => 'optical', 'resolution' => '10m'],
                            ['location' => 'Military Site', 'type' => 'SAR', 'resolution' => '10m'],
                        ],
                        'tools_available' => [
                            'sentinel_hub',
                            'google_earth_engine',
                            'measurement_tools',
                            'spectral_analysis',
                        ],
                    ],
                    'sandbox_mode' => true,
                    'data_persists' => false,
                ]),
                'objectives' => json_encode([
                    [
                        'id' => 'obj_1',
                        'title' => 'Understand Satellite Data Sources',
                        'description' => 'Learn about different satellite imagery providers and their capabilities.',
                        'type' => 'learning',
                        'content_modules' => ['sentinel', 'planet', 'maxar', 'sar_basics'],
                        'quiz_questions' => 5,
                        'points' => 20,
                    ],
                    [
                        'id' => 'obj_2',
                        'title' => 'Perform Damage Assessment',
                        'description' => 'Compare before/after imagery to identify and categorize damage.',
                        'type' => 'analysis',
                        'deliverables' => ['damage_locations_marked', 'severity_assessed', 'area_calculated'],
                        'accuracy_threshold' => 80,
                        'points' => 35,
                    ],
                    [
                        'id' => 'obj_3',
                        'title' => 'Detect Military Activity',
                        'description' => 'Analyze imagery to identify military equipment and activity.',
                        'type' => 'analysis',
                        'targets' => ['vehicle_concentrations', 'defensive_positions', 'logistics'],
                        'points' => 35,
                    ],
                    [
                        'id' => 'obj_4',
                        'title' => 'Create Change Detection Report',
                        'description' => 'Document changes observed in satellite imagery over time.',
                        'type' => 'report',
                        'min_images' => 2,
                        'required_elements' => ['timeline', 'annotations', 'analysis'],
                        'points' => 30,
                    ],
                ]),
                'success_criteria' => json_encode([
                    'min_objectives_completed' => 3,
                    'min_points' => 80,
                    'required_objectives' => ['obj_1', 'obj_2'],
                    'time_limit' => null,
                    'completion_message' => 'Well done! You now have foundational skills in satellite imagery analysis. Continue practicing with different imagery types and scenarios.',
                    'badge_awarded' => 'satellite_analyst_novice',
                ]),
                'time_limit_minutes' => null,
                'skills_covered' => json_encode([
                    'satellite-imagery',
                    'damage-assessment',
                    'change-detection',
                    'imagery-interpretation',
                ]),
                'is_active' => true,
                'is_public' => true,
            ],
        ];

        foreach ($environments as $environment) {
            DB::table('training_environments')->insert([
                ...$environment,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }
}
